"""Tests for generated CLI and SDK reference documentation.

Run: pytest tests/unit/docs/test_generate_reference.py

Covers public-surface collection, deterministic rendering, stale checks, and import safety.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import sys
from dataclasses import asdict
from pathlib import Path

import pytest
import valkyrie.sdk as sdk

from scripts import generate_reference

_EXPECTED_CLI_PATHS = (
    "run analyze",
    "run errors",
    "run fetch",
    "run list",
    "run output",
    "run outputs",
    "run results",
    "run resume",
    "run retry",
    "run start",
    "run status",
    "run stop",
    "run update",
    "agent install",
    "agent push",
    "agent remove",
    "agent download",
    "agent list",
    "benchmark tasks",
    "config auth set",
    "config auth remove",
    "config auth list",
    "config init",
    "config set",
    "config remove",
    "config provider set",
    "config provider default",
    "config provider remove",
    "config provider list",
    "config service set",
    "config service remove",
    "config service list",
)
_EXPECTED_MODELS = {
    "Agents": (
        ("AgentContractRequest", "agent-contract-request"),
        ("AgentDownloadURLResponse", "agent-download-url-response"),
        ("AgentEntry", "agent-entry"),
        ("AgentsResponse", "agents-response"),
    ),
    "Runs": (
        ("AnalyzeEvent", "analyze-event"),
        ("FetchBenchmarkResponse", "fetch-benchmark-response"),
        ("FetchBenchmarkMetadataResponse", "fetch-benchmark-metadata-response"),
        ("FetchBenchmarksRequest", "fetch-benchmarks-request"),
        ("FetchBenchmarksResponse", "fetch-benchmarks-response"),
        ("FinalViewResponse", "final-view-response"),
        ("RetryOrResumeBenchmarkResponse", "retry-or-resume-benchmark-response"),
        ("ResultsExistResponse", "results-exist-response"),
        ("S3UploadResultsResponse", "s3-upload-results-response"),
        ("StartBenchmarkResponse", "start-benchmark-response"),
        ("StopBenchmarkResponse", "stop-benchmark-response"),
    ),
    "Benchmarks": (
        ("BenchmarkStatusEntry", "benchmark-status-entry"),
        ("BenchmarkStatusResponse", "benchmark-status-response"),
        ("FetchTasksRequest", "fetch-tasks-request"),
        ("SingleBenchmarkResponse", "single-benchmark-response"),
        ("SingleTaskResponse", "single-task-response"),
        ("TaskArtifactsResponse", "task-artifacts-response"),
        ("TasksResponse", "tasks-response"),
        ("TaskSummary", "task-summary"),
    ),
    "Services": (
        ("BenchmarkServiceCatalogResponse", "benchmark-service-catalog-response"),
        ("BenchmarkServiceEntry", "benchmark-service-entry"),
        ("BenchmarkServiceHealth", "benchmark-service-health"),
        ("BenchmarkServicesResponse", "benchmark-services-response"),
    ),
    "Config": (("ValkyrieConfig", "valkyrie-config"),),
}
_EXPECTED_ENUMS = (
    ("BenchmarkStatus", "Runs", "benchmark-status"),
    ("Order", "Runs", "order"),
    ("RetryMode", "Runs", "retry-mode"),
    ("TaskStatus", "Runs", "task-status"),
)
_EXPECTED_CLI_HTTP_PATHS = {
    "run analyze",
    "run errors",
    "run fetch",
    "run list",
    "run outputs",
    "run results",
    "run resume",
    "run retry",
    "run start",
    "run status",
    "run stop",
    "run update",
    "benchmark tasks",
    "config init",
    "config service list",
}
_EXPECTED_CLI_HTTP_COUNTS = {
    "run analyze": 2,
    "run errors": 1,
    "run fetch": 3,
    "run list": 1,
    "run outputs": 2,
    "run results": 3,
    "run resume": 5,
    "run retry": 5,
    "run start": 3,
    "run status": 1,
    "run stop": 1,
    "run update": 1,
    "benchmark tasks": 1,
    "config init": 1,
    "config service list": 2,
}
_EXPECTED_RESOURCES = {
    "RunsResource": (
        "start",
        "fetch",
        "list",
        "stream",
        "results",
        "metadata",
        "results_exist",
        "analyze",
        "stream_outputs",
        "stop",
        "resume",
        "retry",
    ),
    "BenchmarksResource": ("fetch", "statuses", "tasks", "task", "artifacts"),
    "AgentsResource": ("list", "download_url"),
    "BenchmarkServicesResource": ("catalog", "list", "task_ids"),
}
_GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"


def _command_by_path(path: str) -> generate_reference.CLICommandReference:
    commands = generate_reference.collect_cli_commands()
    return next(command for command in commands if " ".join(command.path) == path)


def _option_by_name(
    command: generate_reference.CLICommandReference,
    name: str,
) -> generate_reference.CLIParameterReference:
    return next(parameter for parameter in command.parameters if parameter.name == name)


def _request_fields(request: generate_reference.HTTPRequest) -> tuple[object, ...]:
    return (
        request.label,
        request.method,
        request.path,
        request.query,
        request.body,
        request.mutating,
        request.harness_headers,
        request.note,
    )


def _request_matrix(requests: tuple[generate_reference.HTTPRequest, ...]) -> tuple[tuple[object, ...], ...]:
    return tuple(_request_fields(request) for request in requests)


def _flatten_navigation(items: list[object]) -> list[str]:
    pages: list[str] = []
    for item in items:
        if isinstance(item, str):
            pages.append(item)
            continue
        assert isinstance(item, dict)
        nested = item.get("pages")
        assert isinstance(nested, list)
        pages.extend(_flatten_navigation(nested))
    return pages


class TestCLIReferenceCollection:
    """Collection of the complete registered Click command tree."""

    def test_preserves_every_leaf_command_in_registration_order(self) -> None:
        """
        Verify that collection preserves the current registered command contract.

        Test cases:
        - All 32 leaf paths appear.
        - Registration order is unchanged.
        - Retry remains a separate leaf beside resume.
        """
        commands = generate_reference.collect_cli_commands()
        command_paths = tuple(" ".join(command.path) for command in commands)

        assert command_paths == _EXPECTED_CLI_PATHS
        assert command_paths.index("run resume") + 1 == command_paths.index("run retry")

    def test_maps_each_cli_leaf_to_one_endpoint_style_page(self) -> None:
        """
        Verify that every registered command has one focused generated page.

        Test cases:
        - Command paths map to nested file paths.
        - Every command page uses a right-side Panel.
        - No page declares a fake HTTP API endpoint.
        """
        commands = generate_reference.collect_cli_commands()
        rendered = generate_reference.render_reference()
        command_paths = {generate_reference._cli_command_path(command) for command in commands}

        assert len(command_paths) == 32
        assert all(path in rendered for path in command_paths)
        assert all("<Panel>" in rendered[path] for path in command_paths)
        assert all("```bash Syntax" in rendered[path] for path in command_paths)
        assert all("api:" not in rendered[path] for path in command_paths)

    def test_renders_complete_syntax_and_exact_http_matrix(self) -> None:
        """Verify complete CLI syntax and explicit tracker/local classification."""
        commands = generate_reference.collect_cli_commands()
        rendered = generate_reference.render_reference()
        http_paths: set[str] = set()

        for command in commands:
            page = rendered[generate_reference._cli_command_path(command)]
            syntax = page.split("```bash Syntax\n", 1)[1].split("\n```", 1)[0]
            cursor = -1
            for parameter in command.parameters:
                positions: list[int] = []
                for declaration in parameter.declarations:
                    token = declaration if parameter.kind == "option" else f"<{declaration}>"
                    matches = list(re.finditer(rf"(?<![A-Za-z0-9-]){re.escape(token)}(?![A-Za-z0-9-])", syntax))
                    assert len(matches) == 1
                    positions.append(matches[0].start())
                assert min(positions) > cursor
                cursor = max(positions)
            if "```bash HTTP" in page:
                http_paths.add(" ".join(command.path))

        assert http_paths == _EXPECTED_CLI_HTTP_PATHS
        assert len(http_paths) == 15
        assert set(_EXPECTED_CLI_PATHS) - http_paths == {" ".join(path) for path in generate_reference._CLI_LOCAL_PATHS}
        assert len(generate_reference._CLI_LOCAL_PATHS) == 17
        for command_path, request_count in _EXPECTED_CLI_HTTP_COUNTS.items():
            command = _command_by_path(command_path)
            assert len(generate_reference._cli_http_requests(command.path)) == request_count

        expected_connect_tail = (
            generate_reference.HTTPRequest(
                "HTTP connect initial status", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)
            ),
            generate_reference.HTTPRequest(
                "HTTP connect stream",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
        )
        assert generate_reference._cli_http_requests(("run", "start"))[-2:] == expected_connect_tail
        assert generate_reference._cli_http_requests(("run", "resume"))[-2:] == expected_connect_tail
        assert generate_reference._cli_http_requests(("run", "retry"))[-2:] == expected_connect_tail
        start_page = rendered[Path("reference/cli/run/start.mdx")]
        assert "[OPTIONS]" not in start_page
        assert "--agent <TEXT>" in start_page
        assert "[--count|-n <INTEGER>]" in start_page
        assert "$VALKYRIE_BASE_URL/start-benchmark" in start_page
        assert '"X-Api-Key: $VALS_API_KEY"' in start_page
        assert '"X-Harness-Aws-Access-Key-Id: $AWS_ACCESS_KEY_ID"' in start_page
        assert '"X-Harness-S3-Bucket: $S3_BUCKET"' in start_page
        assert "# Example only — review before running" in start_page
        stop_http = (
            rendered[Path("reference/cli/run/stop.mdx")].split("```bash HTTP primary\n", 1)[1].split("\n```", 1)[0]
        )
        assert "--force" not in stop_http
        assert "s3=false" in rendered[Path("reference/cli/run/results.mdx")]
        assert "s3=true" in rendered[Path("reference/cli/run/results.mdx")]

        init_page = rendered[Path("reference/cli/config/init.mdx")]
        init_http = init_page.split("```bash HTTP hosted mode\n", 1)[1].split("\n```", 1)[0]
        assert "$VALKYRIE_BASE_URL/init" in init_http
        assert '"X-Api-Key: $VALS_API_KEY"' in init_http
        assert "X-Harness-" not in init_http
        assert "Hosted setup" in init_page

        stop_page = rendered[Path("reference/cli/run/stop.mdx")]
        assert "valkyrie run stop $RUN_ID" in stop_page
        assert "valkyrie run stop $RUN_ID --force" not in stop_page
        auth_page = rendered[Path("reference/cli/config/auth/set.mdx")]
        assert "$BENCHMARK_CREDENTIAL" in auth_page
        assert "my-secret-credential" not in auth_page

    def test_cli_request_metadata_matrix_is_fully_structured(self) -> None:
        """Verify every CLI request exposes every HTTPRequest field for exact comparison."""
        matrix = {
            " ".join(command.path): _request_matrix(generate_reference._cli_http_requests(command.path))
            for command in generate_reference.collect_cli_commands()
            if generate_reference._cli_http_requests(command.path)
        }

        assert set(matrix) == _EXPECTED_CLI_HTTP_PATHS
        assert {path: len(requests) for path, requests in matrix.items()} == _EXPECTED_CLI_HTTP_COUNTS
        assert all(len(fields) == 8 for requests in matrix.values() for fields in requests)
        assert matrix["config init"] == (
            (
                "HTTP hosted mode",
                "POST",
                "/init",
                (),
                None,
                True,
                False,
                "Hosted setup validates the API key with this request. Self-hosted setup does not call Tracker.",
            ),
        )
        assert tuple(fields[:4] for fields in matrix["run start"][-2:]) == (
            ("HTTP connect initial status", "GET", "/fetch-benchmark", (("benchmark_id", "$RUN_ID"),)),
            (
                "HTTP connect stream",
                "GET",
                "/fetch-benchmark",
                (("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
        )
        assert matrix["run results"][1][7].startswith("Only `--s3`")
        assert matrix["config service list"][1][4] is not None
        serialized = {
            " ".join(command.path): [asdict(request) for request in generate_reference._cli_http_requests(command.path)]
            for command in generate_reference.collect_cli_commands()
            if generate_reference._cli_http_requests(command.path)
        }
        digest = hashlib.sha256(json.dumps(serialized, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        assert digest == "268f9fb39ab95e133ebb206380e82a35ac2e5cc70fd4ac6cefdf7a1caabfbca4"

    def test_renders_cli_parameters_as_ordered_compact_rows(self) -> None:
        """Verify that CLI metadata stays complete in compact source-order rows."""
        rendered = generate_reference.render_reference()
        page = rendered[Path("reference/cli/run/start.mdx")]

        assert '## Options\n\n<div className="border-b border-gray-200 py-3 dark:border-gray-800">' in page
        name_class = 'className="break-all font-mono text-sm"'
        assert page.index(f"<span {name_class}>--agent</span>") < page.index(f"<span {name_class}>--model</span>")
        assert page.index(f"<span {name_class}>--model</span>") < page.index(f"<span {name_class}>--benchmark</span>")
        assert f"<span {name_class}>--agent</span><span" in page
        assert "<code>--agent</code>" not in page
        assert "required · <code>text</code>" in page
        assert "optional · <code>integer</code> · default: <code>5</code> · constraints: &gt;= 1" in page
        assert f"<span {name_class}>--secret, -s</span><span" in page
        assert "constraints: 2 values; repeatable" in page
        assert '<p className="mb-0 mt-1">Secret as ENV_VAR aws_secret_name' in page
        assert "### Required" not in page
        assert "### Optional" not in page
        assert page.count("\n---\n") == 1
        assert "<ParamField" not in page
        assert "| Name | Type | Required | Default | Constraints | Description |" not in page

    def test_formats_multi_group_cli_examples_with_shell_continuations(self) -> None:
        """Verify every concrete multi-group example is readable and shell-valid."""
        rendered = generate_reference.render_reference()
        for command in generate_reference.collect_cli_commands():
            if command.example is None:
                continue
            page = rendered[generate_reference._cli_command_path(command)]
            example = page.split("```bash Example\n", 1)[1].split("\n```", 1)[0]
            command_lines = [line for line in example.splitlines() if line and not line.startswith("#")]
            if len(command_lines) > 1:
                assert all(line.endswith("\\") for line in command_lines[:-1])
                assert all(line.startswith("  ") for line in command_lines[1:])
            subprocess.run(["bash", "-n"], input=example, text=True, check=True)

    def test_captures_representative_click_parameter_metadata(self) -> None:
        """
        Verify that Click declarations become stable structural metadata.

        Test cases:
        - Required aliases, integer ranges, repeatable tuples, choices, paths, and UUIDs retain their shape.
        - Unset defaults remain distinct from explicit None and false defaults.
        """
        start = _command_by_path("run start")
        agent = _option_by_name(start, "agent")
        concurrency = _option_by_name(start, "concurrency")
        secrets = _option_by_name(start, "secrets")
        count = _option_by_name(start, "count")
        status = _command_by_path("run status")
        errors = _command_by_path("run errors")
        output = _command_by_path("run output")

        assert agent.required is True
        assert agent.default is None
        assert concurrency.default == "5"
        assert concurrency.constraints == (">= 1",)
        assert secrets.declarations == ("--secret", "-s")
        assert secrets.multiple is True
        assert secrets.nargs == 2
        assert secrets.type_name == "tuple[text, text]"
        assert count.constraints == (">= 1", "<= 10")
        assert _option_by_name(status, "run_ids_value").required is True
        assert _option_by_name(errors, "output_format").constraints == (
            "one of `text`, `json`",
            "case-insensitive",
        )
        assert output.parameters[0].type_name == "UUID"
        assert _option_by_name(output, "output_dir").type_name == "path"
        assert _option_by_name(output, "output_dir").constraints == ("readable",)


class TestSDKReferenceCollection:
    """Collection of the tested public SDK contract."""

    def test_matches_public_exports_resources_and_overloads(self) -> None:
        """
        Verify that the reference follows the tested public SDK boundary.

        Test cases:
        - Top-level exports retain __all__ order.
        - Every approved resource method appears.
        - Results retains all three overload signatures.
        """
        reference = generate_reference.collect_sdk_reference()

        assert tuple(export.name for export in reference.exports) == tuple(sdk.__all__)
        assert len(reference.exports) == 39
        assert {
            resource.name: tuple(method.name for method in resource.methods) for resource in reference.resources
        } == (_EXPECTED_RESOURCES)

        runs = next(resource for resource in reference.resources if resource.name == "RunsResource")
        results = next(method for method in runs.methods if method.name == "results")

        assert len(results.signatures) == 3
        assert "Literal[False]" in results.signatures[0]
        assert "Literal[True]" in results.signatures[1]
        assert "RetrieveResultsResponse" in results.signatures[2]

    def test_maps_each_public_resource_method_to_one_endpoint_style_page(self) -> None:
        """
        Verify that every approved SDK method has one focused generated page.

        Test cases:
        - All 22 methods map to nested resource paths.
        - Every method page pins exact signatures in a Panel.
        - Results keeps separate overload blocks without an HTTP endpoint declaration.
        """
        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()
        method_paths = {
            generate_reference._sdk_method_path(generate_reference._RESOURCE_PAGES[resource.name], method)
            for resource in reference.resources
            for method in resource.methods
        }

        assert len(method_paths) == 22
        assert all(path in rendered for path in method_paths)
        assert all("<Panel>" in rendered[path] for path in method_paths)
        assert all("```python" in rendered[path] for path in method_paths)
        assert all("api:" not in rendered[path] for path in method_paths)
        assert rendered[Path("reference/sdk/runs/results.mdx")].count("```python Overload") == 3

    def test_renders_sdk_method_and_client_parameters_as_ordered_compact_rows(self) -> None:
        """Verify that SDK callable parameters use compact source-order rows."""
        rendered = generate_reference.render_reference()
        method_page = rendered[Path("reference/sdk/runs/start.mdx")]
        client_page = rendered[Path("reference/sdk/client.mdx")]

        assert '## Parameters\n\n<div className="border-b border-gray-200 py-3 dark:border-gray-800">' in method_page
        name_class = 'className="break-all font-mono text-sm"'
        assert method_page.index(f"<span {name_class}>agent</span>") < method_page.index(
            f"<span {name_class}>benchmark</span>"
        )
        assert method_page.index(f"<span {name_class}>benchmark</span>") < method_page.index(
            f"<span {name_class}>model</span>"
        )
        assert "<code>agent</code>" not in method_page
        assert (
            'required · str | <a href="/reference/sdk/models/agents/agent-contract-request"><code>AgentContractRequest</code></a>'
            in method_page
        )
        assert "optional · int · default: <code>5</code>" in method_page
        assert "### Required" not in method_page
        assert "### Optional" not in method_page
        assert method_page.count("\n---\n") == 1
        assert "<ParamField" not in method_page
        assert "| Name | Type | Required | Default |" not in method_page

        assert '### Parameters\n\n<div className="border-b border-gray-200 py-3 dark:border-gray-800">' in client_page
        assert client_page.index(f"<span {name_class}>config</span>") < client_page.index(
            f"<span {name_class}>base_url</span>"
        )
        assert (
            'required · <a href="/reference/sdk/models/config/valkyrie-config"><code>ValkyrieConfig</code></a>'
            in client_page
        )
        assert "optional · float | httpx.Timeout · default: <code>120</code>" in client_page
        assert "#### Required" not in client_page
        assert "#### Optional" not in client_page
        assert "<ParamField" not in client_page
        assert "| Name | Type | Required | Default |" not in client_page

    def test_generates_exact_public_type_pages_and_safe_slugs(self) -> None:
        """Verify the exact 28-model and four-enum public page contract."""
        reference = generate_reference.collect_sdk_reference()
        models_by_family: dict[str, list[tuple[str, str]]] = {}
        for model in reference.models:
            models_by_family.setdefault(model.family, []).append((model.name, model.slug))

        assert {family: tuple(entries) for family, entries in models_by_family.items()} == _EXPECTED_MODELS
        assert tuple((enum.name, enum.family, enum.slug) for enum in reference.enums) == _EXPECTED_ENUMS
        assert len(reference.models) == 28
        assert len(reference.enums) == 4
        assert generate_reference._type_slug("AgentDownloadURLResponse") == "agent-download-url-response"

        duplicate = generate_reference.SDKEnumReference(
            name="Other",
            module="valkyrie.sdk.models.runs",
            family="Runs",
            slug="order",
            description="",
            members=(),
        )
        order = next(enum for enum in reference.enums if enum.name == "Order")
        with pytest.raises(ValueError, match="Duplicate public type path"):
            generate_reference._validate_type_paths((order, duplicate))
        with pytest.raises(ValueError, match="Unsafe public type slug"):
            generate_reference._type_slug("---")

    def test_links_only_exact_public_types_across_pages(self) -> None:
        """Verify public nested tokens link without exposing private models."""
        rendered = generate_reference.render_reference()
        request_page = rendered[Path("reference/sdk/models/runs/fetch-benchmarks-request.mdx")]
        agents_page = rendered[Path("reference/sdk/models/agents/agents-response.mdx")]
        start_page = rendered[Path("reference/sdk/runs/start.mdx")]
        fetch_page = rendered[Path("reference/sdk/models/runs/fetch-benchmark-response.mdx")]

        assert 'href="/reference/sdk/models/runs/benchmark-status"' in request_page
        assert 'href="/reference/sdk/models/runs/order"' in request_page
        assert 'href="/reference/sdk/models/agents/agent-entry"' in agents_page
        assert 'href="/reference/sdk/models/agents/agent-contract-request"' in start_page
        assert 'href="/reference/sdk/models/runs/start-benchmark-response"' in start_page
        assert "BenchmarkDetails" in fetch_page
        assert "models/runs/benchmark-details" not in fetch_page

    def test_adds_verified_http_to_all_resource_methods(self) -> None:
        """Verify every one of the 22 SDK methods includes its tested wire call."""
        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()
        method_pages = [
            rendered[generate_reference._sdk_method_path(generate_reference._RESOURCE_PAGES[resource.name], method)]
            for resource in reference.resources
            for method in resource.methods
        ]

        assert len(method_pages) == 22
        assert all("```bash HTTP" in page for page in method_pages)
        assert 'curl --get "$VALKYRIE_BASE_URL/fetch-benchmark"' in rendered[Path("reference/sdk/runs/fetch.mdx")]
        assert '--data-urlencode "benchmark_id=$RUN_ID"' in rendered[Path("reference/sdk/runs/fetch.mdx")]
        assert '"X-Harness-Log-Group: $LOG_GROUP"' in rendered[Path("reference/sdk/runs/fetch.mdx")]
        assert (
            "$VALKYRIE_BASE_URL/agents/agent%20one/download-url"
            in rendered[Path("reference/sdk/agents/download_url.mdx")]
        )
        assert (
            "$VALKYRIE_BASE_URL/benchmarks/$RUN_ID/tasks/task%20one/artifacts"
            in rendered[Path("reference/sdk/benchmarks/artifacts.mdx")]
        )
        service_catalog = rendered[Path("reference/sdk/services/catalog.mdx")]
        service_list = rendered[Path("reference/sdk/services/list.mdx")]
        assert 'curl --request GET "$VALKYRIE_BASE_URL/benchmark-services"' in service_catalog
        assert 'curl --request GET "$VALKYRIE_BASE_URL/benchmark-services"' in service_list
        assert 'curl --request POST "$VALKYRIE_BASE_URL/benchmark-services"' in service_list
        assert '"services": [' in service_list
        assert '"name": "benchmark-name"' in service_list

        stop_page = rendered[Path("reference/sdk/runs/stop.mdx")]
        assert "```bash HTTP no task selection" in stop_page
        assert "```bash HTTP selected tasks" in stop_page
        assert '"task_ids": [' in stop_page
        assert '"task-id"' in stop_page

        assert "URL-encode the agent-name path segment" in rendered[Path("reference/sdk/agents/download_url.mdx")]
        assert "URL-encode the task-id path segment" in rendered[Path("reference/sdk/benchmarks/task.mdx")]
        assert "X-Harness-Aws-Session-Token: $AWS_SESSION_TOKEN" in rendered[Path("reference/sdk/runs/fetch.mdx")]
        assert "quoted JSON heredoc does not expand shell variables" in rendered[Path("reference/sdk/runs/start.mdx")]
        assert "```bash HTTP" not in rendered[Path("reference/sdk/client.mdx")]
        assert "```bash HTTP" not in rendered[Path("reference/sdk/errors.mdx")]

    def test_sdk_request_metadata_matrix_is_fully_structured(self) -> None:
        """Verify all 22 SDK methods use field-testable HTTPRequest metadata."""
        reference = generate_reference.collect_sdk_reference()
        matrix = {
            (resource.name, method.name): _request_matrix(
                generate_reference._sdk_http_requests(resource.name, method.name)
            )
            for resource in reference.resources
            for method in resource.methods
        }

        assert set(matrix) == {
            (resource, method) for resource, methods in _EXPECTED_RESOURCES.items() for method in methods
        }
        assert len(matrix) == 22
        assert all(len(fields) == 8 for requests in matrix.values() for fields in requests)
        assert all(fields[1] in {"GET", "POST"} for requests in matrix.values() for fields in requests)
        assert matrix[("RunsResource", "fetch")][0][:4] == (
            "HTTP",
            "GET",
            "/fetch-benchmark",
            (("benchmark_id", "$RUN_ID"),),
        )
        assert tuple(fields[:5] for fields in matrix[("RunsResource", "stop")]) == (
            ("HTTP no task selection", "POST", "/stop-benchmark/$RUN_ID", (("force", "false"),), None),
            (
                "HTTP selected tasks",
                "POST",
                "/stop-benchmark/$RUN_ID",
                (("force", "false"),),
                '{"task_ids":["task-id"]}',
            ),
        )
        assert matrix[("BenchmarkServicesResource", "list")][1][1:5] == (
            "POST",
            "/benchmark-services",
            (),
            '{"services":[{"name":"benchmark-name","url":"https://benchmark.example.com","auth_header_name":null,"auth_secret_name":null}]}',
        )
        assert "single-quoted JSON does not expand shell variables" in matrix[("RunsResource", "start")][0][7]
        serialized = {
            f"{resource.name}.{method.name}": [
                asdict(request) for request in generate_reference._sdk_http_requests(resource.name, method.name)
            ]
            for resource in reference.resources
            for method in resource.methods
        }
        digest = hashlib.sha256(json.dumps(serialized, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        assert digest == "2d6b8935520fc823bcffe33a97d2f31443f2cf386c2f83d720e8eaaed09bb96f"

    def test_captures_public_model_defaults_aliases_constraints_and_enums(self) -> None:
        """
        Verify that public model metadata remains useful without instantiation.

        Test cases:
        - Default factories render as stable values.
        - Aliases and numeric constraints remain visible.
        - Enum declaration order and values remain intact.
        """
        reference = generate_reference.collect_sdk_reference()
        models = {model.name: model for model in reference.models}
        enums = {enum.name: enum for enum in reference.enums}
        contract_fields = {field.name: field for field in models["AgentContractRequest"].fields}
        task_fields = {field.name: field for field in models["FetchTasksRequest"].fields}
        run_fields = {field.name: field for field in models["FetchBenchmarksRequest"].fields}
        config_fields = {field.name: field for field in models["ValkyrieConfig"].fields}

        assert contract_fields["output_artifacts"].default == "[]"
        assert task_fields["limit"].default == "50"
        assert task_fields["limit"].constraints == (">= 1", "<= 500")
        assert run_fields["order_by"].default == "Order.DESC"
        assert config_fields["aws_access_key_id"].alias == "AWS_ACCESS_KEY_ID"
        assert enums["TaskStatus"].members == (
            ("PENDING", "'PENDING'"),
            ("BUILDING", "'BUILDING'"),
            ("IN_PROGRESS", "'IN_PROGRESS'"),
            ("EVALUATING", "'EVALUATING'"),
            ("STOPPED", "'STOPPED'"),
            ("FINISHED", "'FINISHED'"),
            ("ERROR", "'ERROR'"),
        )


class TestGeneratedReferenceFiles:
    """Rendering, navigation, and stale-output behavior for the generated manifest."""

    def test_render_is_deterministic_and_contains_no_runtime_values(self, monkeypatch) -> None:
        """
        Verify that rendering is stable and independent of credentials and machine state.

        Test cases:
        - Two renders are byte-identical.
        - Every file has frontmatter and the generated marker.
        - Output omits credentials, absolute repository paths, timestamps, and memory addresses.
        """
        monkeypatch.setenv("AWS_ACCESS_KEY_ID", "DO_NOT_RENDER_ACCESS_KEY")
        monkeypatch.setenv("VALS_API_KEY", "DO_NOT_RENDER_VALS_KEY")

        first = generate_reference.render_reference()
        second = generate_reference.render_reference()
        combined = "\n".join(first.values())

        mdx_files = {path: content for path, content in first.items() if path.suffix == ".mdx"}
        navigation_files = {path: content for path, content in first.items() if path.name == "navigation.json"}

        assert first == second
        assert len(first) == 93
        assert len(mdx_files) == 91
        assert len(navigation_files) == 2
        assert all(content.startswith("---\n") for content in mdx_files.values())
        assert all(_GENERATED_MARKER in content for content in mdx_files.values())
        assert all(isinstance(json.loads(content), list) for content in navigation_files.values())
        assert "DO_NOT_RENDER_ACCESS_KEY" not in combined
        assert "DO_NOT_RENDER_VALS_KEY" not in combined
        assert str(Path.cwd()) not in combined
        assert "0x" not in combined
        assert "Generated at" not in combined
        assert "@vals.ai" not in combined
        assert "-s ANTHROPIC_API_KEY AnthropicApiKey" in combined
        assert "$VALS_API_KEY" in combined
        assert "vals-key" not in combined
        assert "aws-session" not in combined
        assert "https://local." not in combined
        assert '"aws_session_token":"$AWS_SESSION_TOKEN"' not in combined
        assert "my-secret-credential" not in combined
        assert " --force" not in combined
        assert "<ParamField" not in combined
        assert "| Name | Type | Required | Default | Constraints | Description |" not in combined
        assert '<span className="break-all font-mono text-sm">--agent</span>' in combined
        assert '<span className="break-all font-mono text-sm">agent</span>' in combined
        assert '<span className="break-all font-mono text-sm">IN_PROGRESS</span>' in combined
        assert "<code>--agent</code>" not in combined
        assert "<code>agent</code><span" not in combined
        assert "<code>IN_PROGRESS</code><span" not in combined

    def test_bash_panels_are_bounded_shell_valid_and_preserve_json(self) -> None:
        """Verify generated shell panels fit narrow views without changing request bodies."""
        rendered = generate_reference.render_reference()
        titled_bash_blocks = [
            match.groups()
            for content in rendered.values()
            for match in re.finditer(r"```bash ([^\n]+)\n(.*?)\n```", content, flags=re.DOTALL)
        ]
        assert titled_bash_blocks
        assert max(len(line) for _, block in titled_bash_blocks for line in block.splitlines()) <= 120
        for title, block in titled_bash_blocks:
            if title != "Syntax":
                subprocess.run(["bash", "-n"], input=block, text=True, check=True)

        bash_blocks = [block for _, block in titled_bash_blocks]
        rendered_bodies = [
            match.group(1)
            for block in bash_blocks
            for match in re.finditer(r"--data @- <<'JSON'\n(.*?)\nJSON", block, flags=re.DOTALL)
        ]
        metadata_bodies = [
            request.body
            for command in generate_reference.collect_cli_commands()
            for request in generate_reference._cli_http_requests(command.path)
            if request.body is not None
        ]
        reference = generate_reference.collect_sdk_reference()
        metadata_bodies.extend(
            request.body
            for resource in reference.resources
            for method in resource.methods
            for request in generate_reference._sdk_http_requests(resource.name, method.name)
            if request.body is not None
        )
        assert [json.loads(body) for body in rendered_bodies] == [json.loads(body) for body in metadata_bodies]

    def test_navigation_contains_each_generated_page_once_and_docs_json_uses_refs(self) -> None:
        """
        Verify that generated nested navigation is complete and uniquely referenced.

        Test cases:
        - CLI navigation contains the index and all 32 command pages once.
        - SDK navigation contains the index, client, 22 method pages, models, and errors once.
        - docs.json resolves each reference group through its generated navigation file.
        """
        rendered = generate_reference.render_reference()
        cli_navigation = json.loads(rendered[Path("reference/cli/navigation.json")])
        sdk_navigation = json.loads(rendered[Path("reference/sdk/navigation.json")])
        assert isinstance(cli_navigation, list)
        assert isinstance(sdk_navigation, list)

        cli_pages = _flatten_navigation(cli_navigation)
        sdk_pages = _flatten_navigation(sdk_navigation)

        assert len(cli_pages) == 33
        assert len(cli_pages) == len(set(cli_pages))
        assert len(sdk_pages) == 58
        assert len(sdk_pages) == len(set(sdk_pages))
        assert {Path(page).with_suffix(".mdx") for page in (*cli_pages, *sdk_pages)} == {
            path for path in rendered if path.suffix == ".mdx"
        }

        docs_config = json.loads(Path("docs/docs.json").read_text(encoding="utf-8"))
        groups = {group["group"]: group["pages"] for group in docs_config["navigation"]["groups"]}

        assert groups["CLI reference"] == {"$ref": "reference/cli/navigation.json"}
        assert groups["Python SDK reference"] == {"$ref": "reference/sdk/navigation.json"}

        types_index = rendered[Path("reference/sdk/models/index.mdx")]
        reference = generate_reference.collect_sdk_reference()
        type_entries = (*reference.models, *reference.enums)
        assert all(types_index.count(f"`{entry.name}`") == 1 for entry in type_entries)
        assert all(
            types_index.count(f"/{generate_reference._route(generate_reference._sdk_type_path(entry))}") == 1
            for entry in type_entries
        )

    def test_check_detects_stale_missing_and_unexpected_files_without_writing(self, tmp_path: Path) -> None:
        """
        Verify that check mode reports every generated-manifest drift condition.

        Test cases:
        - Current output passes.
        - Stale and missing files fail without rewriting.
        - Extra marked files fail and are safely removed on regeneration.
        - Unrelated unmarked files remain untouched.
        """
        docs_root = tmp_path / "docs"
        generate_reference.write_reference(docs_root)

        assert generate_reference.check_reference(docs_root) == ()

        stale_path = docs_root / "reference/cli/run/start.mdx"
        stale_path.write_text(_GENERATED_MARKER + "\nstale\n", encoding="utf-8")
        missing_path = docs_root / "reference/sdk/errors.mdx"
        missing_path.unlink()
        unexpected_path = docs_root / "reference/sdk/models.mdx"
        unexpected_path.write_text(_GENERATED_MARKER + "\n", encoding="utf-8")
        unrelated_path = docs_root / "reference/notes.mdx"
        unrelated_path.write_text("Hand-written.\n", encoding="utf-8")

        diagnostics = generate_reference.check_reference(docs_root)

        assert any(message == "stale: reference/cli/run/start.mdx" for message in diagnostics)
        assert any(message == "missing: reference/sdk/errors.mdx" for message in diagnostics)
        assert any(message == "unexpected generated file: reference/sdk/models.mdx" for message in diagnostics)
        assert stale_path.read_text(encoding="utf-8") == _GENERATED_MARKER + "\nstale\n"
        assert not missing_path.exists()
        assert unrelated_path.read_text(encoding="utf-8") == "Hand-written.\n"

        removed = generate_reference.write_reference(docs_root)

        assert removed == (Path("reference/sdk/models.mdx"),)
        assert not unexpected_path.exists()
        assert _GENERATED_MARKER in stale_path.read_text(encoding="utf-8")
        assert missing_path.exists()
        assert unrelated_path.read_text(encoding="utf-8") == "Hand-written.\n"

    def test_write_refuses_to_overwrite_an_unmarked_manifest_path(self, tmp_path: Path) -> None:
        """
        Verify that generation never replaces hand-written content at an owned path.

        Test cases:
        - An unmarked file at an expected path causes a clear failure.
        - The unmarked content remains unchanged.
        """
        docs_root = tmp_path / "docs"
        conflict_path = docs_root / "reference/cli/run/start.mdx"
        conflict_path.parent.mkdir(parents=True)
        conflict_path.write_text("Hand-written.\n", encoding="utf-8")

        with pytest.raises(FileExistsError, match="Refusing to overwrite unmarked file"):
            generate_reference.write_reference(docs_root)

        assert conflict_path.read_text(encoding="utf-8") == "Hand-written.\n"

    def test_collection_is_safe_with_empty_home_and_blocked_network(self, tmp_path: Path) -> None:
        """
        Verify that reference collection does not read user configuration or connect to services.

        Test cases:
        - HOME points to an empty directory.
        - Socket connections raise immediately.
        - Rendering still returns the complete dynamic manifest.
        """
        empty_home = tmp_path / "home"
        empty_home.mkdir()
        script = """
import socket


def blocked_connect(*args, **kwargs):
    raise AssertionError("network access is forbidden")


socket.socket.connect = blocked_connect
from scripts.generate_reference import render_reference
assert len(render_reference()) == 93
"""
        environment = {
            "HOME": str(empty_home),
            "PATH": os.environ.get("PATH", ""),
            "PYTHONPATH": str(Path.cwd()),
        }

        result = subprocess.run(
            [sys.executable, "-c", script],
            cwd=Path.cwd(),
            env=environment,
            capture_output=True,
            text=True,
            check=False,
        )

        assert result.returncode == 0, result.stderr
        assert list(empty_home.iterdir()) == []
