"""Tests for generated CLI and SDK reference documentation.

Run: pytest tests/unit/docs/test_generate_reference.py

Covers public collection, deterministic rendering, links, redirects, and safe file updates.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import cast

import click
import pytest
import valkyrie.sdk as sdk
from valkyrie.sdk import resources as sdk_resources

from scripts import reference_docs as generator
from scripts.reference_docs import collect

_EXPECTED_CLI_PATHS = (
    "run analyze",
    "run errors",
    "run fetch",
    "run list",
    "run output",
    "run outputs",
    "run results",
    "run resume",
    "run retry",
    "run start",
    "run status",
    "run stop",
    "run update",
    "agent install",
    "agent push",
    "agent remove",
    "agent download",
    "agent list",
    "benchmark tasks",
    "config auth set",
    "config auth remove",
    "config auth list",
    "config init",
    "config set",
    "config remove",
    "config provider set",
    "config provider default",
    "config provider remove",
    "config provider list",
    "config service set",
    "config service remove",
    "config service list",
)
_EXPECTED_RESOURCES = {
    "RunsResource": (
        "start",
        "fetch",
        "list",
        "stream",
        "results",
        "metadata",
        "results_exist",
        "analyze",
        "stream_outputs",
        "stop",
        "resume",
        "retry",
    ),
    "BenchmarksResource": ("fetch", "statuses", "tasks", "task", "artifacts"),
    "AgentsResource": ("list", "download_url"),
    "BenchmarkServicesResource": ("catalog", "list", "task_ids"),
}
_EXPECTED_TYPES = {
    "Agents": (
        "AgentContractRequest",
        "AgentDownloadURLResponse",
        "AgentEntry",
        "AgentsResponse",
    ),
    "Runs": (
        "AnalyzeEvent",
        "FetchBenchmarkResponse",
        "FetchBenchmarkMetadataResponse",
        "FetchBenchmarksRequest",
        "FetchBenchmarksResponse",
        "FinalViewResponse",
        "RetryOrResumeBenchmarkResponse",
        "ResultsExistResponse",
        "S3UploadResultsResponse",
        "StartBenchmarkResponse",
        "StopBenchmarkResponse",
        "BenchmarkStatus",
        "Order",
        "RetryMode",
        "TaskStatus",
    ),
    "Benchmarks": (
        "BenchmarkStatusEntry",
        "BenchmarkStatusResponse",
        "FetchTasksRequest",
        "SingleBenchmarkResponse",
        "SingleTaskResponse",
        "TaskArtifactsResponse",
        "TasksResponse",
        "TaskSummary",
    ),
    "Services": (
        "BenchmarkServiceCatalogResponse",
        "BenchmarkServiceEntry",
        "BenchmarkServiceHealth",
        "BenchmarkServicesResponse",
    ),
    "Config": ("ValkyrieConfig",),
}
_GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"
_DOCS_ROOT = Path("docs")


@pytest.fixture(scope="module")
def commands() -> tuple[generator.CLICommandReference, ...]:
    return generator.collect_cli_commands()


@pytest.fixture(scope="module")
def sdk_reference() -> generator.SDKReference:
    return generator.collect_sdk_reference()


@pytest.fixture(scope="module")
def rendered() -> dict[Path, str]:
    return generator.render_reference()


def _route_path(route: str) -> Path:
    return Path(route.partition("#")[0].lstrip("/")).with_suffix(".mdx")


def _command(commands: tuple[generator.CLICommandReference, ...], path: str) -> generator.CLICommandReference:
    return next(command for command in commands if " ".join(command.path) == path)


def _option(command: generator.CLICommandReference, name: str) -> generator.CLIParameterReference:
    return next(parameter for parameter in command.parameters if parameter.name == name)


def _page_with_heading(rendered: dict[Path, str], heading: str) -> tuple[Path, str]:
    pages = [(path, content) for path, content in rendered.items() if path.suffix == ".mdx" and heading in content]
    assert len(pages) == 1
    return pages[0]


def _section(rendered: dict[Path, str], heading: str) -> str:
    _, page = _page_with_heading(rendered, heading)
    remainder = page.split(heading, 1)[1]
    end = remainder.find("\n## ")
    return remainder if end == -1 else remainder[:end]


def _navigation(rendered: dict[Path, str], scope: str) -> tuple[Path, list[object]]:
    candidates = [path for path in rendered if path.name == "navigation.json" and path.parent.name == scope]
    assert len(candidates) == 1
    value = json.loads(rendered[candidates[0]])
    assert isinstance(value, list)
    return candidates[0], cast(list[object], value)


def _flatten(items: list[object]) -> list[str]:
    pages: list[str] = []
    for item in items:
        if isinstance(item, str):
            pages.append(item)
        else:
            assert isinstance(item, dict)
            nested = item["pages"]
            assert isinstance(nested, list)
            pages.extend(_flatten(cast(list[object], nested)))
    return pages


class TestCLIReference:
    """CLI collection and rendering behavior."""

    def test_inventory_metadata_and_syntax(
        self,
        commands: tuple[generator.CLICommandReference, ...],
        rendered: dict[Path, str],
    ) -> None:
        assert tuple(" ".join(command.path) for command in commands) == _EXPECTED_CLI_PATHS

        start = _command(commands, "run start")
        concurrency = _option(start, "concurrency")
        secrets = _option(start, "secrets")
        count = _option(start, "count")

        assert _option(start, "agent").required is True
        assert concurrency.default == "5"
        assert concurrency.constraints == (">= 1",)
        assert secrets.declarations == ("--secret", "-s")
        assert secrets.multiple is True
        assert secrets.nargs == 2
        assert secrets.type_name == "tuple[text, text]"
        assert count.constraints == (">= 1", "<= 10")
        assert _option(_command(commands, "run errors"), "output_format").constraints == (
            "one of `text`, `json`",
            "case-insensitive",
        )

        for command in commands:
            heading = f"## `valkyrie {' '.join(command.path)}` {{#{'-'.join(command.path[1:])}}}"
            section = _section(rendered, heading)
            syntax = section.split("```bash Syntax\n", 1)[1].split("\n```", 1)[0]
            cursor = -1
            for parameter in command.parameters:
                tokens = parameter.declarations if parameter.kind == "option" else (f"<{parameter.declarations[0]}>",)
                matches = [
                    re.search(rf"(?<![A-Za-z0-9-]){re.escape(token)}(?![A-Za-z0-9-])", syntax) for token in tokens
                ]
                assert all(matches)
                positions = [cast(re.Match[str], match).start() for match in matches]
                assert min(positions) > cursor
                cursor = max(positions)

        start_section = _section(rendered, "## `valkyrie run start` {#start}")
        assert "[--secret|-s <TEXT> <TEXT>...]" in start_section
        assert "# Example only, review before running" in start_section
        assert "valkyrie run stop $RUN_ID" in _section(rendered, "## `valkyrie run stop` {#stop}")
        assert "$BENCHMARK_CREDENTIAL" in _section(rendered, "## `valkyrie config auth set` {#auth-set}")

    def test_unsupported_default_fails_collection(self) -> None:
        class Opaque:
            pass

        option = click.Option(["--opaque"], default=Opaque())
        with pytest.raises(TypeError, match="Unsupported default value of type 'Opaque'"):
            collect._collect_click_parameter(option)

    def test_examples_are_shell_valid(self, rendered: dict[Path, str]) -> None:
        blocks = [
            match.groups()
            for content in rendered.values()
            for match in re.finditer(r"```bash ([^\n]+)\n(.*?)\n```", content, re.DOTALL)
        ]
        assert blocks
        assert max(len(line) for _, block in blocks for line in block.splitlines()) <= 120
        for title, block in blocks:
            if title == "Example":
                subprocess.run(["bash", "-n"], input=block, text=True, check=True)


class TestSDKReference:
    """SDK collection and rendering behavior."""

    def test_inventory_overloads_and_metadata(
        self,
        sdk_reference: generator.SDKReference,
        rendered: dict[Path, str],
    ) -> None:
        assert tuple(sdk_reference.exports) == tuple(sdk.__all__)
        assert {
            resource.name: tuple(method.name for method in resource.methods) for resource in sdk_reference.resources
        } == _EXPECTED_RESOURCES

        entries = (*sdk_reference.models, *sdk_reference.enums)
        assert {
            family: tuple(entry.name for entry in entries if entry.family == family) for family in _EXPECTED_TYPES
        } == _EXPECTED_TYPES

        runs = next(resource for resource in sdk_reference.resources if resource.name == "RunsResource")
        results = next(method for method in runs.methods if method.name == "results")
        assert len(results.signatures) == 3
        assert "Literal[False]" in results.signatures[0]
        assert "Literal[True]" in results.signatures[1]
        assert "RetrieveResultsResponse" in results.signatures[2]

        models = {model.name: model for model in sdk_reference.models}
        task_fields = {field.name: field for field in models["FetchTasksRequest"].fields}
        config_fields = {field.name: field for field in models["ValkyrieConfig"].fields}
        assert task_fields["limit"].default == "50"
        assert task_fields["limit"].constraints == (">= 1", "<= 500")
        assert config_fields["aws_access_key_id"].alias == "AWS_ACCESS_KEY_ID"
        assert next(enum for enum in sdk_reference.enums if enum.name == "TaskStatus").members[-1] == (
            "ERROR",
            "'ERROR'",
        )

        combined = "\n".join(rendered.values())
        for export_name in sdk_reference.exports:
            assert export_name in combined

    def test_docstrings_are_collected_at_runtime(self, monkeypatch: pytest.MonkeyPatch) -> None:
        sources = (
            sdk_resources.RunsResource,
            sdk_resources.RunsResource.start,
            sdk.FetchBenchmarksRequest,
            sdk.BenchmarkStatus,
            sdk.ValkyrieAPIError,
            sdk.ValkyrieClient,
            sdk.ValkyrieClient.from_config.__func__,
            sdk.ValkyrieClient.close,
        )
        sentinels = tuple(f"DOCSTRING_SENTINEL_{index}" for index in range(len(sources)))
        for source, sentinel in zip(sources, sentinels, strict=True):
            monkeypatch.setattr(source, "__doc__", sentinel)

        reference = generator.collect_sdk_reference()
        current = generator.render_reference()
        descriptions = [resource.description for resource in reference.resources]
        descriptions.extend(method.description for resource in reference.resources for method in resource.methods)
        descriptions.extend(entry.description for entry in (*reference.models, *reference.enums, *reference.exceptions))
        descriptions.extend(method.description for method in reference.client_methods)
        combined = "\n".join(current.values())

        for sentinel in sentinels:
            assert sentinel in descriptions
            assert sentinel in combined

    def test_public_type_links_and_error_hierarchy(
        self,
        sdk_reference: generator.SDKReference,
        rendered: dict[Path, str],
    ) -> None:
        entries = {entry.name: entry for entry in (*sdk_reference.models, *sdk_reference.enums)}

        def target(name: str) -> str:
            entry = entries[name]
            heading = f"## `{name}` {{#{entry.slug}}}"
            path, _ = _page_with_heading(rendered, heading)
            return f"/{path.with_suffix('').as_posix()}#{entry.slug}"

        request_section = _section(
            rendered,
            f"## `FetchBenchmarksRequest` {{#{entries['FetchBenchmarksRequest'].slug}}}",
        )
        _, agents_page = _page_with_heading(rendered, f"## `AgentEntry` {{#{entries['AgentEntry'].slug}}}")
        runs = next(resource for resource in sdk_reference.resources if resource.name == "RunsResource")
        start_section = _section(rendered, f"## `{runs.client_attribute}.start` {{#start}}")

        assert f'href="{target("BenchmarkStatus")}"' in request_section
        assert f'href="{target("Order")}"' in request_section
        assert f'href="{target("AgentEntry")}"' in agents_page
        assert f'href="{target("AgentContractRequest")}"' in start_section
        assert f'href="{target("StartBenchmarkResponse")}"' in start_section

        config_section = _section(rendered, f"## `ValkyrieConfig` {{#{entries['ValkyrieConfig'].slug}}}")
        agent_contract_section = _section(
            rendered,
            f"## `AgentContractRequest` {{#{entries['AgentContractRequest'].slug}}}",
        )
        assert 'alias: <code>{"AWS_ACCESS_KEY_ID"}</code>' in config_section
        assert 'constraints: {"> 0"}' in config_section
        assert 'default: <code>{"{}"}</code>' in agent_contract_section

        errors = sorted(
            name
            for name in sdk.__all__
            if isinstance(getattr(sdk, name), type) and issubclass(getattr(sdk, name), Exception)
        )
        assert [error.name for error in sdk_reference.exceptions] == errors
        _, error_page = _page_with_heading(rendered, f"## `{errors[0]}`")
        for error in sdk_reference.exceptions:
            assert f"| [`{error.name}`](#{error.name.lower()}) | `{error.parent}` |" in error_page
            assert f"\n{error.signature}\n" in error_page


class TestGeneratedFiles:
    """Manifest, navigation, redirects, and filesystem safety."""

    def test_manifest_is_deterministic_and_navigation_is_complete(self, rendered: dict[Path, str]) -> None:
        assert generator.render_reference() == rendered
        mdx = {path: content for path, content in rendered.items() if path.suffix == ".mdx"}
        json_files = {path: content for path, content in rendered.items() if path.suffix == ".json"}
        assert len(rendered) == 21
        assert len(mdx) == 18
        assert len(json_files) == 3
        assert all(content.startswith("---\n") and _GENERATED_MARKER in content for content in mdx.values())
        assert all(isinstance(json.loads(content), list) for content in json_files.values())

        cli_path, cli_navigation = _navigation(rendered, "cli")
        sdk_path, sdk_navigation = _navigation(rendered, "sdk")
        pages = (*_flatten(cli_navigation), *_flatten(sdk_navigation))
        assert {Path(page).with_suffix(".mdx") for page in pages} == set(mdx)

        config = json.loads((_DOCS_ROOT / "docs.json").read_text(encoding="utf-8"))
        groups = {group["group"]: group["pages"] for group in config["navigation"]["groups"]}
        assert groups["CLI reference"] == {"$ref": cli_path.as_posix()}
        assert groups["Python SDK reference"] == {"$ref": sdk_path.as_posix()}

    def test_redirects_cover_retired_routes_and_resolve(
        self,
        commands: tuple[generator.CLICommandReference, ...],
        sdk_reference: generator.SDKReference,
        rendered: dict[Path, str],
    ) -> None:
        redirect_paths = [path for path in rendered if path.name == "redirects.json"]
        assert len(redirect_paths) == 1
        redirects = cast(list[dict[str, str]], json.loads(rendered[redirect_paths[0]]))
        expected_count = (
            len(generator.STATIC_REDIRECTS)
            + len(commands)
            + sum(len(resource.methods) for resource in sdk_reference.resources)
            + len(sdk_reference.models)
            + len(sdk_reference.enums)
        )
        assert len(redirects) == expected_count
        assert len({entry["source"] for entry in redirects}) == expected_count
        assert all(set(entry) == {"source", "destination"} for entry in redirects)

        by_source = {entry["source"]: entry["destination"] for entry in redirects}
        assert by_source["/reference/cli/run/start"] == "/reference/cli/run#start"
        assert by_source["/reference/sdk/runs/stream_outputs"] == "/reference/sdk/runs#stream-outputs"
        assert (
            by_source["/reference/sdk/models/runs/fetch-benchmarks-request"]
            == "/reference/sdk/models/runs#fetch-benchmarks-request"
        )

        for entry in generator.STATIC_REDIRECTS:
            assert (_DOCS_ROOT / f"{entry['destination'].lstrip('/')}.mdx").is_file()

        for entry in redirects[len(generator.STATIC_REDIRECTS) :]:
            page = _route_path(entry["destination"])
            anchor = entry["destination"].partition("#")[2]
            assert page in rendered
            assert f"{{#{anchor}}}" in rendered[page]

        config = json.loads((_DOCS_ROOT / "docs.json").read_text(encoding="utf-8"))
        assert config["redirects"] == {"$ref": redirect_paths[0].as_posix()}

    def test_handwritten_reference_links_resolve(self, rendered: dict[Path, str]) -> None:
        anchors = {
            path: {
                line.split("{#", 1)[1].split("}", 1)[0]
                for line in content.splitlines()
                if line.startswith("## ") and "{#" in line
            }
            for path, content in rendered.items()
            if path.suffix == ".mdx"
        }
        links: list[str] = []
        for guide in _DOCS_ROOT.rglob("*.mdx"):
            if guide.parts[1] == "reference":
                continue
            links.extend(re.findall(r"\(/reference/[^)]*\)", guide.read_text(encoding="utf-8")))
        assert links
        for link in links:
            route, _, anchor = link[1:-1].partition("#")
            page = (
                Path(route.lstrip("/"), "index.mdx")
                if route.endswith(("/cli", "/sdk", "/models"))
                else Path(route.lstrip("/")).with_suffix(".mdx")
            )
            assert page in rendered
            if anchor:
                assert anchor in anchors[page]

    def test_check_reports_drift_without_writing_and_write_repairs_it(self, tmp_path: Path) -> None:
        docs_root = tmp_path / "docs"
        manifest = generator.render_reference()
        generator.write_reference(docs_root)
        assert generator.check_reference(docs_root) == ()

        mdx = [path for path in manifest if path.suffix == ".mdx"]
        stale, missing = mdx[0], mdx[-1]
        stale_path = docs_root / stale
        stale_path.write_text(_GENERATED_MARKER + "\nstale\n", encoding="utf-8")
        (docs_root / missing).unlink()
        obsolete = Path(mdx[0].parts[0]) / "obsolete" / "nested.mdx"
        obsolete_path = docs_root / obsolete
        obsolete_path.parent.mkdir(parents=True)
        obsolete_path.write_text(_GENERATED_MARKER + "\n", encoding="utf-8")
        notes = docs_root / Path(mdx[0].parts[0]) / "notes.mdx"
        notes.write_text("Hand-written.\n", encoding="utf-8")

        diagnostics = generator.check_reference(docs_root)
        assert any(message == f"stale: {stale}" for message in diagnostics)
        assert any(message == f"missing: {missing}" for message in diagnostics)
        assert any(message == f"unexpected generated file: {obsolete}" for message in diagnostics)
        assert stale_path.read_text(encoding="utf-8") == _GENERATED_MARKER + "\nstale\n"
        assert notes.read_text(encoding="utf-8") == "Hand-written.\n"

        assert generator.write_reference(docs_root) == (obsolete,)
        assert generator.check_reference(docs_root) == ()
        assert notes.read_text(encoding="utf-8") == "Hand-written.\n"

    def test_write_preserves_unmarked_owned_file(self, tmp_path: Path) -> None:
        docs_root = tmp_path / "docs"
        path = next(path for path in generator.render_reference() if path.suffix == ".mdx")
        output = docs_root / path
        output.parent.mkdir(parents=True)
        output.write_text("Hand-written.\n", encoding="utf-8")

        with pytest.raises(FileExistsError, match="Refusing to overwrite unmarked file"):
            generator.write_reference(docs_root)
        assert output.read_text(encoding="utf-8") == "Hand-written.\n"

    def test_collection_is_hermetic(self, tmp_path: Path) -> None:
        home = tmp_path / "home"
        home.mkdir()
        script = """
import socket

def blocked_connect(*args, **kwargs):
    raise AssertionError("network access is forbidden")

socket.socket.connect = blocked_connect
from scripts.reference_docs import render_reference
rendered = render_reference()
assert rendered
assert all(rendered.values())
"""
        environment = {"HOME": str(home), "PATH": os.environ.get("PATH", ""), "PYTHONPATH": str(Path.cwd())}
        result = subprocess.run(
            [sys.executable, "-c", script], cwd=Path.cwd(), env=environment, capture_output=True, text=True
        )
        assert result.returncode == 0, result.stderr

    def test_script_entry_point_checks_committed_reference(self) -> None:
        command = (sys.executable, "scripts/generate_reference.py", "--check")
        result = subprocess.run(command, cwd=Path.cwd(), capture_output=True, text=True)

        assert result.returncode == 0, result.stderr
        assert result.stdout == "Generated documentation reference is current.\n"

    def test_main_reports_current_and_stale_trees(self, tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
        docs_root = tmp_path / "docs"
        generator.write_reference(docs_root)
        assert generator.main(["--check"], docs_root) == 0
        assert "Generated documentation reference is current." in capsys.readouterr().out

        stale = next(path for path in generator.render_reference() if path.suffix == ".mdx")
        output = docs_root / stale
        output.write_text(_GENERATED_MARKER + "\nstale\n", encoding="utf-8")
        before = {path: path.read_bytes() for path in docs_root.rglob("*") if path.is_file()}
        assert generator.main(["--check"], docs_root) == 1
        text = capsys.readouterr().out
        assert "Generated documentation reference is stale:" in text
        assert f"stale: {stale}" in text
        assert {path: path.read_bytes() for path in docs_root.rglob("*") if path.is_file()} == before

        assert generator.main([], docs_root) == 0
        assert capsys.readouterr().out == "Generated documentation reference.\n"
