"""Tests for generated CLI and SDK reference documentation.

Run: pytest tests/unit/docs/test_generate_reference.py

Covers public-surface collection, deterministic rendering, stale checks, and import safety.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

import pytest
import valkyrie.sdk as sdk
from valkyrie.sdk import resources as sdk_resources

from scripts import generate_reference

_EXPECTED_CLI_PATHS = (
    "run analyze",
    "run errors",
    "run fetch",
    "run list",
    "run output",
    "run outputs",
    "run results",
    "run resume",
    "run retry",
    "run start",
    "run status",
    "run stop",
    "run update",
    "agent install",
    "agent push",
    "agent remove",
    "agent download",
    "agent list",
    "benchmark tasks",
    "config auth set",
    "config auth remove",
    "config auth list",
    "config init",
    "config set",
    "config remove",
    "config provider set",
    "config provider default",
    "config provider remove",
    "config provider list",
    "config service set",
    "config service remove",
    "config service list",
)
_EXPECTED_MODELS = {
    "Agents": (
        ("AgentContractRequest", "agent-contract-request"),
        ("AgentDownloadURLResponse", "agent-download-url-response"),
        ("AgentEntry", "agent-entry"),
        ("AgentsResponse", "agents-response"),
    ),
    "Runs": (
        ("AnalyzeEvent", "analyze-event"),
        ("FetchBenchmarkResponse", "fetch-benchmark-response"),
        ("FetchBenchmarkMetadataResponse", "fetch-benchmark-metadata-response"),
        ("FetchBenchmarksRequest", "fetch-benchmarks-request"),
        ("FetchBenchmarksResponse", "fetch-benchmarks-response"),
        ("FinalViewResponse", "final-view-response"),
        ("RetryOrResumeBenchmarkResponse", "retry-or-resume-benchmark-response"),
        ("ResultsExistResponse", "results-exist-response"),
        ("S3UploadResultsResponse", "s3-upload-results-response"),
        ("StartBenchmarkResponse", "start-benchmark-response"),
        ("StopBenchmarkResponse", "stop-benchmark-response"),
    ),
    "Benchmarks": (
        ("BenchmarkStatusEntry", "benchmark-status-entry"),
        ("BenchmarkStatusResponse", "benchmark-status-response"),
        ("FetchTasksRequest", "fetch-tasks-request"),
        ("SingleBenchmarkResponse", "single-benchmark-response"),
        ("SingleTaskResponse", "single-task-response"),
        ("TaskArtifactsResponse", "task-artifacts-response"),
        ("TasksResponse", "tasks-response"),
        ("TaskSummary", "task-summary"),
    ),
    "Services": (
        ("BenchmarkServiceCatalogResponse", "benchmark-service-catalog-response"),
        ("BenchmarkServiceEntry", "benchmark-service-entry"),
        ("BenchmarkServiceHealth", "benchmark-service-health"),
        ("BenchmarkServicesResponse", "benchmark-services-response"),
    ),
    "Config": (("ValkyrieConfig", "valkyrie-config"),),
}
_EXPECTED_ENUMS = (
    ("BenchmarkStatus", "Runs", "benchmark-status"),
    ("Order", "Runs", "order"),
    ("RetryMode", "Runs", "retry-mode"),
    ("TaskStatus", "Runs", "task-status"),
)
_EXPECTED_RESOURCES = {
    "RunsResource": (
        "start",
        "fetch",
        "list",
        "stream",
        "results",
        "metadata",
        "results_exist",
        "analyze",
        "stream_outputs",
        "stop",
        "resume",
        "retry",
    ),
    "BenchmarksResource": ("fetch", "statuses", "tasks", "task", "artifacts"),
    "AgentsResource": ("list", "download_url"),
    "BenchmarkServicesResource": ("catalog", "list", "task_ids"),
}
_GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"
_DOCS_CONFIG_PATH = Path("docs/docs.json")
_DOCS_ROOT = _DOCS_CONFIG_PATH.parent


def _command_by_path(path: str) -> generate_reference.CLICommandReference:
    commands = generate_reference.collect_cli_commands()
    return next(command for command in commands if " ".join(command.path) == path)


def _option_by_name(
    command: generate_reference.CLICommandReference,
    name: str,
) -> generate_reference.CLIParameterReference:
    return next(parameter for parameter in command.parameters if parameter.name == name)


def _markdown_headings(page: str) -> list[str]:
    """Return only real Markdown headings, ignoring shell comments inside fenced code blocks."""
    headings: list[str] = []
    in_fence = False
    for line in page.splitlines():
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence and line.startswith("#") and not line.startswith("#!"):
            headings.append(line)
    return headings


def _command_heading(command: generate_reference.CLICommandReference) -> str:
    anchor = generate_reference._cli_command_anchor(command)
    return f"## `valkyrie {' '.join(command.path)}` {{#{anchor}}}"


def _command_section(rendered: dict[Path, str], command: generate_reference.CLICommandReference) -> str:
    """Return the text of one command's section on its group page."""
    page = rendered[generate_reference._cli_group_page_path(command.path[0])]
    heading = _command_heading(command)
    assert page.count(heading) == 1, heading
    remainder = page.split(heading, 1)[1]
    end = remainder.find("\n## ")
    return remainder if end == -1 else remainder[:end]


def _method_heading(
    resource: generate_reference.SDKResourceReference,
    method: generate_reference.SDKMethodReference,
) -> str:
    anchor = generate_reference._sdk_method_anchor(method)
    return f"## `{resource.client_attribute}.{method.name}` {{#{anchor}}}"


def _method_section(
    rendered: dict[Path, str],
    resource: generate_reference.SDKResourceReference,
    method: generate_reference.SDKMethodReference,
) -> str:
    """Return the text of one method's section on its resource page."""
    heading = _method_heading(resource, method)
    pages = [content for path, content in rendered.items() if path.suffix == ".mdx" and heading in content]
    assert len(pages) == 1
    page = pages[0]
    assert page.count(heading) == 1, heading
    remainder = page.split(heading, 1)[1]
    end = remainder.find("\n## ")
    return remainder if end == -1 else remainder[:end]


def _flatten_navigation(items: list[object]) -> list[str]:
    pages: list[str] = []
    for item in items:
        if isinstance(item, str):
            pages.append(item)
            continue
        assert isinstance(item, dict)
        nested = item.get("pages")
        assert isinstance(nested, list)
        pages.extend(_flatten_navigation(nested))
    return pages


def _path_for_route(route: str) -> Path:
    return Path(route.partition("#")[0].lstrip("/")).with_suffix(".mdx")


def _navigation(rendered: dict[Path, str], scope: str) -> tuple[Path, list[object]]:
    candidates = [path for path in rendered if path.name == "navigation.json" and path.parent.name == scope]
    assert len(candidates) == 1
    path = candidates[0]
    value = json.loads(rendered[path])
    assert isinstance(value, list)
    return path, value


def _export_page(reference: generate_reference.SDKReference, name: str) -> Path:
    target = next(export.target for export in reference.exports if export.name == name)
    return _path_for_route(target)


class TestCLIReferenceCollection:
    """Collection of the complete registered Click command tree."""

    def test_preserves_every_leaf_command_in_registration_order(self) -> None:
        """
        Verify that collection preserves the current registered command contract.

        Test cases:
        - All 32 leaf paths appear.
        - Registration order is unchanged.
        - Retry remains a separate leaf beside resume.
        """
        commands = generate_reference.collect_cli_commands()
        command_paths = tuple(" ".join(command.path) for command in commands)

        assert command_paths == _EXPECTED_CLI_PATHS
        assert command_paths.index("run resume") + 1 == command_paths.index("run retry")

    def test_maps_every_cli_leaf_to_one_section_on_one_group_page(self) -> None:
        """
        Verify that every registered command is documented once on its group page.

        Test cases:
        - The index and group pages match the expected manifest.
        - Each leaf has one section with a unique explicit anchor.
        - Sections keep their syntax block.
        """
        commands = generate_reference.collect_cli_commands()
        rendered = generate_reference.render_reference()
        cli_pages = sorted(path for path in rendered if path.suffix == ".mdx" and path.parent.name == "cli")
        _, navigation = _navigation(rendered, "cli")
        navigation_pages = [_path_for_route(route) for route in _flatten_navigation(navigation)]

        assert cli_pages == sorted(navigation_pages)
        located = [
            (generate_reference._cli_group_page_path(command.path[0]), generate_reference._cli_command_anchor(command))
            for command in commands
        ]
        by_page: dict[Path, list[str]] = {}
        for page, anchor in located:
            by_page.setdefault(page, []).append(anchor)

        assert len(set(located)) == len(located)
        assert all(len(anchors) == len(set(anchors)) for anchors in by_page.values())
        assert set(by_page) == set(navigation_pages[1:])

        for command in commands:
            section = _command_section(rendered, command)
            assert "```bash Syntax" in section

    def test_group_pages_keep_commands_in_click_registration_order(self) -> None:
        """
        Verify that a group page lists its commands in registration order.

        Test cases:
        - Section order matches Click order within every group.
        - Every group page states how many commands it documents.
        """
        commands = generate_reference.collect_cli_commands()
        rendered = generate_reference.render_reference()
        groups = generate_reference._cli_groups(commands)

        for group, group_commands in groups.items():
            page = rendered[generate_reference._cli_group_page_path(group)]
            positions = [page.index(_command_heading(command)) for command in group_commands]

            assert positions == sorted(positions)
            assert f"all {len(group_commands)} commands in the `{group}` group" in page

    def test_renders_complete_cli_syntax_in_source_order(self) -> None:
        """
        Verify complete, ordered CLI syntax and safe examples.

        Test cases:
        - Every argument and option appears exactly once in the syntax, in declaration order.
        - Syntax names concrete metavars.
        - Mutating examples carry the review comment.
        """
        commands = generate_reference.collect_cli_commands()
        rendered = generate_reference.render_reference()

        for command in commands:
            section = _command_section(rendered, command)
            syntax = section.split("```bash Syntax\n", 1)[1].split("\n```", 1)[0]
            cursor = -1
            for parameter in command.parameters:
                positions: list[int] = []
                for declaration in parameter.declarations:
                    token = declaration if parameter.kind == "option" else f"<{declaration}>"
                    matches = list(re.finditer(rf"(?<![A-Za-z0-9-]){re.escape(token)}(?![A-Za-z0-9-])", syntax))
                    assert len(matches) == 1
                    positions.append(matches[0].start())
                assert min(positions) > cursor
                cursor = max(positions)

        start_section = _command_section(rendered, _command_by_path("run start"))
        assert "--agent <TEXT>" in start_section
        assert "[--count|-n <INTEGER>]" in start_section
        assert "[--secret|-s <TEXT> <TEXT>...]" in start_section
        assert "# Example only — review before running" in start_section

        stop_section = _command_section(rendered, _command_by_path("run stop"))
        assert "valkyrie run stop $RUN_ID" in stop_section

        auth_section = _command_section(rendered, _command_by_path("config auth set"))
        assert "$BENCHMARK_CREDENTIAL" in auth_section

    def test_formats_multi_group_cli_examples_with_shell_continuations(self) -> None:
        """Verify every concrete multi-group example is readable and shell-valid."""
        rendered = generate_reference.render_reference()
        for command in generate_reference.collect_cli_commands():
            if command.example is None:
                continue
            section = _command_section(rendered, command)
            example = section.split("```bash Example\n", 1)[1].split("\n```", 1)[0]
            command_lines = [line for line in example.splitlines() if line and not line.startswith("#")]
            if len(command_lines) > 1:
                assert all(line.endswith("\\") for line in command_lines[:-1])
                assert all(line.startswith("  ") for line in command_lines[1:])
            subprocess.run(["bash", "-n"], input=example, text=True, check=True)

    def test_captures_representative_click_parameter_metadata(self) -> None:
        """
        Verify that Click declarations become stable structural metadata.

        Test cases:
        - Required aliases, integer ranges, repeatable tuples, choices, paths, and UUIDs retain their shape.
        - Unset defaults remain distinct from explicit None and false defaults.
        """
        start = _command_by_path("run start")
        agent = _option_by_name(start, "agent")
        concurrency = _option_by_name(start, "concurrency")
        secrets = _option_by_name(start, "secrets")
        count = _option_by_name(start, "count")
        status = _command_by_path("run status")
        errors = _command_by_path("run errors")
        output = _command_by_path("run output")

        assert agent.required is True
        assert agent.default is None
        assert concurrency.default == "5"
        assert concurrency.constraints == (">= 1",)
        assert secrets.declarations == ("--secret", "-s")
        assert secrets.multiple is True
        assert secrets.nargs == 2
        assert secrets.type_name == "tuple[text, text]"
        assert count.constraints == (">= 1", "<= 10")
        assert _option_by_name(status, "run_ids_value").required is True
        assert _option_by_name(errors, "output_format").constraints == (
            "one of `text`, `json`",
            "case-insensitive",
        )
        assert output.parameters[0].type_name == "UUID"
        assert _option_by_name(output, "output_dir").type_name == "path"
        assert _option_by_name(output, "output_dir").constraints == ("readable",)


class TestSDKReferenceCollection:
    """Collection of the tested public SDK contract."""

    def test_matches_public_exports_resources_and_overloads(self) -> None:
        """
        Verify that the reference follows the tested public SDK boundary.

        Test cases:
        - Top-level exports retain __all__ order.
        - Every approved resource method appears.
        - Results retains all three overload signatures.
        """
        reference = generate_reference.collect_sdk_reference()

        assert tuple(export.name for export in reference.exports) == tuple(sdk.__all__)
        assert len(reference.exports) == 39
        assert {
            resource.name: tuple(method.name for method in resource.methods) for resource in reference.resources
        } == (_EXPECTED_RESOURCES)

        runs = next(resource for resource in reference.resources if resource.name == "RunsResource")
        results = next(method for method in runs.methods if method.name == "results")

        assert len(results.signatures) == 3
        assert "Literal[False]" in results.signatures[0]
        assert "Literal[True]" in results.signatures[1]
        assert "RetrieveResultsResponse" in results.signatures[2]

        rendered = generate_reference.render_reference()
        for export in reference.exports:
            page = _path_for_route(export.target)
            assert page in rendered, export
            assert export.name in rendered[page], export

    def test_collects_and_renders_source_docstrings(self, monkeypatch) -> None:
        """Verify each SDK source category reads its current docstring at collection time."""
        sources = (
            sdk_resources.RunsResource,
            sdk_resources.RunsResource.start,
            sdk.FetchBenchmarksRequest,
            sdk.BenchmarkStatus,
            sdk.ValkyrieAPIError,
            sdk.ValkyrieClient,
            sdk.ValkyrieClient.from_config.__func__,
            sdk.ValkyrieClient.close,
        )
        sentinels = {source: f"DOCSTRING_SENTINEL_{index}" for index, source in enumerate(sources)}
        for source, sentinel in sentinels.items():
            monkeypatch.setattr(source, "__doc__", sentinel)

        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()
        descriptions = [resource.description for resource in reference.resources]
        descriptions.extend(method.description for resource in reference.resources for method in resource.methods)
        descriptions.extend(model.description for model in reference.models)
        descriptions.extend(enum.description for enum in reference.enums)
        descriptions.extend(exception.description for exception in reference.exceptions)
        descriptions.extend(method.description for method in reference.client_methods)
        combined = "\n".join(rendered.values())

        for sentinel in sentinels.values():
            assert sentinel in descriptions
            assert sentinel in combined

    def test_maps_each_public_resource_method_to_one_section_on_one_resource_page(self) -> None:
        """Verify that all 22 methods map to four complete anchored resource pages."""
        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()

        for resource in reference.resources:
            first_heading = _method_heading(resource, resource.methods[0])
            pages = [
                content for path, content in rendered.items() if path.suffix == ".mdx" and first_heading in content
            ]
            assert len(pages) == 1
            page = pages[0]
            headings = _markdown_headings(page)

            assert headings == [_method_heading(resource, method) for method in resource.methods]

            for method in resource.methods:
                section = _method_section(rendered, resource, method)
                assert all(f"\n{signature}\n" in section for signature in method.signatures)
                assert section.count("```python") == len(method.signatures)
                assert "**Returns**" in section

    def test_collects_and_renders_exact_public_types(self) -> None:
        """Verify every public model and enum has one stable family-page heading."""
        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()
        models_by_family: dict[str, list[tuple[str, str]]] = {}
        for model in reference.models:
            models_by_family.setdefault(model.family, []).append((model.name, model.slug))

        assert {family: tuple(entries) for family, entries in models_by_family.items()} == _EXPECTED_MODELS
        assert tuple((enum.name, enum.family, enum.slug) for enum in reference.enums) == _EXPECTED_ENUMS

        type_locations = {
            name: (family, slug) for family, entries in _EXPECTED_MODELS.items() for name, slug in entries
        }
        type_locations.update({name: (family, slug) for name, family, slug in _EXPECTED_ENUMS})
        for family in _EXPECTED_MODELS:
            expected = [
                f"## `{name}` {{#{type_locations[name][1]}}}"
                for name in sdk.__all__
                if name in type_locations and type_locations[name][0] == family
            ]
            page = rendered[_export_page(reference, _EXPECTED_MODELS[family][0][0])]
            assert _markdown_headings(page) == expected

    def test_links_public_types_across_pages(self) -> None:
        """Verify public nested tokens link to family-page anchors."""
        rendered = generate_reference.render_reference()
        reference = generate_reference.collect_sdk_reference()
        targets = {export.name: export.target for export in reference.exports}
        request_page = rendered[_path_for_route(targets["FetchBenchmarksRequest"])]
        agents_page = rendered[_path_for_route(targets["AgentEntry"])]
        runs = reference.resources[0]
        start = next(method for method in runs.methods if method.name == "start")
        start_page = _method_section(rendered, runs, start)

        assert f'href="{targets["BenchmarkStatus"]}"' in request_page
        assert f'href="{targets["Order"]}"' in request_page
        assert f'href="{targets["AgentEntry"]}"' in agents_page
        assert f'href="{targets["AgentContractRequest"]}"' in start_page
        assert f'href="{targets["StartBenchmarkResponse"]}"' in start_page
        assert "BenchmarkDetails" in request_page

    def test_documents_every_public_exception_with_its_hierarchy(self) -> None:
        """
        Verify the generated errors page covers the public exception surface.

        Test cases:
        - Every exception exported from `valkyrie.sdk` has a table row and a section.
        - Rows name the real parent class and link to the matching section anchor.
        - Each section pins the constructor signature.
        - The SDK index links to the complete error hierarchy.
        """
        reference = generate_reference.collect_sdk_reference()
        rendered = generate_reference.render_reference()
        _, sdk_navigation = _navigation(rendered, "sdk")
        index = rendered[_path_for_route(_flatten_navigation(sdk_navigation)[0])]
        exported = sorted(
            name
            for name in sdk.__all__
            if isinstance(getattr(sdk, name), type) and issubclass(getattr(sdk, name), Exception)
        )

        assert exported == [
            "ValkyrieAPIError",
            "ValkyrieConfigError",
            "ValkyrieRunError",
            "ValkyrieSDKError",
            "ValkyrieStreamError",
            "ValkyrieTransportError",
        ]
        assert [error.name for error in reference.exceptions] == exported
        error_target = next(export.target for export in reference.exports if export.name == exported[0])
        page = rendered[_path_for_route(error_target)]

        for error in reference.exceptions:
            expected_parent = getattr(sdk, error.name).__bases__[0].__name__

            assert error.parent == expected_parent
            assert f"| [`{error.name}`](#{error.name.lower()}) | `{expected_parent}` |" in page
            assert f"## `{error.name}`" in page
            assert f"\n{error.signature}\n" in page

        assert index.count(f"[SDK error hierarchy]({error_target.partition('#')[0]})") == 1
        assert "ValkyrieAPIError(status_code: int, detail: Any)" in page
        assert "ValkyrieSDKError(*args: object)" in page
        assert page.count("## `Valkyrie") == len(exported)

    def test_captures_public_model_defaults_aliases_constraints_and_enums(self) -> None:
        """
        Verify that public model metadata remains useful without instantiation.

        Test cases:
        - Default factories render as stable values.
        - Aliases and numeric constraints remain visible.
        - Enum declaration order and values remain intact.
        """
        reference = generate_reference.collect_sdk_reference()
        models = {model.name: model for model in reference.models}
        enums = {enum.name: enum for enum in reference.enums}
        contract_fields = {field.name: field for field in models["AgentContractRequest"].fields}
        task_fields = {field.name: field for field in models["FetchTasksRequest"].fields}
        run_fields = {field.name: field for field in models["FetchBenchmarksRequest"].fields}
        config_fields = {field.name: field for field in models["ValkyrieConfig"].fields}

        assert contract_fields["output_artifacts"].default == "[]"
        assert task_fields["limit"].default == "50"
        assert task_fields["limit"].constraints == (">= 1", "<= 500")
        assert run_fields["order_by"].default == "Order.DESC"
        assert config_fields["aws_access_key_id"].alias == "AWS_ACCESS_KEY_ID"
        assert enums["TaskStatus"].members == (
            ("PENDING", "'PENDING'"),
            ("BUILDING", "'BUILDING'"),
            ("IN_PROGRESS", "'IN_PROGRESS'"),
            ("EVALUATING", "'EVALUATING'"),
            ("STOPPED", "'STOPPED'"),
            ("FINISHED", "'FINISHED'"),
            ("ERROR", "'ERROR'"),
        )


class TestGeneratedReferenceFiles:
    """Rendering, navigation, and stale-output behavior for the generated manifest."""

    def test_render_is_deterministic_and_structured(self) -> None:
        """Verify that rendering is stable and every generated file has the expected structure."""
        first = generate_reference.render_reference()
        second = generate_reference.render_reference()

        mdx_files = {path: content for path, content in first.items() if path.suffix == ".mdx"}
        json_files = {path: content for path, content in first.items() if path.suffix == ".json"}
        cli_navigation_path, _ = _navigation(first, "cli")
        sdk_navigation_path, _ = _navigation(first, "sdk")
        redirect_paths = [path for path in first if path.name == "redirects.json"]

        assert first == second
        assert mdx_files
        assert len(redirect_paths) == 1
        assert set(json_files) == {cli_navigation_path, sdk_navigation_path, redirect_paths[0]}
        assert set(first) == set(mdx_files) | set(json_files)
        assert all(content.startswith("---\n") for content in mdx_files.values())
        assert all(_GENERATED_MARKER in content for content in mdx_files.values())
        assert all(isinstance(json.loads(content), list) for content in json_files.values())

    def test_cli_bash_blocks_are_bounded_and_shell_valid(self) -> None:
        """
        Verify every generated shell block stays narrow and parses as shell.

        Test cases:
        - Shell blocks fit a narrow column.
        - Examples parse under `bash -n`; syntax templates are not executable by design.
        """
        rendered = generate_reference.render_reference()
        titled_bash_blocks = [
            match.groups()
            for content in rendered.values()
            for match in re.finditer(r"```bash ([^\n]+)\n(.*?)\n```", content, flags=re.DOTALL)
        ]

        assert titled_bash_blocks
        assert max(len(line) for _, block in titled_bash_blocks for line in block.splitlines()) <= 120

        for title, block in titled_bash_blocks:
            if title != "Syntax":
                subprocess.run(["bash", "-n"], input=block, text=True, check=True)

    def test_navigation_contains_each_generated_page_once_and_docs_json_uses_refs(self) -> None:
        """
        Verify that generated nested navigation is complete and uniquely referenced.

        Test cases:
        - CLI navigation contains the index and exactly one route per command group.
        - SDK navigation contains the index, client, four resource pages, models, and errors once.
        - docs.json resolves each reference group through its generated navigation file.
        """
        rendered = generate_reference.render_reference()
        cli_navigation_path, cli_navigation = _navigation(rendered, "cli")
        sdk_navigation_path, sdk_navigation = _navigation(rendered, "sdk")
        cli_pages = _flatten_navigation(cli_navigation)
        sdk_pages = _flatten_navigation(sdk_navigation)
        cli_root = cli_navigation_path.parent
        sdk_root = sdk_navigation_path.parent

        assert cli_pages == [
            path.with_suffix("").as_posix() for path in rendered if path.suffix == ".mdx" and cli_root in path.parents
        ]
        assert sdk_pages == [
            path.with_suffix("").as_posix() for path in rendered if path.suffix == ".mdx" and sdk_root in path.parents
        ]
        assert {Path(page).with_suffix(".mdx") for page in (*cli_pages, *sdk_pages)} == {
            path for path in rendered if path.suffix == ".mdx"
        }

        docs_config = json.loads(_DOCS_CONFIG_PATH.read_text(encoding="utf-8"))
        groups = {group["group"]: group["pages"] for group in docs_config["navigation"]["groups"]}

        assert groups["CLI reference"] == {"$ref": cli_navigation_path.as_posix()}
        assert groups["Python SDK reference"] == {"$ref": sdk_navigation_path.as_posix()}

    def test_retired_reference_routes_redirect_to_group_page_anchors(self) -> None:
        """Verify all retired CLI command and SDK method URLs keep resolving."""
        rendered = generate_reference.render_reference()
        redirect_paths = [path for path in rendered if path.name == "redirects.json"]
        assert len(redirect_paths) == 1
        redirects_path = redirect_paths[0]
        redirect_entries = json.loads(rendered[redirects_path])
        commands = generate_reference.collect_cli_commands()
        reference = generate_reference.collect_sdk_reference()

        assert isinstance(redirect_entries, list)
        assert len(redirect_entries) == len({entry["source"] for entry in redirect_entries})
        assert all(set(entry) == {"source", "destination"} for entry in redirect_entries)

        expected = [
            *generate_reference.cli_redirects(commands),
            *generate_reference.sdk_redirects(reference),
            *generate_reference.sdk_type_redirects(reference),
        ]
        assert redirect_entries == expected

        by_source = {entry["source"]: entry["destination"] for entry in redirect_entries}
        cli_navigation_path, _ = _navigation(rendered, "cli")
        sdk_navigation_path, _ = _navigation(rendered, "sdk")
        start_command = _command_by_path("run start")
        cli_source = "/" + cli_navigation_path.parent.joinpath(*start_command.path).as_posix()
        cli_destination = f"/{(cli_navigation_path.parent / start_command.path[0]).as_posix()}#start"
        assert by_source[cli_source] == cli_destination

        runs = next(resource for resource in reference.resources if resource.name == "RunsResource")
        stream_outputs = next(method for method in runs.methods if method.name == "stream_outputs")
        resource_page = runs.client_attribute.rsplit(".", 1)[1]
        sdk_source = "/" + (sdk_navigation_path.parent / resource_page / stream_outputs.name).as_posix()
        sdk_destination = (
            f"/{(sdk_navigation_path.parent / resource_page).as_posix()}#{stream_outputs.name.replace('_', '-')}"
        )
        assert by_source[sdk_source] == sdk_destination

        model = next(model for model in reference.models if model.name == "FetchBenchmarksRequest")
        model_page = _export_page(reference, model.name)
        type_source = "/" + (model_page.parent / model.family.lower() / model.slug).as_posix()
        type_destination = f"/{model_page.with_suffix('').as_posix()}#{model.slug}"
        assert by_source[type_source] == type_destination

        for entry in redirect_entries:
            _, anchor = entry["destination"].split("#", 1)
            destination_page = _path_for_route(entry["destination"])
            assert destination_page in rendered
            assert f"{{#{anchor}}}" in rendered[destination_page]

        docs_config = json.loads(_DOCS_CONFIG_PATH.read_text(encoding="utf-8"))
        assert docs_config["redirects"] == {"$ref": redirects_path.as_posix()}

    def test_handwritten_guides_link_to_group_page_anchors(self) -> None:
        """Verify handwritten CLI and SDK links resolve to real pages and anchors."""
        rendered = generate_reference.render_reference()
        anchors_by_page = {
            path: {
                line.split("{#", 1)[1].split("}", 1)[0]
                for line in content.splitlines()
                if line.startswith("## ") and "{#" in line
            }
            for path, content in rendered.items()
            if path.suffix == ".mdx"
        }
        reference_root = Path(next(iter(rendered)).parts[0])
        guides = [path for path in sorted(_DOCS_ROOT.rglob("*.mdx")) if path.parts[1] != reference_root.name]
        _, cli_navigation = _navigation(rendered, "cli")
        _, sdk_navigation = _navigation(rendered, "sdk")
        types_group = next(item for item in sdk_navigation if isinstance(item, dict) and item.get("group") == "Types")
        types_pages = types_group.get("pages")
        assert isinstance(types_pages, list)
        index_pages = (
            _flatten_navigation(cli_navigation)[0],
            _flatten_navigation(sdk_navigation)[0],
            _flatten_navigation(types_pages)[0],
        )
        index_routes = {f"/{page.removesuffix('/index')}" for page in index_pages}
        link_pattern = rf"\(/{re.escape(reference_root.as_posix())}/[^)]*\)"

        assert guides

        for guide in guides:
            text = guide.read_text(encoding="utf-8")
            for link in re.findall(link_pattern, text):
                target = link[1:-1]
                route, _, anchor = target.partition("#")
                if route in index_routes:
                    page = Path(route.lstrip("/"), "index.mdx")
                else:
                    page = Path(route.lstrip("/")).with_suffix(".mdx")

                assert page in rendered, (guide, target)
                if anchor:
                    assert anchor in anchors_by_page[page], (guide, target)

    def test_check_detects_stale_missing_and_unexpected_files_without_writing(self, tmp_path: Path) -> None:
        """
        Verify that check mode reports every generated-manifest drift condition.

        Test cases:
        - Current output passes.
        - Stale and missing files fail without rewriting.
        - Extra marked files fail and are safely removed on regeneration.
        - Unrelated unmarked files remain untouched.
        """
        docs_root = tmp_path / "docs"
        manifest = generate_reference.render_reference()
        generate_reference.write_reference(docs_root)

        assert generate_reference.check_reference(docs_root) == ()

        generated_mdx = [path for path in manifest if path.suffix == ".mdx"]
        reference_root = Path(generated_mdx[0].parts[0])
        stale_relative = generated_mdx[0]
        missing_relative = generated_mdx[-1]
        unexpected_relative = reference_root / "obsolete" / "nested.mdx"
        stale_path = docs_root / stale_relative
        stale_path.write_text(_GENERATED_MARKER + "\nstale\n", encoding="utf-8")
        missing_path = docs_root / missing_relative
        missing_path.unlink()
        unexpected_path = docs_root / unexpected_relative
        unexpected_path.parent.mkdir(parents=True, exist_ok=True)
        unexpected_path.write_text(_GENERATED_MARKER + "\n", encoding="utf-8")
        unrelated_path = docs_root / reference_root / "notes.mdx"
        unrelated_path.write_text("Hand-written.\n", encoding="utf-8")
        cli_navigation_path, _ = _navigation(manifest, "cli")
        retired_redirects_path = docs_root / cli_navigation_path.parent / "redirects.json"
        retired_redirects_path.write_text("[]\n", encoding="utf-8")

        diagnostics = generate_reference.check_reference(docs_root)

        assert any(message == f"stale: {stale_relative.as_posix()}" for message in diagnostics)
        assert any(message == f"missing: {missing_relative.as_posix()}" for message in diagnostics)
        assert any(message == f"unexpected generated file: {unexpected_relative.as_posix()}" for message in diagnostics)
        assert stale_path.read_text(encoding="utf-8") == _GENERATED_MARKER + "\nstale\n"
        assert unrelated_path.read_text(encoding="utf-8") == "Hand-written.\n"
        assert retired_redirects_path.read_text(encoding="utf-8") == "[]\n"

        removed = generate_reference.write_reference(docs_root)

        assert removed == (unexpected_relative,)
        assert _GENERATED_MARKER in stale_path.read_text(encoding="utf-8")
        assert missing_path.exists()
        assert unrelated_path.read_text(encoding="utf-8") == "Hand-written.\n"
        assert retired_redirects_path.read_text(encoding="utf-8") == "[]\n"

    def test_write_refuses_to_overwrite_an_unmarked_manifest_path(self, tmp_path: Path) -> None:
        """
        Verify that generation never replaces hand-written content at an owned path.

        Test cases:
        - An unmarked file at an expected path causes a clear failure.
        - The unmarked content remains unchanged.
        """
        docs_root = tmp_path / "docs"
        conflict_relative = next(path for path in generate_reference.render_reference() if path.suffix == ".mdx")
        conflict_path = docs_root / conflict_relative
        conflict_path.parent.mkdir(parents=True)
        conflict_path.write_text("Hand-written.\n", encoding="utf-8")

        with pytest.raises(FileExistsError, match="Refusing to overwrite unmarked file"):
            generate_reference.write_reference(docs_root)

        assert conflict_path.read_text(encoding="utf-8") == "Hand-written.\n"

    def test_collection_is_safe_with_empty_home_and_blocked_network(self, tmp_path: Path) -> None:
        """
        Verify that reference collection does not read user configuration or connect to services.

        Test cases:
        - HOME points to an empty directory.
        - Socket connections raise immediately.
        - Rendering still returns the complete dynamic manifest.
        """
        empty_home = tmp_path / "home"
        empty_home.mkdir()
        script = """
import socket


def blocked_connect(*args, **kwargs):
    raise AssertionError("network access is forbidden")


socket.socket.connect = blocked_connect
from scripts.generate_reference import render_reference
rendered = render_reference()
assert rendered
assert all(rendered.values())
"""
        environment = {
            "HOME": str(empty_home),
            "PATH": os.environ.get("PATH", ""),
            "PYTHONPATH": str(Path.cwd()),
        }

        result = subprocess.run(
            [sys.executable, "-c", script],
            cwd=Path.cwd(),
            env=environment,
            capture_output=True,
            text=True,
            check=False,
        )

        assert result.returncode == 0, result.stderr

    def test_renders_literal_braces_as_escaped_text(self) -> None:
        """Verify that braces survive MDX rendering as visible text."""
        rendered = generate_reference.render_reference()
        reference = generate_reference.collect_sdk_reference()
        config_page = rendered[_export_page(reference, "ValkyrieConfig")]

        assert 'default: <code>{"{}"}</code>' in config_page

    def test_check_entry_point_exits_nonzero_on_drift_without_writing(
        self, tmp_path: Path, monkeypatch, capsys
    ) -> None:
        """
        Verify the command-line check mode reports drift and never writes.

        Test cases:
        - A current tree exits 0 with a success message.
        - A stale tree exits 1, names the file, and leaves every file untouched.
        """
        docs_root = tmp_path / "docs"
        generate_reference.write_reference(docs_root)
        monkeypatch.setattr(generate_reference, "_DOCS_ROOT", docs_root)

        assert generate_reference.main(["--check"]) == 0
        assert "Generated documentation reference is current." in capsys.readouterr().out

        stale_relative = next(path for path in generate_reference.render_reference() if path.suffix == ".mdx")
        stale_path = docs_root / stale_relative
        stale_path.write_text(_GENERATED_MARKER + "\nstale\n", encoding="utf-8")
        before = {path: path.read_bytes() for path in sorted(docs_root.rglob("*")) if path.is_file()}

        assert generate_reference.main(["--check"]) == 1

        output = capsys.readouterr().out
        assert "Generated documentation reference is stale:" in output
        assert f"stale: {stale_relative.as_posix()}" in output
        assert "Run `make docs-reference`" in output
        assert {path: path.read_bytes() for path in sorted(docs_root.rglob("*")) if path.is_file()} == before

        assert generate_reference.main([]) == 0
        assert capsys.readouterr().out == "Generated documentation reference.\n"


class TestSDKTypesReference:
    """Focused coverage for the grouped SDK Types pages, navigation, and redirects."""

    def test_family_pages_preserve_complete_metadata(self) -> None:
        """Verify field, member, default, alias, constraint, and type-link metadata survives."""
        rendered = generate_reference.render_reference()
        reference = generate_reference.collect_sdk_reference()
        runs = rendered[_export_page(reference, "FetchBenchmarksRequest")]
        benchmarks = rendered[_export_page(reference, "FetchTasksRequest")]
        config = rendered[_export_page(reference, "ValkyrieConfig")]

        assert "Runs model · 13 fields" in runs
        assert 'default: <code>{"Order.DESC"}</code>' in runs
        assert 'default: <code>{"50"}</code>' in benchmarks
        assert 'constraints: {">= 1; <= 500"}' in benchmarks
        assert 'alias: <code>{"AWS_ACCESS_KEY_ID"}</code>' in config
