FROM python:3.12-slim

RUN apt-get update && apt-get install -y git

# https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONPATH=/app

# Copy over project dependencies from `src/` 
# NOTE: Ideally this is just what we need to start the daytona environment (Not everything)
COPY src/ ./src/

COPY submodules/${SUBMODULE_NAME} ./submodules/${SUBMODULE_NAME}

COPY contracts/${CONTRACT_NAME}.py ./contracts/${CONTRACT_NAME}.py

# Copy over project pyproject.toml file and install dependencies
COPY pyproject.toml ./pyproject.toml
COPY uv.lock ./uv.lock
COPY README.md ./README.md

# Create a user called agent-user
RUN groupadd -g 1000 agent-user \
 && useradd -m -u 1000 -g agent-user -s /bin/bash agent-user

# Set the permissions of the app directory to the agent-user
RUN chown -R agent-user:agent-user /app

RUN uv sync --frozen --group dev

# This is where the agent will exist and run all of its code / create files, etc...
RUN mkdir -p /app/workspace && chown -R agent-user:agent-user /app/workspace

# Final destination for the agent (blank workspace directory we can clone a repository into, run code, etc...)
WORKDIR /app/workspace

# Disable logging to file
ENV DISABLE_FILE_LOGGING=1

CMD ["sleep", "infinity"]
