"""valkyrie phase a: user, org_config, benchmark.run_by_id

Revision ID: 2c902b6c56ba
Revises: a9d2e1c8b3f4
Create Date: 2026-05-20 21:59:32.147703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2c902b6c56ba'
down_revision: Union[str, Sequence[str], None] = 'a9d2e1c8b3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_config',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('aws_access_key_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_secret_access_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aws_default_region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('s3_bucket', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daytona_secret_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('log_retention_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('webhook', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('org_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descope_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_descope_user_id'), 'user', ['descope_user_id'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.create_index(op.f('ix_user_org_id'), 'user', ['org_id'], unique=False)
    op.add_column('benchmark', sa.Column('run_by_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_benchmark_run_by_id'), 'benchmark', ['run_by_id'], unique=False)
    op.create_foreign_key('benchmark_run_by_id_fkey', 'benchmark', 'user', ['run_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('benchmark_run_by_id_fkey', 'benchmark', type_='foreignkey')
    op.drop_index(op.f('ix_benchmark_run_by_id'), table_name='benchmark')
    op.drop_column('benchmark', 'run_by_id')
    op.drop_index(op.f('ix_user_org_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_descope_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('org_config')
    # ### end Alembic commands ###
