"""Remove agent output

Revision ID: 49036a6b501c
Revises: abe0693a7c7e
Create Date: 2026-02-09 16:36:40.991813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '49036a6b501c'
down_revision: Union[str, Sequence[str], None] = 'abe0693a7c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluationresult', 'agent_output')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluationresult', sa.Column('agent_output', sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
