"""Added an agent_timed_out field to track agent timeouts due to benchmark service restrictions

Revision ID: a338d54845d9
Revises: c1f2af2104e1
Create Date: 2026-03-27 18:52:21.565028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a338d54845d9'
down_revision: Union[str, Sequence[str], None] = 'c1f2af2104e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('agent_timed_out', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'agent_timed_out')
    # ### end Alembic commands ###
