"""Add task breakdown

Revision ID: a92e64afa650
Revises: 35f2d4a8c9b1
Create Date: 2026-05-05 15:01:53.271409

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a92e64afa650"
down_revision: Union[str, Sequence[str], None] = "35f2d4a8c9b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskbreakdown",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sandbox_build_duration", sa.Float(), nullable=True),
        sa.Column("agent_run_duration", sa.Float(), nullable=True),
        sa.Column("evaluation_run_duration", sa.Float(), nullable=True),
        sa.Column("sandbox_run_duration", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("task", sa.Column("task_breakdown", sa.Uuid(), nullable=True))
    op.create_foreign_key("fk_task_task_breakdown", "task", "taskbreakdown", ["task_breakdown"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_task_task_breakdown", "task", type_="foreignkey")
    op.drop_column("task", "task_breakdown")
    op.drop_table("taskbreakdown")
    # ### end Alembic commands ###
