"""Changed task status

Revision ID: abe0693a7c7e
Revises: 26b342c24bd4
Create Date: 2026-02-02 20:42:21.882544

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abe0693a7c7e"
down_revision: Union[str, Sequence[str], None] = "26b342c24bd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    connection = op.get_bind()

    # Step 1: Update existing data
    connection.execute(
        sa.text("""
        UPDATE task
        SET status = 'pending'
        WHERE status = 'starting'
        """)
    )

    # Step 2: Alter the column type
    with op.batch_alter_table("task") as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            type_=sa.Enum("pending", "in_progress", "evaluating", "stopped", "finished", "error", name="taskstatus"),
            existing_nullable=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
