"""Changed task status

Revision ID: abe0693a7c7e
Revises: 26b342c24bd4
Create Date: 2026-02-02 20:42:21.882544

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abe0693a7c7e"
down_revision: Union[str, Sequence[str], None] = "26b342c24bd4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The status column may already be an enum type from a previous migration.
    # Skip the UPDATE and ALTER if the enum already exists with the correct values.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
