"""drop webhook_secret_name and webhook_intervals from benchmark

Revision ID: b3c4d5e6f7a8
Revises: 2d3e4f5a6b7c
Create Date: 2026-09-30 21:45:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b3c4d5e6f7a8"
down_revision: Union[str, Sequence[str], None] = "2d3e4f5a6b7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("benchmark", "webhook_intervals")
    op.drop_column("benchmark", "webhook_secret_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("benchmark", sa.Column("webhook_secret_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("benchmark", sa.Column("webhook_intervals", sa.JSON(), nullable=True))
    # ### end Alembic commands ###
