"""Initial migration

Revision ID: b7edc066bc8c
Revises:
Create Date: 2026-02-09 15:11:23.633129

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from tracker.database.models import BenchmarkArgumentsType


# revision identifiers, used by Alembic.
revision: str = "b7edc066bc8c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("IN_PROGRESS", "STOPPING", "STOPPED", "FINISHED", "ERROR", name="benchmarkstatus"),
            nullable=False,
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("arguments", BenchmarkArgumentsType(), nullable=True),
        sa.CheckConstraint(
            "(status != 'FINISHED' AND status != 'ERROR') OR (finished_at IS NOT NULL)",
            name="benchmark_finished_requires_timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finalevaluation",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("benchmark", sa.Uuid(), nullable=False),
        sa.Column("final_score", sa.Float(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["benchmark"],
            ["benchmark.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "IN_PROGRESS", "EVALUATING", "STOPPED", "FINISHED", "ERROR", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("benchmark", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(status != 'FINISHED' AND status != 'ERROR') OR (finished_at IS NOT NULL)",
            name="task_finished_requires_timestamp",
        ),
        sa.ForeignKeyConstraint(
            ["benchmark"],
            ["benchmark.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("benchmark", "task_id", name="unique_task_per_benchmark"),
    )
    op.create_table(
        "evaluationresult",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("task", sa.Uuid(), nullable=False),
        sa.Column("instance_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("instance_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evaluationresult")
    op.drop_table("task")
    op.drop_table("finalevaluation")
    op.drop_table("benchmark")
    # ### end Alembic commands ###
