"""add webhook_secret_name and webhook_intervals to benchmark

Revision ID: c1f2af2104e1
Revises: f8c7b6a5d4e3
Create Date: 2026-03-24 00:57:58.578229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "c1f2af2104e1"
down_revision: Union[str, Sequence[str], None] = "f8c7b6a5d4e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("benchmark", sa.Column("webhook_secret_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column("benchmark", sa.Column("webhook_intervals", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("benchmark", "webhook_intervals")
    op.drop_column("benchmark", "webhook_secret_name")
    # ### end Alembic commands ###
