"""Change field for agent time out

Revision ID: fc0b597e5045
Revises: a338d54845d9
Create Date: 2026-03-27 20:05:08.922227

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc0b597e5045"
down_revision: Union[str, Sequence[str], None] = "c1f2af2104e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("evaluationresult", sa.Column("agent_timed_out", sa.Boolean(), nullable=True))
    op.execute("UPDATE evaluationresult SET agent_timed_out = false WHERE agent_timed_out IS NULL")
    op.alter_column("evaluationresult", "agent_timed_out", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluationresult", "agent_timed_out")
    # ### end Alembic commands ###
