agent_config:
  model: grok/grok-4-1-fast-non-reasoning
  max_tokens: 16384
  temperature: 1
  extra:
    max_turns: 20

benchmark: ioi
agent: ioi_agent
dataset:
  name: ioi
  suite_id: ed7f59e3-9eeb-44e2-a1c4-87ca507ea1d2
  project_id: ioi-s964z8
