"""Generate deterministic Mintlify reference pages from the public CLI and SDK APIs."""

from __future__ import annotations

import argparse
import difflib
import html
import inspect
import json
import re
import types
import typing
from collections import OrderedDict
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, ForwardRef, Literal, get_args, get_origin

import click
from pydantic import BaseModel

_ROOT = Path(__file__).resolve().parents[1]
_DOCS_ROOT = _ROOT / "docs"
_GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"
_FORMAT_VERSION = 1
_MAX_DIFF_LINES = 80
_CLI_INDEX_PATH = Path("reference/cli/index.mdx")
_CLI_NAVIGATION_PATH = Path("reference/cli/navigation.json")
_REDIRECTS_PATH = Path("reference/redirects.json")
_RETIRED_GENERATED_PATHS = (Path("reference/cli/redirects.json"),)
_SDK_INDEX_PATH = Path("reference/sdk/index.mdx")
_SDK_CLIENT_PATH = Path("reference/sdk/client.mdx")
_SDK_TYPES_INDEX_PATH = Path("reference/sdk/models/index.mdx")
_SDK_ERRORS_PATH = Path("reference/sdk/errors.mdx")
_SDK_NAVIGATION_PATH = Path("reference/sdk/navigation.json")
_RESOURCE_PAGES: OrderedDict[str, str] = OrderedDict(
    (
        ("RunsResource", "runs"),
        ("BenchmarksResource", "benchmarks"),
        ("AgentsResource", "agents"),
        ("BenchmarkServicesResource", "services"),
    )
)
_GUIDE_LINKS: dict[str, str] = {
    "run": "/runs/start",
    "agent": "/agents/manage-agents",
    "benchmark": "/benchmarks/custom-services",
    "config": "/get-started/configuration",
}
# Card icon and purpose per top-level command group. Counts stay computed from the Click tree, so
# only the icon and the phrase completing "N commands for ..." are curated here. A new group fails
# generation until it is listed.
_CLI_GROUP_CARDS: dict[str, tuple[str, str]] = {
    "run": ("play", "starting, monitoring, managing, and retrieving runs"),
    "agent": ("robot", "installing, uploading, listing, downloading, and removing agent bundles"),
    "benchmark": ("flask", "exporting the task IDs in a benchmark dataset"),
    "config": ("gear", "credentials, sandbox providers, and benchmark services"),
}
_SDK_RESOURCE_CARDS: dict[str, tuple[str, str, str]] = {
    "RunsResource": ("Runs", "play", "starting, inspecting, streaming, controlling, and retrying runs"),
    "BenchmarksResource": ("Benchmarks", "flask", "retrieving benchmark status, tasks, and artifacts"),
    "AgentsResource": ("Agents", "robot", "listing agents and retrieving bundle download URLs"),
    "BenchmarkServicesResource": (
        "Benchmark services",
        "server",
        "discovering service catalogs, deployments, and task IDs",
    ),
}
_SDK_TYPE_FAMILIES = ("Agents", "Runs", "Benchmarks", "Services", "Config")
_SDK_TYPE_FAMILY_CARDS: dict[str, tuple[str, str]] = {
    "Agents": ("robot", "uploaded agent bundles and download URLs"),
    "Runs": ("play", "run requests, responses, and lifecycle enums"),
    "Benchmarks": ("flask", "benchmark, task, artifact, and status responses"),
    "Services": ("server", "benchmark service catalog and health responses"),
    "Config": ("gear", "validated SDK configuration and field aliases"),
}
_CLI_MUTATING_PATHS = frozenset(
    {
        ("run", "analyze"),
        ("run", "resume"),
        ("run", "retry"),
        ("run", "start"),
        ("run", "stop"),
        ("run", "update"),
        ("agent", "install"),
        ("agent", "push"),
        ("agent", "remove"),
        ("agent", "download"),
        ("config", "auth", "set"),
        ("config", "auth", "remove"),
        ("config", "init"),
        ("config", "set"),
        ("config", "remove"),
        ("config", "provider", "set"),
        ("config", "provider", "default"),
        ("config", "provider", "remove"),
        ("config", "service", "set"),
        ("config", "service", "remove"),
    }
)


@dataclass(frozen=True)
class CLIParameterReference:
    """Stable documentation data for one Click parameter."""

    name: str
    kind: Literal["argument", "option"]
    declarations: tuple[str, ...]
    type_name: str
    required: bool
    default: str | None
    multiple: bool
    nargs: int
    metavar: str | None
    constraints: tuple[str, ...]
    help: str


@dataclass(frozen=True)
class CLICommandReference:
    """Stable documentation data for one leaf Click command."""

    path: tuple[str, ...]
    summary: str
    example: str | None
    parameters: tuple[CLIParameterReference, ...]


@dataclass(frozen=True)
class SDKParameterReference:
    """Stable documentation data for one Python callable parameter."""

    name: str
    kind: str
    type_name: str
    required: bool
    default: str | None


@dataclass(frozen=True)
class SDKMethodReference:
    """Stable documentation data for one public SDK method."""

    name: str
    description: str
    signatures: tuple[str, ...]
    parameters: tuple[SDKParameterReference, ...]
    return_types: tuple[str, ...]


@dataclass(frozen=True)
class SDKResourceReference:
    """Stable documentation data for one SDK resource namespace."""

    name: str
    client_attribute: str
    description: str
    methods: tuple[SDKMethodReference, ...]


@dataclass(frozen=True)
class SDKFieldReference:
    """Stable documentation data for one public Pydantic model field."""

    name: str
    type_name: str
    required: bool
    default: str | None
    alias: str | None
    constraints: tuple[str, ...]
    description: str


@dataclass(frozen=True)
class SDKModelReference:
    """Stable documentation data for one public Pydantic model."""

    name: str
    module: str
    family: str
    slug: str
    description: str
    fields: tuple[SDKFieldReference, ...]


@dataclass(frozen=True)
class SDKEnumReference:
    """Stable documentation data for one public enum."""

    name: str
    module: str
    family: str
    slug: str
    description: str
    members: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class SDKExceptionReference:
    """Stable documentation data for one public SDK exception."""

    name: str
    parent: str
    description: str
    signature: str


@dataclass(frozen=True)
class SDKExportReference:
    """Stable documentation data for one top-level SDK export."""

    name: str
    kind: str
    target: str


@dataclass(frozen=True)
class SDKReference:
    """Complete tested public SDK reference data."""

    exports: tuple[SDKExportReference, ...]
    resources: tuple[SDKResourceReference, ...]
    models: tuple[SDKModelReference, ...]
    enums: tuple[SDKEnumReference, ...]
    exceptions: tuple[SDKExceptionReference, ...]
    client_methods: tuple[SDKMethodReference, ...]


def _clean_docstring(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return inspect.cleandoc(value)


def _format_value(value: object) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, Path):
        return repr(str(value))
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        items = typing.cast(list[object], value)
        return "[" + ", ".join(_format_value(item) for item in items) + "]"
    if isinstance(value, tuple):
        items = typing.cast(tuple[object, ...], value)
        suffix = "," if len(items) == 1 else ""
        return "(" + ", ".join(_format_value(item) for item in items) + suffix + ")"
    if isinstance(value, dict):
        items = typing.cast(dict[object, object], value)
        rendered = (f"{_format_value(key)}: {_format_value(item)}" for key, item in items.items())
        return "{" + ", ".join(rendered) + "}"
    if isinstance(value, type):
        return value.__name__
    return type(value).__name__


def _format_annotation(annotation: object) -> str:
    if annotation is inspect.Signature.empty or annotation is inspect.Parameter.empty:
        return "Any"
    if annotation is None or annotation is type(None):
        return "None"
    if isinstance(annotation, str):
        return annotation
    if isinstance(annotation, ForwardRef):
        return annotation.__forward_arg__
    if isinstance(annotation, typing.TypeVar):
        return annotation.__name__

    origin = get_origin(annotation)
    arguments = get_args(annotation)
    if origin is typing.Annotated:
        return _format_annotation(arguments[0])
    if origin is typing.Literal:
        return "Literal[" + ", ".join(_format_value(argument) for argument in arguments) + "]"
    if origin in {typing.Union, types.UnionType}:
        return " | ".join(_format_annotation(argument) for argument in arguments)
    if origin is not None:
        origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if arguments:
            return f"{origin_name}[{', '.join(_format_annotation(argument) for argument in arguments)}]"
        return origin_name

    name = getattr(annotation, "__name__", None)
    if isinstance(name, str):
        return name
    return str(annotation).replace("typing.", "")


def _sanitize_public_text(value: str) -> str:
    value = re.sub(
        r"(-s\s+ANTHROPIC_API_KEY)\s+[A-Za-z][A-Za-z0-9_-]+",
        r"\1 AnthropicApiKey",
        value,
    )
    return re.sub(r"\b([A-Za-z0-9._%+-]+)@vals\.ai\b", r"\1@example.com", value)


def _split_click_help(value: str) -> tuple[str, str | None]:
    match = re.search(r"\n\nExample:\s*(.+)$", value, flags=re.DOTALL)
    if match is None:
        return value.strip(), None
    summary = value[: match.start()].strip()
    example = "\n".join(line.strip() for line in match.group(1).strip().splitlines())
    return summary, example


def _format_click_type(parameter_type: click.ParamType) -> tuple[str, tuple[str, ...]]:
    constraints: list[str] = []
    if isinstance(parameter_type, click.Tuple):
        item_types = ", ".join(_format_click_type(item)[0] for item in parameter_type.types)
        return f"tuple[{item_types}]", ()
    if isinstance(parameter_type, click.Choice):
        raw_choices = typing.cast(Sequence[object], parameter_type.choices)
        choices = tuple(str(choice) for choice in raw_choices)
        constraints.append("one of " + ", ".join(f"`{choice}`" for choice in choices))
        if not parameter_type.case_sensitive:
            constraints.append("case-insensitive")
        return "choice", tuple(constraints)
    if isinstance(parameter_type, click.IntRange):
        if parameter_type.min is not None:
            constraints.append(f">= {parameter_type.min}")
        if parameter_type.max is not None:
            constraints.append(f"<= {parameter_type.max}")
        if parameter_type.clamp:
            constraints.append("clamped")
        return "integer", tuple(constraints)
    if isinstance(parameter_type, click.FloatRange):
        if parameter_type.min is not None:
            constraints.append(f">= {parameter_type.min}")
        if parameter_type.max is not None:
            constraints.append(f"<= {parameter_type.max}")
        if parameter_type.clamp:
            constraints.append("clamped")
        return "number", tuple(constraints)
    if isinstance(parameter_type, click.Path):
        if parameter_type.exists:
            constraints.append("must exist")
        if parameter_type.file_okay and not parameter_type.dir_okay:
            constraints.append("file")
        elif parameter_type.dir_okay and not parameter_type.file_okay:
            constraints.append("directory")
        if parameter_type.readable:
            constraints.append("readable")
        if parameter_type.writable:
            constraints.append("writable")
        return "path", tuple(constraints)

    stable_name = parameter_type.name.replace(" range", "")
    return stable_name, ()


def _is_click_unset(value: object) -> bool:
    return (
        isinstance(value, Enum)
        and type(value).__module__.startswith("click.")
        and type(value).__name__ == "Sentinel"
        and value.name == "UNSET"
    )


def _collect_click_parameter(parameter: click.Parameter) -> CLIParameterReference:
    parameter_type, type_constraints = _format_click_type(parameter.type)
    default = None if _is_click_unset(parameter.default) else _format_value(parameter.default)
    constraints = list(type_constraints)
    if parameter.nargs != 1:
        constraints.append(f"{parameter.nargs} values")
    if parameter.multiple:
        constraints.append("repeatable")

    if isinstance(parameter, click.Option):
        declarations = tuple((*parameter.opts, *parameter.secondary_opts))
        help_text = _sanitize_public_text(parameter.help or "")
        kind: Literal["argument", "option"] = "option"
    else:
        declarations = (parameter.human_readable_name.upper(),)
        help_text = ""
        kind = "argument"

    return CLIParameterReference(
        name=parameter.name or declarations[0].lower(),
        kind=kind,
        declarations=declarations,
        type_name=parameter_type,
        required=parameter.required,
        default=default,
        multiple=parameter.multiple,
        nargs=parameter.nargs,
        metavar=parameter.metavar,
        constraints=tuple(constraints),
        help=help_text,
    )


def collect_cli_commands() -> tuple[CLICommandReference, ...]:
    """Collect every registered leaf command without invoking Click callbacks."""
    from valkyrie.cli.main import cli

    commands: list[CLICommandReference] = []

    def visit(command: click.Command, path: tuple[str, ...]) -> None:
        # Hidden commands and options are not part of the public surface, so they stay unpublished.
        if command.hidden:
            return
        if isinstance(command, click.Group):
            for name, child in command.commands.items():
                visit(child, (*path, name))
            return
        summary, example = _split_click_help(_sanitize_public_text(_clean_docstring(command.help)))
        commands.append(
            CLICommandReference(
                path=path,
                summary=summary,
                example=example,
                parameters=tuple(
                    _collect_click_parameter(parameter)
                    for parameter in command.params
                    if not (isinstance(parameter, click.Option) and parameter.hidden)
                ),
            )
        )

    visit(cli, ())
    return tuple(commands)


def _format_callable_parameter(parameter: inspect.Parameter) -> str:
    prefix = ""
    if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
        prefix = "*"
    elif parameter.kind is inspect.Parameter.VAR_KEYWORD:
        prefix = "**"

    result = f"{prefix}{parameter.name}"
    if parameter.annotation is not inspect.Parameter.empty:
        result += f": {_format_annotation(parameter.annotation)}"
    if parameter.default is not inspect.Parameter.empty:
        result += f" = {_format_value(parameter.default)}"
    return result


def _format_signature(name: str, callable_object: Callable[..., object], *, drop_first: bool = True) -> str:
    signature = inspect.signature(callable_object, eval_str=False)
    parameters = list(signature.parameters.values())
    if drop_first and parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]

    rendered: list[str] = []
    keyword_marker_added = False
    for index, parameter in enumerate(parameters):
        if parameter.kind is inspect.Parameter.KEYWORD_ONLY and not keyword_marker_added:
            rendered.append("*")
            keyword_marker_added = True
        rendered.append(_format_callable_parameter(parameter))
        if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
            keyword_marker_added = True
        if parameter.kind is inspect.Parameter.POSITIONAL_ONLY and (
            index + 1 == len(parameters) or parameters[index + 1].kind is not inspect.Parameter.POSITIONAL_ONLY
        ):
            rendered.append("/")

    return_type = _format_annotation(signature.return_annotation)
    async_prefix = (
        "async " if inspect.iscoroutinefunction(callable_object) or inspect.isasyncgenfunction(callable_object) else ""
    )
    one_line = f"{async_prefix}def {name}({', '.join(rendered)}) -> {return_type}"
    if len(one_line) <= 110:
        return one_line

    body = "\n".join(f"    {parameter}," for parameter in rendered)
    return f"{async_prefix}def {name}(\n{body}\n) -> {return_type}"


def _collect_method(name: str, callable_object: Callable[..., object]) -> SDKMethodReference:
    signature = inspect.signature(callable_object, eval_str=False)
    parameters = list(signature.parameters.values())
    if parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]
    parameter_references = tuple(
        SDKParameterReference(
            name=parameter.name,
            kind=parameter.kind.name,
            type_name=_format_annotation(parameter.annotation),
            required=parameter.default is inspect.Parameter.empty,
            default=(None if parameter.default is inspect.Parameter.empty else _format_value(parameter.default)),
        )
        for parameter in parameters
    )
    overloads = typing.get_overloads(callable_object)
    signature_sources = overloads or (callable_object,)

    return SDKMethodReference(
        name=name,
        description=_clean_docstring(inspect.getdoc(callable_object)),
        signatures=tuple(_format_signature(name, source) for source in signature_sources),
        parameters=parameter_references,
        return_types=tuple(
            _format_annotation(inspect.signature(source, eval_str=False).return_annotation)
            for source in signature_sources
        ),
    )


def _field_constraints(metadata: Sequence[object]) -> tuple[str, ...]:
    constraints: list[str] = []
    attributes = (
        ("gt", ">"),
        ("ge", ">="),
        ("lt", "<"),
        ("le", "<="),
        ("multiple_of", "multiple of"),
        ("min_length", "minimum length"),
        ("max_length", "maximum length"),
        ("pattern", "pattern"),
    )
    for item in metadata:
        for attribute, label in attributes:
            value = getattr(item, attribute, None)
            if value is not None:
                constraints.append(f"{label} {_format_value(value)}")
    return tuple(constraints)


def _field_default(field: Any) -> str | None:
    if field.is_required():
        return None
    if field.default_factory is not None:
        factory = field.default_factory
        if factory is list:
            return "[]"
        if factory is dict:
            return "{}"
        if factory is set:
            return "set()"
        factory_name = getattr(factory, "__name__", "generated value")
        return "generated value" if factory_name == "<lambda>" else f"{factory_name}()"
    return _format_value(field.default)


def _model_family(module: str) -> str:
    return module.rsplit(".", 1)[-1].replace("_", " ").title()


def _type_slug(name: str) -> str:
    """Return an acronym-aware, path-safe slug for one public type name."""
    separated = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    separated = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", separated)
    slug = re.sub(r"[^A-Za-z0-9]+", "-", separated).strip("-").lower()
    if not slug or slug in {".", ".."} or "/" in slug or "\\" in slug:
        raise ValueError(f"Unsafe public type slug for {name!r}: {slug!r}")
    return slug


def _sdk_type_family_page_path(family: str) -> Path:
    """Return the single generated page that documents one SDK type family."""
    return Path("reference/sdk/models", family.lower()).with_suffix(".mdx")


def _sdk_type_path(entry: SDKModelReference | SDKEnumReference) -> Path:
    """Return the family page where one public SDK type is documented."""
    return _sdk_type_family_page_path(entry.family)


def _sdk_type_anchor(entry: SDKModelReference | SDKEnumReference) -> str:
    """Return the stable explicit heading id for one public SDK type inside its family page."""
    return entry.slug


def _sdk_type_route(entry: SDKModelReference | SDKEnumReference) -> str:
    """Return the public family-page anchor where one public SDK type is documented."""
    return f"/{_route(_sdk_type_path(entry))}#{_sdk_type_anchor(entry)}"


def _legacy_type_route(entry: SDKModelReference | SDKEnumReference) -> str:
    """Return the retired per-type route that must keep resolving through a redirect."""
    return "/" + Path("reference/sdk/models", entry.family.lower(), entry.slug).as_posix()


def _collect_model(model: type[BaseModel]) -> SDKModelReference:
    fields = tuple(
        SDKFieldReference(
            name=name,
            type_name=_format_annotation(field.annotation),
            required=field.is_required(),
            default=_field_default(field),
            alias=field.alias if field.alias != name else None,
            constraints=_field_constraints(field.metadata),
            description=field.description or "",
        )
        for name, field in model.model_fields.items()
    )
    return SDKModelReference(
        name=model.__name__,
        module=model.__module__,
        family=_model_family(model.__module__),
        slug=_type_slug(model.__name__),
        description=_clean_docstring(inspect.getdoc(model)),
        fields=fields,
    )


def _collect_enum(enum_class: type[Enum]) -> SDKEnumReference:
    return SDKEnumReference(
        name=enum_class.__name__,
        module=enum_class.__module__,
        family=_model_family(enum_class.__module__),
        slug=_type_slug(enum_class.__name__),
        description=_clean_docstring(inspect.getdoc(enum_class)),
        members=tuple((member.name, _format_value(member.value)) for member in enum_class),
    )


def _validate_type_paths(entries: Sequence[SDKModelReference | SDKEnumReference]) -> None:
    """Reject duplicate names, duplicate anchors within a family, and unsafe slugs."""
    names: set[str] = set()
    anchors: set[tuple[str, str]] = set()
    for entry in entries:
        if entry.name in names:
            raise ValueError(f"Duplicate public type name: {entry.name}")
        names.add(entry.name)
        key = (entry.family, _sdk_type_anchor(entry))
        if key in anchors:
            raise ValueError(f"Duplicate public type path: {_sdk_type_path(entry)}#{_sdk_type_anchor(entry)}")
        anchors.add(key)


def _collect_exception(exception_class: type[Exception]) -> SDKExceptionReference:
    if "__init__" not in exception_class.__dict__:
        signature = "(*args: object)"
    else:
        try:
            signature = str(inspect.signature(exception_class))
        except (TypeError, ValueError):
            signature = "(*args: object)"
    parent = exception_class.__base__.__name__ if exception_class.__base__ is not None else "Exception"
    return SDKExceptionReference(
        name=exception_class.__name__,
        parent=parent,
        description=_clean_docstring(inspect.getdoc(exception_class)),
        signature=f"{exception_class.__name__}{signature}",
    )


def _collect_constructor(client_class: type[object]) -> SDKMethodReference:
    method = _collect_method("Constructor", client_class.__init__)
    signature = _format_signature(client_class.__name__, client_class.__init__)
    signature = signature.removeprefix("def ").rsplit(" -> ", 1)[0] + f" -> {client_class.__name__}"
    return SDKMethodReference(
        name=method.name,
        description=_clean_docstring(inspect.getdoc(client_class)),
        signatures=(signature,),
        parameters=method.parameters,
        return_types=(client_class.__name__,),
    )


def _resource_methods(resource_class: type[object]) -> tuple[SDKMethodReference, ...]:
    methods: list[SDKMethodReference] = []
    for name, value in resource_class.__dict__.items():
        if name.startswith("_") or not callable(value):
            continue
        methods.append(_collect_method(name, value))
    return tuple(methods)


def collect_sdk_reference() -> SDKReference:
    """Collect the tested top-level SDK exports and public resource methods."""
    import valkyrie.sdk as sdk
    from valkyrie.sdk.client import ValkyrieClient
    from valkyrie.sdk.resources import AgentsResource, BenchmarksResource, BenchmarkServicesResource, RunsResource

    resource_classes = (
        ("RunsResource", "client.runs", RunsResource),
        ("BenchmarksResource", "client.benchmarks", BenchmarksResource),
        ("AgentsResource", "client.agents", AgentsResource),
        ("BenchmarkServicesResource", "client.services", BenchmarkServicesResource),
    )
    resources = tuple(
        SDKResourceReference(
            name=name,
            client_attribute=client_attribute,
            description=_clean_docstring(inspect.getdoc(resource_class)),
            methods=_resource_methods(resource_class),
        )
        for name, client_attribute, resource_class in resource_classes
    )

    models: list[SDKModelReference] = []
    enums: list[SDKEnumReference] = []
    exceptions: list[SDKExceptionReference] = []
    exports: list[SDKExportReference] = []
    for name in sdk.__all__:
        value = getattr(sdk, name)
        if inspect.isclass(value) and issubclass(value, Enum):
            enums.append(_collect_enum(value))
            kind = "enum"
            target = _sdk_type_route(enums[-1])
        elif inspect.isclass(value) and issubclass(value, BaseModel):
            models.append(_collect_model(value))
            kind = "model"
            target = _sdk_type_route(models[-1])
        elif inspect.isclass(value) and issubclass(value, Exception):
            exceptions.append(_collect_exception(value))
            kind = "exception"
            target = f"/reference/sdk/errors#{name.lower()}"
        elif value is ValkyrieClient:
            kind = "client"
            target = "/reference/sdk/client"
        else:
            kind = "export"
            target = "/reference/sdk/index"
        exports.append(SDKExportReference(name=name, kind=kind, target=target))

    _validate_type_paths((*models, *enums))

    client_methods = (
        _collect_constructor(ValkyrieClient),
        _collect_method("from_config", ValkyrieClient.from_config.__func__),
        _collect_method("close", ValkyrieClient.close),
    )
    return SDKReference(
        exports=tuple(exports),
        resources=resources,
        models=tuple(models),
        enums=tuple(enums),
        exceptions=tuple(exceptions),
        client_methods=client_methods,
    )


def _escape_braces(value: str) -> str:
    """Escape braces so MDX renders them as text instead of a JSX expression."""
    return value.replace("{", "&#123;").replace("}", "&#125;")


def _escape_cell(value: str) -> str:
    escaped = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("|", "\\|")
    return _escape_braces(escaped).replace("\n", "<br />")


def _frontmatter(title: str, description: str) -> list[str]:
    return [
        "---",
        f"title: {json.dumps(title)}",
        f"description: {json.dumps(description)}",
        "---",
        "",
        _GENERATED_MARKER,
        "",
    ]


def _page_summary(summary: str, fallback: str) -> tuple[str, tuple[str, ...]]:
    """Split a summary into a frontmatter description and any remaining body paragraphs.

    Mintlify renders the frontmatter description under the page title, so repeating it in the
    body only duplicates it. The first paragraph becomes the description; later paragraphs are
    genuinely additional text and are kept in the body.
    """
    paragraphs = [" ".join(block.split()) for block in summary.strip().split("\n\n")]
    paragraphs = [block for block in paragraphs if block]
    if not paragraphs:
        return fallback, ()
    return paragraphs[0], tuple(paragraphs[1:])


def _page_header(title: str, summary: str, fallback: str) -> list[str]:
    """Render frontmatter plus any body text the frontmatter description does not already show."""
    description, body = _page_summary(summary, fallback)
    lines = _frontmatter(title, description)
    for paragraph in body:
        lines.extend((paragraph, ""))
    return lines


def _route(path: Path) -> str:
    return path.with_suffix("").as_posix()


def _cli_group_page_path(group: str) -> Path:
    """Return the single generated page that documents one top-level command group."""
    return Path("reference/cli", group).with_suffix(".mdx")


def _cli_command_anchor(command: CLICommandReference) -> str:
    """Return the stable explicit heading id for one leaf command inside its group page."""
    return "-".join(command.path[1:])


def _cli_command_route(command: CLICommandReference) -> str:
    """Return the public route and anchor a leaf command is documented at."""
    return f"/{_route(_cli_group_page_path(command.path[0]))}#{_cli_command_anchor(command)}"


def _cli_legacy_command_route(command: CLICommandReference) -> str:
    """Return the retired per-command route that must keep resolving through a redirect."""
    return "/" + Path("reference/cli", *command.path).as_posix()


def _cli_groups(commands: Sequence[CLICommandReference]) -> OrderedDict[str, list[CLICommandReference]]:
    """Group leaf commands by top-level group, preserving Click registration order."""
    groups: OrderedDict[str, list[CLICommandReference]] = OrderedDict()
    for command in commands:
        groups.setdefault(command.path[0], []).append(command)
    return groups


def cli_redirects(commands: Sequence[CLICommandReference] | None = None) -> list[dict[str, str]]:
    """Map every retired per-command route to its group page anchor.

    Mintlify's redirect schema takes a free-form ``destination`` string and its redirect
    validator strips ``#``/``?`` selectors before resolving, so anchor destinations are supported.
    """
    resolved = collect_cli_commands() if commands is None else commands
    return [
        {"source": _cli_legacy_command_route(command), "destination": _cli_command_route(command)}
        for command in resolved
    ]


def _sdk_resource_page_path(resource_page: str) -> Path:
    """Return the single generated page that documents one SDK resource namespace."""
    return Path("reference/sdk", resource_page).with_suffix(".mdx")


def _sdk_method_anchor(method: SDKMethodReference) -> str:
    """Return the stable explicit heading id for one SDK method inside its resource page."""
    return method.name.replace("_", "-")


def _sdk_method_route(resource_page: str, method: SDKMethodReference) -> str:
    """Return the public route and anchor where one SDK method is documented."""
    return f"/{_route(_sdk_resource_page_path(resource_page))}#{_sdk_method_anchor(method)}"


def _sdk_legacy_method_route(resource_page: str, method: SDKMethodReference) -> str:
    """Return the retired per-method route that must keep resolving through a redirect."""
    return "/" + Path("reference/sdk", resource_page, method.name).as_posix()


def sdk_redirects(reference: SDKReference | None = None) -> list[dict[str, str]]:
    """Map every retired SDK method route to its resource page anchor."""
    resolved = collect_sdk_reference() if reference is None else reference
    return [
        {
            "source": _sdk_legacy_method_route(_RESOURCE_PAGES[resource.name], method),
            "destination": _sdk_method_route(_RESOURCE_PAGES[resource.name], method),
        }
        for resource in resolved.resources
        for method in resource.methods
    ]


def sdk_type_redirects(reference: SDKReference | None = None) -> list[dict[str, str]]:
    """Map every retired per-type route to its family page anchor."""
    resolved = collect_sdk_reference() if reference is None else reference
    return [
        {"source": _legacy_type_route(entry), "destination": _sdk_type_route(entry)}
        for entry in _ordered_type_entries(resolved)
    ]


def redirects(
    commands: Sequence[CLICommandReference] | None = None,
    reference: SDKReference | None = None,
) -> list[dict[str, str]]:
    """Return all retired public reference routes in deterministic registration order."""
    return [*cli_redirects(commands), *sdk_redirects(reference), *sdk_type_redirects(reference)]


def _parameter_metavar(parameter: CLIParameterReference) -> str:
    if parameter.metavar:
        values = [f"<{parameter.metavar}>" for _ in range(max(parameter.nargs, 1))]
    elif parameter.kind == "argument":
        values = [f"<{parameter.declarations[0]}>" for _ in range(max(parameter.nargs, 1))]
    elif parameter.type_name.startswith("tuple["):
        item_types = parameter.type_name.removeprefix("tuple[").removesuffix("]").split(", ")
        values = [f"<{item.upper()}>" for item in item_types]
    elif parameter.type_name == "boolean":
        values = []
    else:
        values = [f"<{parameter.type_name.upper()}>" for _ in range(max(parameter.nargs, 1))]
    return " ".join(values)


def _command_usage(command: CLICommandReference) -> str:
    """Render complete non-executable Click syntax in registration order."""
    fragments: list[str] = ["valkyrie " + " ".join(command.path)]
    for parameter in command.parameters:
        metavar = _parameter_metavar(parameter)
        if parameter.kind == "argument":
            fragment = metavar
        else:
            fragment = "|".join(parameter.declarations)
            if metavar:
                fragment += f" {metavar}"
        if parameter.multiple:
            fragment += "..."
        if not parameter.required:
            fragment = f"[{fragment}]"
        fragments.append(fragment)
    if len(fragments) == 1:
        return fragments[0]
    return " \\\n  ".join(fragments)


def _render_panel(blocks: Sequence[tuple[str, str, str]]) -> list[str]:
    lines = ["<Panel>"]
    if len(blocks) > 1:
        lines.extend(("<CodeGroup>", ""))
    for language, title, content in blocks:
        lines.extend((f"```{language} {title}", content, "```", ""))
    if len(blocks) > 1:
        lines.extend(("</CodeGroup>",))
    lines.extend(("</Panel>", ""))
    return lines


def _jsx_text(value: str) -> str:
    """Render literal text through a JSX string so MDX cannot transform it.

    MDX applies smart typography to JSX text nodes, which turns ``--connect`` into an em dash
    and straight quotes into curly quotes. A string expression keeps parameter names, defaults,
    and constraints exactly as the source declares them.
    """
    return "{" + json.dumps(value, ensure_ascii=False) + "}"


def _escape_html(value: str) -> str:
    return _escape_braces(html.escape(value, quote=False)).replace("\n", "<br />")


def _render_parameter_row(
    name: str,
    type_name: str,
    *,
    required: bool,
    default: str | None,
    constraints: Sequence[str] = (),
    description: str = "",
    type_markup: bool = False,
    alias: str | None = None,
) -> list[str]:
    rendered_type = type_name if type_markup else f"<code>{_jsx_text(type_name)}</code>"
    metadata = ["required" if required else "optional", rendered_type]
    if alias is not None:
        metadata.append(f"alias: <code>{_jsx_text(alias)}</code>")
    if default is not None:
        metadata.append(f"default: <code>{_jsx_text(default)}</code>")
    if constraints:
        metadata.append("constraints: " + _jsx_text("; ".join(constraints)))

    lines = [
        '<div className="border-b border-gray-200 py-3 dark:border-gray-800">',
        '  <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">'
        f'<span className="break-all font-mono text-sm">{_jsx_text(name)}</span>'
        f'<span className="min-w-0 break-words text-sm text-gray-500 dark:text-gray-400">'
        f"{' · '.join(metadata)}</span></div>",
    ]
    if description:
        lines.append(f'  <p className="mb-0 mt-1">{_jsx_text(description)}</p>')
    lines.extend(("</div>", ""))
    return lines


def _render_cli_parameter_table(
    parameters: Sequence[CLIParameterReference], kind: str, *, label_only: bool = False
) -> list[str]:
    """Render compact parameter rows under a section label.

    ``label_only`` emits a bold label instead of a heading so that grouped command pages keep
    the native table of contents limited to command headings.
    """
    selected = [parameter for parameter in parameters if parameter.kind == kind]
    if not selected:
        return []
    title = "Arguments" if kind == "argument" else "Options"
    lines = [f"**{title}**" if label_only else f"## {title}", ""]
    for parameter in selected:
        lines.extend(
            _render_parameter_row(
                ", ".join(parameter.declarations),
                parameter.type_name,
                required=parameter.required,
                default=parameter.default,
                constraints=parameter.constraints,
                description=parameter.help,
            )
        )
    return lines


def _format_cli_example(command: CLICommandReference, example: str) -> str:
    """Put each concrete argument or option group on its own shell line."""
    comments = [line for line in example.splitlines() if line.startswith("#")]
    command_line = next((line for line in example.splitlines() if line and not line.startswith("#")), "")
    tokens = command_line.split()
    prefix_length = 1 + len(command.path)
    if len(tokens) <= prefix_length:
        return example

    option_by_declaration = {
        declaration: parameter
        for parameter in command.parameters
        if parameter.kind == "option"
        for declaration in parameter.declarations
    }
    groups: list[list[str]] = []
    index = prefix_length
    while index < len(tokens):
        token = tokens[index]
        parameter = option_by_declaration.get(token)
        value_count = max(parameter.nargs, 1) if parameter is not None and parameter.type_name != "boolean" else 0
        group = tokens[index : index + 1 + value_count]
        groups.append(group)
        index += len(group)

    if len(groups) <= 1:
        return example
    lines = [*comments, " ".join(tokens[:prefix_length]) + " \\"]
    for position, group in enumerate(groups):
        continuation = " \\" if position < len(groups) - 1 else ""
        lines.append("  " + " ".join(group) + continuation)
    return "\n".join(lines)


def _cli_example(command: CLICommandReference) -> str | None:
    """Return the runnable-looking example for one command, with destructive cases neutralized."""
    if command.example is None:
        return None
    example = command.example
    if command.path == ("run", "stop"):
        example = "valkyrie run stop $RUN_ID"
    elif command.path == ("config", "auth", "set"):
        example = "valkyrie config auth set benchmark-name $BENCHMARK_CREDENTIAL"
    if command.path in _CLI_MUTATING_PATHS:
        example = "# Example only — review before running\n" + example
    return _format_cli_example(command, example)


def _render_cli_command_section(command: CLICommandReference) -> list[str]:
    """Render one leaf command as a level-2 section with an explicit stable anchor.

    Code blocks stay inline rather than inside a Panel or CodeGroup, because Mintlify replaces
    the native right table of contents on pages that use a Panel.
    """
    command_name = "valkyrie " + " ".join(command.path)
    summary, extra_paragraphs = _page_summary(command.summary, f"Reference for {command_name}.")
    lines = [f"## `{command_name}` {{#{_cli_command_anchor(command)}}}", "", summary, ""]
    for paragraph in extra_paragraphs:
        lines.extend((paragraph, ""))

    blocks = [("bash", "Syntax", _command_usage(command))]
    example = _cli_example(command)
    if example is not None:
        blocks.append(("bash", "Example", example))
    for language, title, content in blocks:
        lines.extend((f"```{language} {title}", content, "```", ""))

    if command.path == ("run", "retry"):
        lines.extend(
            (
                "`retry` is a command alias for the retry mode of `run resume` and shares its options. "
                "It always retries tasks in `ERROR` status; use `run resume` to admit pending tasks instead.",
                "",
            )
        )
    lines.extend(_render_cli_parameter_table(command.parameters, "argument", label_only=True))
    lines.extend(_render_cli_parameter_table(command.parameters, "option", label_only=True))
    guide = _GUIDE_LINKS[command.path[0]]
    lines.extend((f"Task guidance: [{command.path[0].title()} guides]({guide}).", ""))
    return lines


def _render_cli_group_page(group: str, commands: Sequence[CLICommandReference]) -> str:
    """Render every command in one top-level group as a single page."""
    lines = _frontmatter(f"valkyrie {group}", f"Complete generated reference for every `valkyrie {group}` command.")
    lines.extend(
        (
            f"This page documents all {len(commands)} commands in the `{group}` group in registration order. "
            "Use the table of contents to jump to a command.",
            "",
        )
    )
    for position, command in enumerate(commands):
        if position:
            lines.extend(("---", ""))
        lines.extend(_render_cli_command_section(command))
    return "\n".join(lines).rstrip() + "\n"


def _render_cli_index(commands: Sequence[CLICommandReference]) -> str:
    lines = _frontmatter("CLI reference", "Complete generated reference for every Valkyrie CLI command.")
    lines.extend(
        (
            "This reference is generated from the CLI itself. Use the task guides for complete workflows.",
            "",
            "## Command groups",
            "",
            "<CardGroup cols={2}>",
        )
    )
    for group, group_commands in _cli_groups(commands).items():
        icon, purpose = _CLI_GROUP_CARDS[group]
        route = _route(_cli_group_page_path(group))
        count = len(group_commands)
        noun = "command" if count == 1 else "commands"
        lines.extend(
            (
                f'  <Card title="{group.title()} commands" icon="{icon}" href="/{route}">',
                f"    {count} {noun} for {purpose}.",
                "  </Card>",
            )
        )
    lines.extend(("</CardGroup>", ""))
    return "\n".join(lines)


def _cli_navigation(commands: Sequence[CLICommandReference]) -> list[object]:
    """Return one navigation entry for the index plus one per top-level command group."""
    navigation: list[object] = [_route(_CLI_INDEX_PATH)]
    navigation.extend(_route(_cli_group_page_path(group)) for group in _cli_groups(commands))
    return navigation


def _public_type_routes(reference: SDKReference) -> dict[str, str]:
    return {entry.name: _sdk_type_route(entry) for entry in (*reference.models, *reference.enums)}


def _link_public_types(value: str, type_routes: dict[str, str]) -> str:
    """Link exact public type tokens while preserving containers and unions."""
    parts = re.split(r"([A-Za-z_][A-Za-z0-9_]*)", value)
    rendered: list[str] = []
    for part in parts:
        if part in type_routes:
            rendered.append(f'<a href="{type_routes[part]}"><code>{part}</code></a>')
        else:
            rendered.append(_escape_html(part))
    return "".join(rendered)


def _render_sdk_parameter_table(
    parameters: Sequence[SDKParameterReference],
    *,
    heading_level: int | None = 2,
    type_routes: dict[str, str] | None = None,
) -> list[str]:
    if not parameters:
        return []
    heading = "**Parameters**" if heading_level is None else f"{'#' * heading_level} Parameters"
    lines = [heading, ""]
    for parameter in parameters:
        lines.extend(
            _render_parameter_row(
                parameter.name,
                _link_public_types(parameter.type_name, type_routes or {}),
                required=parameter.required,
                default=parameter.default,
                type_markup=True,
            )
        )
    return lines


def _render_returns(
    method: SDKMethodReference,
    *,
    heading_level: int | None = 2,
    type_routes: dict[str, str] | None = None,
) -> list[str]:
    heading = "**Returns**" if heading_level is None else f"{'#' * heading_level} Returns"
    lines = [heading, ""]
    if len(method.return_types) == 1:
        lines.extend((_link_public_types(method.return_types[0], type_routes or {}), ""))
        return lines
    lines.extend(
        ("The selected overload determines the return type.", "", "| Overload | Return type |", "| ---: | --- |")
    )
    for index, return_type in enumerate(method.return_types, start=1):
        lines.append(f"| {index} | {_link_public_types(return_type, type_routes or {})} |")
    return [*lines, ""]


def _render_sdk_method_section(
    reference: SDKReference,
    resource: SDKResourceReference,
    page: str,
    method: SDKMethodReference,
) -> list[str]:
    """Render one SDK method as a level-2 section with an explicit stable anchor."""
    title = f"{resource.client_attribute}.{method.name}"
    summary, extra_paragraphs = _page_summary(method.description, f"Reference for {title}.")
    lines = [f"## `{title}` {{#{_sdk_method_anchor(method)}}}", "", summary, ""]
    for paragraph in extra_paragraphs:
        lines.extend((paragraph, ""))

    for index, signature in enumerate(method.signatures, start=1):
        label = "Signature" if len(method.signatures) == 1 else f"Overload {index}"
        lines.extend((f"```python {label}", signature, "```", ""))

    type_routes = _public_type_routes(reference)
    lines.extend(_render_sdk_parameter_table(method.parameters, heading_level=None, type_routes=type_routes))
    lines.extend(_render_returns(method, heading_level=None, type_routes=type_routes))
    guide = "/sdk/runs" if page == "runs" else "/sdk/resources"
    lines.extend((f"For examples, see the [Python SDK guide]({guide}).", ""))
    return lines


def _render_sdk_resource_page(
    reference: SDKReference,
    resource: SDKResourceReference,
    page: str,
) -> str:
    """Render one resource page with every public method in source order."""
    title, _, _ = _SDK_RESOURCE_CARDS[resource.name]
    lines = _page_header(f"{title} resource", resource.description, f"Reference for {resource.client_attribute}.")
    lines.extend((f"Access these methods through `{resource.client_attribute}`.", ""))
    for method in resource.methods:
        lines.extend(_render_sdk_method_section(reference, resource, page, method))
    return "\n".join(lines).rstrip() + "\n"


def _render_sdk_index(reference: SDKReference) -> str:
    lines = _frontmatter("Python SDK reference", "Complete generated reference for the public Valkyrie Python SDK.")
    lines.extend(
        (
            "This reference follows the tested `valkyrie.sdk` public contract. Internal models and helpers are excluded.",
            "",
            "## Client",
            "",
            "Use [`ValkyrieClient`](/reference/sdk/client) to configure the async client and access resource namespaces.",
            "",
            "## Resource namespaces",
            "",
            "<CardGroup cols={2}>",
        )
    )
    for resource in reference.resources:
        page = _RESOURCE_PAGES[resource.name]
        title, icon, purpose = _SDK_RESOURCE_CARDS[resource.name]
        count = len(resource.methods)
        method_label = "method" if count == 1 else "methods"
        lines.extend(
            (
                f'  <Card title="{title}" icon="{icon}" href="/{_route(_sdk_resource_page_path(page))}">',
                f"    {count} {method_label} for {purpose}.",
                "  </Card>",
            )
        )
    lines.extend(
        (
            "</CardGroup>",
            "",
            "## Types and errors",
            "",
            "Browse [public models and enums](/reference/sdk/models) or the [SDK error hierarchy](/reference/sdk/errors).",
            "",
        )
    )
    return "\n".join(lines)


def _render_sdk_client(reference: SDKReference) -> str:
    lines = _frontmatter("ValkyrieClient", "Construct and close the async Valkyrie SDK client.")
    lines.extend(
        (
            "`ValkyrieClient` owns the async HTTP connection pool and exposes the public resource namespaces.",
            "",
        )
    )
    blocks = [("python", method.name, method.signatures[0]) for method in reference.client_methods]
    lines.extend(_render_panel(blocks))
    for method in reference.client_methods:
        lines.extend((f"## {method.name}", "", method.description, ""))
        type_routes = _public_type_routes(reference)
        lines.extend(_render_sdk_parameter_table(method.parameters, heading_level=3, type_routes=type_routes))
        lines.extend(_render_returns(method, heading_level=3, type_routes=type_routes))
    lines.extend(
        (
            "## Async context manager",
            "",
            "The client closes its connection pool when an `async with` block exits.",
            "",
            "```python",
            "async with ValkyrieClient(config) as client:",
            '    run = await client.runs.start(agent="sweagent", benchmark="swebench")',
            "```",
            "",
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def _sdk_navigation(reference: SDKReference) -> list[object]:
    """Return the SDK reference navigation with flat grouped Types pages."""
    navigation: list[object] = [_route(_SDK_INDEX_PATH), _route(_SDK_CLIENT_PATH)]
    navigation.extend(
        _route(_sdk_resource_page_path(_RESOURCE_PAGES[resource.name])) for resource in reference.resources
    )
    type_pages: list[object] = [_route(_SDK_TYPES_INDEX_PATH)]
    type_pages.extend(_route(_sdk_type_family_page_path(family)) for family in _SDK_TYPE_FAMILIES)
    type_pages.append(_route(_SDK_ERRORS_PATH))
    navigation.append({"group": "Types", "pages": type_pages})
    return navigation


def _ordered_type_entries(reference: SDKReference) -> tuple[SDKModelReference | SDKEnumReference, ...]:
    by_name = {entry.name: entry for entry in (*reference.models, *reference.enums)}
    return tuple(by_name[export.name] for export in reference.exports if export.name in by_name)


def _render_types_index(reference: SDKReference) -> str:
    """Render the Types landing as a compact two-column card grid."""
    lines = _frontmatter("Python SDK types", "Public models and enums exported by the Valkyrie Python SDK.")
    lines.extend(
        (
            "Only public models and enums exported from `valkyrie.sdk` appear here.",
            "",
            "## Type families",
            "",
            "<CardGroup cols={2}>",
        )
    )
    entries = _ordered_type_entries(reference)
    for family in _SDK_TYPE_FAMILIES:
        family_entries = [entry for entry in entries if entry.family == family]
        page = _sdk_type_family_page_path(family)
        icon, purpose = _SDK_TYPE_FAMILY_CARDS[family]
        count = len(family_entries)
        noun = "type" if count == 1 else "types"
        lines.extend(
            (
                f'  <Card title="{family}" icon="{icon}" href="/{_route(page)}">',
                f"    {count} {noun} for {purpose}.",
                "  </Card>",
            )
        )
    lines.extend(("</CardGroup>", ""))
    return "\n".join(lines).rstrip() + "\n"


def _render_enum_member_row(name: str, value: str) -> list[str]:
    """Render one enum member as a compact source-order row."""
    return [
        '<div className="border-b border-gray-200 py-3 dark:border-gray-800">',
        '  <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">'
        f'<span className="break-all font-mono text-sm">{_jsx_text(name)}</span>'
        f'<span className="text-sm text-gray-500 dark:text-gray-400">'
        f"<code>{_jsx_text(value)}</code></span></div>",
        "</div>",
        "",
    ]


def _render_type_section(reference: SDKReference, entry: SDKModelReference | SDKEnumReference) -> list[str]:
    """Render one public SDK type as a level-2 section with an explicit stable anchor."""
    lines = [f"## `{entry.name}` {{#{_sdk_type_anchor(entry)}}}", ""]
    if entry.description:
        lines.extend((entry.description, ""))
    kind = "enum" if isinstance(entry, SDKEnumReference) else "model"
    items = entry.members if isinstance(entry, SDKEnumReference) else entry.fields
    count = len(items)
    noun = "member" if kind == "enum" else "field"
    if count != 1:
        noun += "s"
    lines.append(f"{entry.family} {kind} · {count} {noun}")
    lines.append("")
    label = "Members" if kind == "enum" else "Fields"
    lines.append(f"**{label}**")
    lines.append("")
    if kind == "enum":
        for name, value in entry.members:
            lines.extend(_render_enum_member_row(name, value))
    else:
        type_routes = _public_type_routes(reference)
        for field in entry.fields:
            lines.extend(
                _render_parameter_row(
                    field.name,
                    _link_public_types(field.type_name, type_routes),
                    required=field.required,
                    default=field.default,
                    alias=field.alias,
                    constraints=field.constraints,
                    description=field.description,
                    type_markup=True,
                )
            )
    return lines


def _render_type_family_page(
    reference: SDKReference, family: str, entries: Sequence[SDKModelReference | SDKEnumReference]
) -> str:
    """Render every public model and enum in one SDK type family on a single page."""
    lines = _frontmatter(
        f"{family} types",
        f"Public {family.lower()} models and enums exported by the Valkyrie Python SDK.",
    )
    lines.extend(
        (
            f"This page documents all {len(entries)} public types in the `{family}` family in source order. "
            "Use the table of contents to jump to a type.",
            "",
        )
    )
    for position, entry in enumerate(entries):
        if position:
            lines.extend(("---", ""))
        lines.extend(_render_type_section(reference, entry))
    return "\n".join(lines).rstrip() + "\n"


def _render_errors(reference: SDKReference) -> str:
    lines = _frontmatter("Python SDK errors", "Generated exception hierarchy for the public Valkyrie SDK.")
    lines.extend(
        (
            "Catch `ValkyrieSDKError` to handle every SDK-defined failure, or catch a specific subclass.",
            "",
            "| Exception | Parent |",
            "| --- | --- |",
        )
    )
    for error in reference.exceptions:
        lines.append(f"| [`{error.name}`](#{error.name.lower()}) | `{error.parent}` |")
    lines.append("")
    for error in reference.exceptions:
        lines.extend((f"## `{error.name}`", "", error.description, "", "```python", error.signature, "```", ""))
    return "\n".join(lines)


def _render_json(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def render_reference() -> OrderedDict[Path, str]:
    """Render the code-derived generated manifest in deterministic order."""
    commands = collect_cli_commands()
    sdk_reference = collect_sdk_reference()
    rendered: OrderedDict[Path, str] = OrderedDict()
    rendered[_CLI_INDEX_PATH] = _render_cli_index(commands).rstrip() + "\n"
    rendered[_CLI_NAVIGATION_PATH] = _render_json(_cli_navigation(commands))
    for group, group_commands in _cli_groups(commands).items():
        rendered[_cli_group_page_path(group)] = _render_cli_group_page(group, group_commands)

    rendered[_SDK_INDEX_PATH] = _render_sdk_index(sdk_reference).rstrip() + "\n"
    rendered[_SDK_CLIENT_PATH] = _render_sdk_client(sdk_reference)
    rendered[_SDK_NAVIGATION_PATH] = _render_json(_sdk_navigation(sdk_reference))
    for resource in sdk_reference.resources:
        page = _RESOURCE_PAGES[resource.name]
        rendered[_sdk_resource_page_path(page)] = _render_sdk_resource_page(sdk_reference, resource, page)
    rendered[_REDIRECTS_PATH] = _render_json(redirects(commands, sdk_reference))
    rendered[_SDK_TYPES_INDEX_PATH] = _render_types_index(sdk_reference)
    type_entries = _ordered_type_entries(sdk_reference)
    for family in _SDK_TYPE_FAMILIES:
        family_entries = [entry for entry in type_entries if entry.family == family]
        rendered[_sdk_type_family_page_path(family)] = _render_type_family_page(sdk_reference, family, family_entries)
    rendered[_SDK_ERRORS_PATH] = _render_errors(sdk_reference).rstrip() + "\n"
    return rendered


def _obsolete_generated_files(docs_root: Path, expected: set[Path]) -> tuple[Path, ...]:
    reference_root = docs_root / "reference"
    if not reference_root.exists():
        return ()
    obsolete: list[Path] = []
    for path in reference_root.rglob("*.mdx"):
        relative_path = path.relative_to(docs_root)
        if relative_path in expected:
            continue
        if _GENERATED_MARKER in path.read_text(encoding="utf-8"):
            obsolete.append(relative_path)
    for relative_path in _RETIRED_GENERATED_PATHS:
        if relative_path not in expected and (docs_root / relative_path).is_file():
            obsolete.append(relative_path)
    return tuple(sorted(obsolete))


def _prune_empty_reference_directories(docs_root: Path) -> None:
    """Remove directories left empty after retired generated pages are deleted."""
    reference_root = docs_root / "reference"
    if not reference_root.exists():
        return
    for path in sorted(reference_root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def write_reference(docs_root: Path = _DOCS_ROOT) -> tuple[Path, ...]:
    """Write the manifest and remove only obsolete files bearing the generated marker."""
    rendered = render_reference()
    for relative_path in rendered:
        output_path = docs_root / relative_path
        if output_path.suffix == ".mdx" and output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            if _GENERATED_MARKER not in existing:
                raise FileExistsError(f"Refusing to overwrite unmarked file: {relative_path}")

    obsolete = _obsolete_generated_files(docs_root, set(rendered))
    for relative_path in obsolete:
        (docs_root / relative_path).unlink()
    _prune_empty_reference_directories(docs_root)

    for relative_path, content in rendered.items():
        output_path = docs_root / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8", newline="\n")
    return obsolete


def check_reference(docs_root: Path = _DOCS_ROOT) -> tuple[str, ...]:
    """Return diagnostics for missing, stale, or unexpected generated files."""
    rendered = render_reference()
    diagnostics: list[str] = []
    for relative_path, expected in rendered.items():
        output_path = docs_root / relative_path
        if not output_path.exists():
            diagnostics.append(f"missing: {relative_path}")
            continue
        actual = output_path.read_text(encoding="utf-8")
        if actual == expected:
            continue
        diagnostics.append(f"stale: {relative_path}")
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(relative_path),
            tofile=f"generated/{relative_path}",
            lineterm="",
        )
        diagnostics.extend(list(diff)[:_MAX_DIFF_LINES])
    diagnostics.extend(
        f"unexpected generated file: {path}" for path in _obsolete_generated_files(docs_root, set(rendered))
    )
    return tuple(diagnostics)


def main(argv: Sequence[str] | None = None) -> int:
    """Generate reference pages or check that committed output is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing them")
    arguments = parser.parse_args(argv)

    if arguments.check:
        diagnostics = check_reference(_DOCS_ROOT)
        if diagnostics:
            print("Generated documentation reference is stale:")
            for diagnostic in diagnostics:
                print(diagnostic)
            print("Run `make docs-reference` and commit the generated files.")
            return 1
        print("Generated documentation reference is current.")
        return 0

    obsolete = write_reference(_DOCS_ROOT)
    print(f"Generated {len(render_reference())} documentation reference files.")
    if obsolete:
        print(f"Removed {len(obsolete)} obsolete generated files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
