"""Generate deterministic Mintlify reference pages from the public CLI and SDK APIs."""

from __future__ import annotations

import argparse
import difflib
import html
import inspect
import json
import re
import types
import typing
from collections import OrderedDict
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any, ForwardRef, Literal, get_args, get_origin

import click
from pydantic import BaseModel

_ROOT = Path(__file__).resolve().parents[1]
_DOCS_ROOT = _ROOT / "docs"
_GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"
_FORMAT_VERSION = 1
_MAX_DIFF_LINES = 80
_CLI_INDEX_PATH = Path("reference/cli/index.mdx")
_CLI_NAVIGATION_PATH = Path("reference/cli/navigation.json")
_SDK_INDEX_PATH = Path("reference/sdk/index.mdx")
_SDK_CLIENT_PATH = Path("reference/sdk/client.mdx")
_SDK_TYPES_INDEX_PATH = Path("reference/sdk/models/index.mdx")
_SDK_ERRORS_PATH = Path("reference/sdk/errors.mdx")
_SDK_NAVIGATION_PATH = Path("reference/sdk/navigation.json")
_RESOURCE_PAGES: OrderedDict[str, str] = OrderedDict(
    (
        ("RunsResource", "runs"),
        ("BenchmarksResource", "benchmarks"),
        ("AgentsResource", "agents"),
        ("BenchmarkServicesResource", "services"),
    )
)
_GUIDE_LINKS: dict[str, str] = {
    "run": "/runs/start",
    "agent": "/agents/manage-agents",
    "benchmark": "/benchmarks/custom-services",
    "config": "/get-started/configuration",
}
_CLI_HTTP_PATHS = frozenset(
    {
        ("run", "analyze"),
        ("run", "errors"),
        ("run", "fetch"),
        ("run", "list"),
        ("run", "outputs"),
        ("run", "results"),
        ("run", "resume"),
        ("run", "retry"),
        ("run", "start"),
        ("run", "status"),
        ("run", "stop"),
        ("run", "update"),
        ("benchmark", "tasks"),
        ("config", "init"),
        ("config", "service", "list"),
    }
)
_CLI_LOCAL_PATHS = frozenset(
    {
        ("run", "output"),
        ("agent", "install"),
        ("agent", "push"),
        ("agent", "remove"),
        ("agent", "download"),
        ("agent", "list"),
        ("config", "auth", "set"),
        ("config", "auth", "remove"),
        ("config", "auth", "list"),
        ("config", "set"),
        ("config", "remove"),
        ("config", "provider", "set"),
        ("config", "provider", "default"),
        ("config", "provider", "remove"),
        ("config", "provider", "list"),
        ("config", "service", "set"),
        ("config", "service", "remove"),
    }
)
_CLI_MUTATING_PATHS = frozenset(
    {
        ("run", "analyze"),
        ("run", "resume"),
        ("run", "retry"),
        ("run", "start"),
        ("run", "stop"),
        ("run", "update"),
        ("agent", "install"),
        ("agent", "push"),
        ("agent", "remove"),
        ("agent", "download"),
        ("config", "auth", "set"),
        ("config", "auth", "remove"),
        ("config", "init"),
        ("config", "set"),
        ("config", "remove"),
        ("config", "provider", "set"),
        ("config", "provider", "default"),
        ("config", "provider", "remove"),
        ("config", "service", "set"),
        ("config", "service", "remove"),
    }
)


@dataclass(frozen=True)
class CLIParameterReference:
    """Stable documentation data for one Click parameter."""

    name: str
    kind: Literal["argument", "option"]
    declarations: tuple[str, ...]
    type_name: str
    required: bool
    default: str | None
    multiple: bool
    nargs: int
    metavar: str | None
    constraints: tuple[str, ...]
    help: str


@dataclass(frozen=True)
class CLICommandReference:
    """Stable documentation data for one leaf Click command."""

    path: tuple[str, ...]
    summary: str
    example: str | None
    parameters: tuple[CLIParameterReference, ...]


@dataclass(frozen=True)
class SDKParameterReference:
    """Stable documentation data for one Python callable parameter."""

    name: str
    kind: str
    type_name: str
    required: bool
    default: str | None


@dataclass(frozen=True)
class SDKMethodReference:
    """Stable documentation data for one public SDK method."""

    name: str
    description: str
    signatures: tuple[str, ...]
    parameters: tuple[SDKParameterReference, ...]
    return_types: tuple[str, ...]


@dataclass(frozen=True)
class SDKResourceReference:
    """Stable documentation data for one SDK resource namespace."""

    name: str
    client_attribute: str
    description: str
    methods: tuple[SDKMethodReference, ...]


@dataclass(frozen=True)
class SDKFieldReference:
    """Stable documentation data for one public Pydantic model field."""

    name: str
    type_name: str
    required: bool
    default: str | None
    alias: str | None
    constraints: tuple[str, ...]
    description: str


@dataclass(frozen=True)
class SDKModelReference:
    """Stable documentation data for one public Pydantic model."""

    name: str
    module: str
    family: str
    slug: str
    description: str
    fields: tuple[SDKFieldReference, ...]


@dataclass(frozen=True)
class SDKEnumReference:
    """Stable documentation data for one public enum."""

    name: str
    module: str
    family: str
    slug: str
    description: str
    members: tuple[tuple[str, str], ...]


@dataclass(frozen=True)
class SDKExceptionReference:
    """Stable documentation data for one public SDK exception."""

    name: str
    parent: str
    description: str
    signature: str


@dataclass(frozen=True)
class SDKExportReference:
    """Stable documentation data for one top-level SDK export."""

    name: str
    kind: str
    target: str


@dataclass(frozen=True)
class SDKReference:
    """Complete tested public SDK reference data."""

    exports: tuple[SDKExportReference, ...]
    resources: tuple[SDKResourceReference, ...]
    models: tuple[SDKModelReference, ...]
    enums: tuple[SDKEnumReference, ...]
    exceptions: tuple[SDKExceptionReference, ...]
    client_methods: tuple[SDKMethodReference, ...]


@dataclass(frozen=True)
class HTTPRequest:
    """One verified tracker request rendered as a labeled cURL block."""

    label: str
    method: str
    path: str
    query: tuple[tuple[str, str], ...] = ()
    body: str | None = None
    mutating: bool = False
    harness_headers: bool = True
    note: str = ""


@dataclass(frozen=True)
class HTTPExample:
    """Legacy single-request metadata retained while building curated matrices."""

    curl: str
    note: str = ""


def _clean_docstring(value: object) -> str:
    if not isinstance(value, str):
        return ""
    return inspect.cleandoc(value)


def _format_value(value: object) -> str:
    if value is None:
        return "None"
    if isinstance(value, bool):
        return "True" if value else "False"
    if isinstance(value, Enum):
        return f"{type(value).__name__}.{value.name}"
    if isinstance(value, str):
        return repr(value)
    if isinstance(value, Path):
        return repr(str(value))
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, list):
        items = typing.cast(list[object], value)
        return "[" + ", ".join(_format_value(item) for item in items) + "]"
    if isinstance(value, tuple):
        items = typing.cast(tuple[object, ...], value)
        suffix = "," if len(items) == 1 else ""
        return "(" + ", ".join(_format_value(item) for item in items) + suffix + ")"
    if isinstance(value, dict):
        items = typing.cast(dict[object, object], value)
        rendered = (f"{_format_value(key)}: {_format_value(item)}" for key, item in items.items())
        return "{" + ", ".join(rendered) + "}"
    if isinstance(value, type):
        return value.__name__
    return type(value).__name__


def _format_annotation(annotation: object) -> str:
    if annotation is inspect.Signature.empty or annotation is inspect.Parameter.empty:
        return "Any"
    if annotation is None or annotation is type(None):
        return "None"
    if isinstance(annotation, str):
        return annotation
    if isinstance(annotation, ForwardRef):
        return annotation.__forward_arg__
    if isinstance(annotation, typing.TypeVar):
        return annotation.__name__

    origin = get_origin(annotation)
    arguments = get_args(annotation)
    if origin is typing.Annotated:
        return _format_annotation(arguments[0])
    if origin is typing.Literal:
        return "Literal[" + ", ".join(_format_value(argument) for argument in arguments) + "]"
    if origin in {typing.Union, types.UnionType}:
        return " | ".join(_format_annotation(argument) for argument in arguments)
    if origin is not None:
        origin_name = getattr(origin, "__name__", str(origin).replace("typing.", ""))
        if arguments:
            return f"{origin_name}[{', '.join(_format_annotation(argument) for argument in arguments)}]"
        return origin_name

    name = getattr(annotation, "__name__", None)
    if isinstance(name, str):
        return name
    return str(annotation).replace("typing.", "")


def _sanitize_public_text(value: str) -> str:
    value = re.sub(
        r"(-s\s+ANTHROPIC_API_KEY)\s+[A-Za-z][A-Za-z0-9_-]+",
        r"\1 AnthropicApiKey",
        value,
    )
    return re.sub(r"\b([A-Za-z0-9._%+-]+)@vals\.ai\b", r"\1@example.com", value)


def _split_click_help(value: str) -> tuple[str, str | None]:
    match = re.search(r"\n\nExample:\s*(.+)$", value, flags=re.DOTALL)
    if match is None:
        return value.strip(), None
    summary = value[: match.start()].strip()
    example = "\n".join(line.strip() for line in match.group(1).strip().splitlines())
    return summary, example


def _format_click_type(parameter_type: click.ParamType) -> tuple[str, tuple[str, ...]]:
    constraints: list[str] = []
    if isinstance(parameter_type, click.Tuple):
        item_types = ", ".join(_format_click_type(item)[0] for item in parameter_type.types)
        return f"tuple[{item_types}]", ()
    if isinstance(parameter_type, click.Choice):
        raw_choices = typing.cast(Sequence[object], parameter_type.choices)
        choices = tuple(str(choice) for choice in raw_choices)
        constraints.append("one of " + ", ".join(f"`{choice}`" for choice in choices))
        if not parameter_type.case_sensitive:
            constraints.append("case-insensitive")
        return "choice", tuple(constraints)
    if isinstance(parameter_type, click.IntRange):
        if parameter_type.min is not None:
            constraints.append(f">= {parameter_type.min}")
        if parameter_type.max is not None:
            constraints.append(f"<= {parameter_type.max}")
        if parameter_type.clamp:
            constraints.append("clamped")
        return "integer", tuple(constraints)
    if isinstance(parameter_type, click.FloatRange):
        if parameter_type.min is not None:
            constraints.append(f">= {parameter_type.min}")
        if parameter_type.max is not None:
            constraints.append(f"<= {parameter_type.max}")
        if parameter_type.clamp:
            constraints.append("clamped")
        return "number", tuple(constraints)
    if isinstance(parameter_type, click.Path):
        if parameter_type.exists:
            constraints.append("must exist")
        if parameter_type.file_okay and not parameter_type.dir_okay:
            constraints.append("file")
        elif parameter_type.dir_okay and not parameter_type.file_okay:
            constraints.append("directory")
        if parameter_type.readable:
            constraints.append("readable")
        if parameter_type.writable:
            constraints.append("writable")
        return "path", tuple(constraints)

    stable_name = parameter_type.name.replace(" range", "")
    return stable_name, ()


def _is_click_unset(value: object) -> bool:
    return (
        isinstance(value, Enum)
        and type(value).__module__.startswith("click.")
        and type(value).__name__ == "Sentinel"
        and value.name == "UNSET"
    )


def _collect_click_parameter(parameter: click.Parameter) -> CLIParameterReference:
    parameter_type, type_constraints = _format_click_type(parameter.type)
    default = None if _is_click_unset(parameter.default) else _format_value(parameter.default)
    constraints = list(type_constraints)
    if parameter.nargs != 1:
        constraints.append(f"{parameter.nargs} values")
    if parameter.multiple:
        constraints.append("repeatable")

    if isinstance(parameter, click.Option):
        declarations = tuple((*parameter.opts, *parameter.secondary_opts))
        help_text = _sanitize_public_text(parameter.help or "")
        kind: Literal["argument", "option"] = "option"
    else:
        declarations = (parameter.human_readable_name.upper(),)
        help_text = ""
        kind = "argument"

    return CLIParameterReference(
        name=parameter.name or declarations[0].lower(),
        kind=kind,
        declarations=declarations,
        type_name=parameter_type,
        required=parameter.required,
        default=default,
        multiple=parameter.multiple,
        nargs=parameter.nargs,
        metavar=parameter.metavar,
        constraints=tuple(constraints),
        help=help_text,
    )


def collect_cli_commands() -> tuple[CLICommandReference, ...]:
    """Collect every registered leaf command without invoking Click callbacks."""
    from valkyrie.cli.main import cli

    commands: list[CLICommandReference] = []

    def visit(command: click.Command, path: tuple[str, ...]) -> None:
        if isinstance(command, click.Group):
            for name, child in command.commands.items():
                visit(child, (*path, name))
            return
        summary, example = _split_click_help(_sanitize_public_text(_clean_docstring(command.help)))
        commands.append(
            CLICommandReference(
                path=path,
                summary=summary,
                example=example,
                parameters=tuple(_collect_click_parameter(parameter) for parameter in command.params),
            )
        )

    visit(cli, ())
    return tuple(commands)


def _format_callable_parameter(parameter: inspect.Parameter) -> str:
    prefix = ""
    if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
        prefix = "*"
    elif parameter.kind is inspect.Parameter.VAR_KEYWORD:
        prefix = "**"

    result = f"{prefix}{parameter.name}"
    if parameter.annotation is not inspect.Parameter.empty:
        result += f": {_format_annotation(parameter.annotation)}"
    if parameter.default is not inspect.Parameter.empty:
        result += f" = {_format_value(parameter.default)}"
    return result


def _format_signature(name: str, callable_object: Callable[..., object], *, drop_first: bool = True) -> str:
    signature = inspect.signature(callable_object, eval_str=False)
    parameters = list(signature.parameters.values())
    if drop_first and parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]

    rendered: list[str] = []
    keyword_marker_added = False
    for index, parameter in enumerate(parameters):
        if parameter.kind is inspect.Parameter.KEYWORD_ONLY and not keyword_marker_added:
            rendered.append("*")
            keyword_marker_added = True
        rendered.append(_format_callable_parameter(parameter))
        if parameter.kind is inspect.Parameter.VAR_POSITIONAL:
            keyword_marker_added = True
        if parameter.kind is inspect.Parameter.POSITIONAL_ONLY and (
            index + 1 == len(parameters) or parameters[index + 1].kind is not inspect.Parameter.POSITIONAL_ONLY
        ):
            rendered.append("/")

    return_type = _format_annotation(signature.return_annotation)
    async_prefix = (
        "async " if inspect.iscoroutinefunction(callable_object) or inspect.isasyncgenfunction(callable_object) else ""
    )
    one_line = f"{async_prefix}def {name}({', '.join(rendered)}) -> {return_type}"
    if len(one_line) <= 110:
        return one_line

    body = "\n".join(f"    {parameter}," for parameter in rendered)
    return f"{async_prefix}def {name}(\n{body}\n) -> {return_type}"


def _collect_method(name: str, callable_object: Callable[..., object]) -> SDKMethodReference:
    signature = inspect.signature(callable_object, eval_str=False)
    parameters = list(signature.parameters.values())
    if parameters and parameters[0].name in {"self", "cls"}:
        parameters = parameters[1:]
    parameter_references = tuple(
        SDKParameterReference(
            name=parameter.name,
            kind=parameter.kind.name,
            type_name=_format_annotation(parameter.annotation),
            required=parameter.default is inspect.Parameter.empty,
            default=(None if parameter.default is inspect.Parameter.empty else _format_value(parameter.default)),
        )
        for parameter in parameters
    )
    overloads = typing.get_overloads(callable_object)
    signature_sources = overloads or (callable_object,)

    return SDKMethodReference(
        name=name,
        description=_clean_docstring(inspect.getdoc(callable_object)),
        signatures=tuple(_format_signature(name, source) for source in signature_sources),
        parameters=parameter_references,
        return_types=tuple(
            _format_annotation(inspect.signature(source, eval_str=False).return_annotation)
            for source in signature_sources
        ),
    )


def _field_constraints(metadata: Sequence[object]) -> tuple[str, ...]:
    constraints: list[str] = []
    attributes = (
        ("gt", ">"),
        ("ge", ">="),
        ("lt", "<"),
        ("le", "<="),
        ("multiple_of", "multiple of"),
        ("min_length", "minimum length"),
        ("max_length", "maximum length"),
        ("pattern", "pattern"),
    )
    for item in metadata:
        for attribute, label in attributes:
            value = getattr(item, attribute, None)
            if value is not None:
                constraints.append(f"{label} {_format_value(value)}")
    return tuple(constraints)


def _field_default(field: Any) -> str | None:
    if field.is_required():
        return None
    if field.default_factory is not None:
        factory = field.default_factory
        if factory is list:
            return "[]"
        if factory is dict:
            return "{}"
        if factory is set:
            return "set()"
        factory_name = getattr(factory, "__name__", "generated value")
        return "generated value" if factory_name == "<lambda>" else f"{factory_name}()"
    return _format_value(field.default)


def _model_family(module: str) -> str:
    return module.rsplit(".", 1)[-1].replace("_", " ").title()


def _type_slug(name: str) -> str:
    """Return an acronym-aware, path-safe slug for one public type name."""
    separated = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    separated = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", separated)
    slug = re.sub(r"[^A-Za-z0-9]+", "-", separated).strip("-").lower()
    if not slug or slug in {".", ".."} or "/" in slug or "\\" in slug:
        raise ValueError(f"Unsafe public type slug for {name!r}: {slug!r}")
    return slug


def _collect_model(model: type[BaseModel]) -> SDKModelReference:
    fields = tuple(
        SDKFieldReference(
            name=name,
            type_name=_format_annotation(field.annotation),
            required=field.is_required(),
            default=_field_default(field),
            alias=field.alias if field.alias != name else None,
            constraints=_field_constraints(field.metadata),
            description=field.description or "",
        )
        for name, field in model.model_fields.items()
    )
    return SDKModelReference(
        name=model.__name__,
        module=model.__module__,
        family=_model_family(model.__module__),
        slug=_type_slug(model.__name__),
        description=_clean_docstring(inspect.getdoc(model)),
        fields=fields,
    )


def _collect_enum(enum_class: type[Enum]) -> SDKEnumReference:
    return SDKEnumReference(
        name=enum_class.__name__,
        module=enum_class.__module__,
        family=_model_family(enum_class.__module__),
        slug=_type_slug(enum_class.__name__),
        description=_clean_docstring(inspect.getdoc(enum_class)),
        members=tuple((member.name, _format_value(member.value)) for member in enum_class),
    )


def _validate_type_paths(entries: Sequence[SDKModelReference | SDKEnumReference]) -> None:
    """Reject duplicate names, duplicate slugs, and unsafe generated paths."""
    names: set[str] = set()
    paths: set[Path] = set()
    for entry in entries:
        if entry.name in names:
            raise ValueError(f"Duplicate public type name: {entry.name}")
        names.add(entry.name)
        path = _sdk_type_path(entry)
        if path in paths:
            raise ValueError(f"Duplicate public type path: {path}")
        paths.add(path)


def _collect_exception(exception_class: type[Exception]) -> SDKExceptionReference:
    if "__init__" not in exception_class.__dict__:
        signature = "(*args: object)"
    else:
        try:
            signature = str(inspect.signature(exception_class))
        except (TypeError, ValueError):
            signature = "(*args: object)"
    parent = exception_class.__base__.__name__ if exception_class.__base__ is not None else "Exception"
    return SDKExceptionReference(
        name=exception_class.__name__,
        parent=parent,
        description=_clean_docstring(inspect.getdoc(exception_class)),
        signature=f"{exception_class.__name__}{signature}",
    )


def _collect_constructor(client_class: type[object]) -> SDKMethodReference:
    method = _collect_method("Constructor", client_class.__init__)
    signature = _format_signature(client_class.__name__, client_class.__init__)
    signature = signature.removeprefix("def ").rsplit(" -> ", 1)[0] + f" -> {client_class.__name__}"
    return SDKMethodReference(
        name=method.name,
        description=_clean_docstring(inspect.getdoc(client_class)),
        signatures=(signature,),
        parameters=method.parameters,
        return_types=(client_class.__name__,),
    )


def _resource_methods(resource_class: type[object]) -> tuple[SDKMethodReference, ...]:
    methods: list[SDKMethodReference] = []
    for name, value in resource_class.__dict__.items():
        if name.startswith("_") or not callable(value):
            continue
        methods.append(_collect_method(name, value))
    return tuple(methods)


def collect_sdk_reference() -> SDKReference:
    """Collect the tested top-level SDK exports and public resource methods."""
    import valkyrie.sdk as sdk
    from valkyrie.sdk.client import ValkyrieClient
    from valkyrie.sdk.resources import AgentsResource, BenchmarksResource, BenchmarkServicesResource, RunsResource

    resource_classes = (
        ("RunsResource", "client.runs", RunsResource),
        ("BenchmarksResource", "client.benchmarks", BenchmarksResource),
        ("AgentsResource", "client.agents", AgentsResource),
        ("BenchmarkServicesResource", "client.services", BenchmarkServicesResource),
    )
    resources = tuple(
        SDKResourceReference(
            name=name,
            client_attribute=client_attribute,
            description=_clean_docstring(inspect.getdoc(resource_class)),
            methods=_resource_methods(resource_class),
        )
        for name, client_attribute, resource_class in resource_classes
    )

    models: list[SDKModelReference] = []
    enums: list[SDKEnumReference] = []
    exceptions: list[SDKExceptionReference] = []
    exports: list[SDKExportReference] = []
    for name in sdk.__all__:
        value = getattr(sdk, name)
        if inspect.isclass(value) and issubclass(value, Enum):
            enums.append(_collect_enum(value))
            kind = "enum"
            target = f"/{_route(_sdk_type_path(enums[-1]))}"
        elif inspect.isclass(value) and issubclass(value, BaseModel):
            models.append(_collect_model(value))
            kind = "model"
            target = f"/{_route(_sdk_type_path(models[-1]))}"
        elif inspect.isclass(value) and issubclass(value, Exception):
            exceptions.append(_collect_exception(value))
            kind = "exception"
            target = f"/reference/sdk/errors#{name.lower()}"
        elif value is ValkyrieClient:
            kind = "client"
            target = "/reference/sdk/client"
        else:
            kind = "export"
            target = "/reference/sdk/index"
        exports.append(SDKExportReference(name=name, kind=kind, target=target))

    _validate_type_paths((*models, *enums))

    client_methods = (
        _collect_constructor(ValkyrieClient),
        _collect_method("from_config", ValkyrieClient.from_config.__func__),
        _collect_method("close", ValkyrieClient.close),
    )
    return SDKReference(
        exports=tuple(exports),
        resources=resources,
        models=tuple(models),
        enums=tuple(enums),
        exceptions=tuple(exceptions),
        client_methods=client_methods,
    )


def _escape_cell(value: str) -> str:
    escaped = value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("|", "\\|")
    return escaped.replace("\n", "<br />")


def _code(value: str | None) -> str:
    return "—" if value is None else f"`{_escape_cell(value)}`"


def _frontmatter(title: str, description: str) -> list[str]:
    return [
        "---",
        f"title: {json.dumps(title)}",
        f"description: {json.dumps(description)}",
        "---",
        "",
        _GENERATED_MARKER,
        "",
    ]


def _route(path: Path) -> str:
    return path.with_suffix("").as_posix()


def _cli_command_path(command: CLICommandReference) -> Path:
    return Path("reference/cli", *command.path).with_suffix(".mdx")


def _sdk_method_path(resource_page: str, method: SDKMethodReference) -> Path:
    return Path("reference/sdk", resource_page, method.name).with_suffix(".mdx")


def _sdk_type_path(entry: SDKModelReference | SDKEnumReference) -> Path:
    return Path("reference/sdk/models", entry.family.lower(), entry.slug).with_suffix(".mdx")


def _parameter_metavar(parameter: CLIParameterReference) -> str:
    if parameter.metavar:
        values = [f"<{parameter.metavar}>" for _ in range(max(parameter.nargs, 1))]
    elif parameter.kind == "argument":
        values = [f"<{parameter.declarations[0]}>" for _ in range(max(parameter.nargs, 1))]
    elif parameter.type_name.startswith("tuple["):
        item_types = parameter.type_name.removeprefix("tuple[").removesuffix("]").split(", ")
        values = [f"<{item.upper()}>" for item in item_types]
    elif parameter.type_name == "boolean":
        values = []
    else:
        values = [f"<{parameter.type_name.upper()}>" for _ in range(max(parameter.nargs, 1))]
    return " ".join(values)


def _command_usage(command: CLICommandReference) -> str:
    """Render complete non-executable Click syntax in registration order."""
    fragments: list[str] = ["valkyrie " + " ".join(command.path)]
    for parameter in command.parameters:
        metavar = _parameter_metavar(parameter)
        if parameter.kind == "argument":
            fragment = metavar
        else:
            fragment = "|".join(parameter.declarations)
            if metavar:
                fragment += f" {metavar}"
        if parameter.multiple:
            fragment += "..."
        if not parameter.required:
            fragment = f"[{fragment}]"
        fragments.append(fragment)
    if len(fragments) == 1:
        return fragments[0]
    return " \\\n  ".join(fragments)


def _curl(
    method: str,
    path: str,
    *,
    query: Sequence[tuple[str, str]] = (),
    body: str | None = None,
    mutating: bool = False,
    api_key_header: str = "X-Api-Key",
    harness_headers: bool = True,
) -> str:
    """Render a shell-valid cURL example without long URL or JSON lines."""
    lines: list[str] = []
    if mutating:
        lines.append("# Example only — review before running")
    if method == "GET" and query:
        lines.append(f'curl --get "$VALKYRIE_BASE_URL{path}" \\')
    else:
        lines.append(f'curl --request {method} "$VALKYRIE_BASE_URL{path}" \\')
    lines.append(f'  --header "{api_key_header}: $VALS_API_KEY"')
    if harness_headers:
        headers = (
            ("X-Harness-Aws-Access-Key-Id", "$AWS_ACCESS_KEY_ID"),
            ("X-Harness-Aws-Secret-Access-Key", "$AWS_SECRET_ACCESS_KEY"),
            ("X-Harness-Aws-Default-Region", "$AWS_DEFAULT_REGION"),
            ("X-Harness-S3-Bucket", "$S3_BUCKET"),
            ("X-Harness-Log-Group", "$LOG_GROUP"),
            ("X-Harness-Log-Retention-Policy", "$LOG_RETENTION_POLICY"),
        )
        for name, value in headers:
            lines[-1] += " \\"
            lines.append(f'  --header "{name}: {value}"')
    for name, value in query:
        lines[-1] += " \\"
        option = "--data-urlencode" if method == "GET" else "--url-query"
        lines.append(f'  {option} "{name}={value}"')
    if body is not None:
        pretty_body = json.dumps(json.loads(body), indent=2, ensure_ascii=False)
        lines[-1] += " \\"
        lines.append('  --header "Content-Type: application/json" \\')
        lines.append("  --data @- <<'JSON'")
        lines.extend(pretty_body.splitlines())
        lines.append("JSON")
    if harness_headers:
        lines.extend(
            (
                "# For temporary credentials, add:",
                '#   --header "X-Harness-Aws-Session-Token: $AWS_SESSION_TOKEN"',
            )
        )
    return "\n".join(lines)


def _render_http_request(request: HTTPRequest) -> tuple[str, str, str]:
    return (
        "bash",
        request.label,
        _curl(
            request.method,
            request.path,
            query=request.query,
            body=request.body,
            mutating=request.mutating,
            harness_headers=request.harness_headers,
        ),
    )


def _validate_cli_http_classification(commands: Sequence[CLICommandReference]) -> None:
    paths = {command.path for command in commands}
    classified: set[tuple[str, ...]] = set(_CLI_HTTP_PATHS | _CLI_LOCAL_PATHS)
    overlap: set[tuple[str, ...]] = set(_CLI_HTTP_PATHS & _CLI_LOCAL_PATHS)
    if paths != classified or overlap:
        missing = sorted(" ".join(path) for path in paths - classified)
        unexpected = sorted(" ".join(path) for path in classified - paths)
        raise ValueError(f"Invalid CLI HTTP classification; missing={missing}, unexpected={unexpected}")


def _cli_http_requests(path: tuple[str, ...]) -> tuple[HTTPRequest, ...]:
    service_body = '{"services":[{"name":"benchmark-name","url":"https://benchmark.example.com","auth_header_name":null,"auth_secret_name":null}]}'
    requests: dict[tuple[str, ...], tuple[HTTPRequest, ...]] = {
        ("run", "analyze"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark-metadata/$RUN_ID"),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/analyze-benchmark/$RUN_ID",
                body='{"no_cache":false,"lambda_function":null}',
                mutating=True,
            ),
        ),
        ("run", "errors"): (
            HTTPRequest(
                "HTTP primary", "GET", "/retrieve-results", query=(("benchmark_id", "$RUN_ID"), ("s3", "false"))
            ),
        ),
        ("run", "fetch"): (
            HTTPRequest("HTTP primary", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
            HTTPRequest(
                "HTTP stream",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
            HTTPRequest("HTTP JSON metadata", "GET", "/fetch-benchmark-metadata/$RUN_ID"),
        ),
        ("run", "list"): (
            HTTPRequest(
                "HTTP primary",
                "GET",
                "/fetch-benchmarks",
                query=(("agent_name", "agent-name"), ("order_by", "desc"), ("limit", "5"), ("offset", "0")),
            ),
        ),
        ("run", "outputs"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark-metadata/$RUN_ID"),
            HTTPRequest("HTTP primary", "GET", "/fetch-run-outputs/$RUN_ID", query=(("task_ids", "task-id"),)),
        ),
        ("run", "results"): (
            HTTPRequest(
                "HTTP primary",
                "GET",
                "/retrieve-results",
                query=(("benchmark_id", "$RUN_ID"), ("s3", "false"), ("task_ids", "task-id")),
            ),
            HTTPRequest(
                "HTTP S3 prerequisite",
                "GET",
                "/check-results-exist",
                query=(("benchmark_id", "$RUN_ID"),),
                mutating=True,
                note="Only `--s3` performs this overwrite check; local result-file writes are not HTTP operations.",
            ),
            HTTPRequest(
                "HTTP S3 conditional",
                "GET",
                "/retrieve-results",
                query=(("benchmark_id", "$RUN_ID"), ("s3", "true"), ("task_ids", "task-id")),
                mutating=True,
            ),
        ),
        ("run", "resume"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
            HTTPRequest(
                "HTTP update-agent metadata",
                "GET",
                "/fetch-benchmark-metadata/$RUN_ID",
                mutating=True,
                note="`--update-agent` then refreshes the agent through direct S3 helpers; that local/S3 step is not tracker HTTP.",
            ),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/retry-or-resume-benchmark/$RUN_ID",
                query=(("retry", "false"), ("retry_mode", "auto"), ("concurrency", "5")),
                body='{"task_ids":[],"service_headers":{},"secrets":{}}',
                mutating=True,
            ),
            HTTPRequest(
                "HTTP connect initial status",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"),),
            ),
            HTTPRequest(
                "HTTP connect stream",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
        ),
        ("run", "retry"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
            HTTPRequest(
                "HTTP update-agent metadata",
                "GET",
                "/fetch-benchmark-metadata/$RUN_ID",
                mutating=True,
                note="`--update-agent` then refreshes the agent through direct S3 helpers; that local/S3 step is not tracker HTTP.",
            ),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/retry-or-resume-benchmark/$RUN_ID",
                query=(("retry", "true"), ("retry_mode", "auto"), ("concurrency", "5")),
                body='{"task_ids":[],"service_headers":{},"secrets":{}}',
                mutating=True,
            ),
            HTTPRequest(
                "HTTP connect initial status",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"),),
            ),
            HTTPRequest(
                "HTTP connect stream",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
        ),
        ("run", "start"): (
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/start-benchmark",
                body='{"contract":{"name":"agent-name","model":"model-name","install_cmd":"","run_cmd":"","final_output":null,"output_artifacts":[],"egress_allowlist":[],"secrets":{},"kwargs":{}},"benchmark_name":"benchmark-name","concurrency":5,"label":null,"task_ids":null,"slice_str":null,"lambda_function":null,"dataset":"default","harness_config":{"aws":{"aws_access_key_id":"literal-placeholder","aws_secret_access_key":"literal-placeholder","aws_default_region":"literal-placeholder","aws_session_token":null},"s3_bucket":"bucket-name","log_group":"log-group","log_retention_policy":30,"sandbox_provider_secret_name":"provider-secret-name"},"custom_benchmark_service":null,"service_headers":{},"sandbox_provider":"daytona","sandbox_provider_secret_name":null,"service_auth_header_name":null,"service_auth_secret_name":null,"webhook_secret_name":null,"webhook_intervals":null}',
                mutating=True,
                note="JSON values are literal templates. `--count` repeats this request.",
            ),
            HTTPRequest(
                "HTTP connect initial status",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"),),
            ),
            HTTPRequest(
                "HTTP connect stream",
                "GET",
                "/fetch-benchmark",
                query=(("benchmark_id", "$RUN_ID"), ("connect", "true")),
            ),
        ),
        ("run", "status"): (HTTPRequest("HTTP primary", "GET", "/benchmarks/status", query=(("ids", "$RUN_ID"),)),),
        ("run", "stop"): (
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/stop-benchmark/$RUN_ID",
                query=(("force", "false"),),
                body='{"task_ids":null}',
                mutating=True,
            ),
        ),
        ("run", "update"): (
            HTTPRequest(
                "HTTP primary", "PATCH", "/benchmarks/$RUN_ID/concurrency", body='{"concurrency":5}', mutating=True
            ),
        ),
        ("benchmark", "tasks"): (
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/fetch-benchmark-tasks",
                body='{"benchmark_name":"benchmark-name","dataset":"default","custom_benchmark_service":null,"service_headers":{}}',
            ),
        ),
        ("config", "init"): (
            HTTPRequest(
                "HTTP hosted mode",
                "POST",
                "/init",
                mutating=True,
                harness_headers=False,
                note="Hosted setup validates the API key with this request. Self-hosted setup does not call Tracker.",
            ),
        ),
        ("config", "service", "list"): (
            HTTPRequest("HTTP catalog", "GET", "/benchmark-services"),
            HTTPRequest(
                "HTTP health check",
                "POST",
                "/benchmark-services",
                body=service_body,
                note="The CLI sends this request only when the merged hosted/custom catalog contains services.",
            ),
        ),
    }
    return requests.get(path, ())


def _sdk_http_requests(resource: str, method: str) -> tuple[HTTPRequest, ...]:
    start_body = '{"contract":{"name":"agent-name","model":null,"install_cmd":"","run_cmd":"","final_output":null,"output_artifacts":[],"egress_allowlist":[],"secrets":{},"kwargs":{}},"benchmark_name":"benchmark-name","concurrency":5,"label":null,"task_ids":null,"slice_str":null,"lambda_function":null,"dataset":"default","harness_config":{"aws":{"aws_access_key_id":"literal-placeholder","aws_secret_access_key":"literal-placeholder","aws_default_region":"literal-placeholder","aws_session_token":null},"s3_bucket":"bucket-name","log_group":"log-group","log_retention_policy":30,"sandbox_provider_secret_name":"provider-secret-name"},"custom_benchmark_service":null,"service_headers":{},"sandbox_provider":"daytona","sandbox_provider_secret_name":null,"service_auth_header_name":null,"service_auth_secret_name":null,"webhook_secret_name":null,"webhook_intervals":null}'
    service_body = '{"services":[{"name":"benchmark-name","url":"https://benchmark.example.com","auth_header_name":null,"auth_secret_name":null}]}'
    requests: dict[tuple[str, str], tuple[HTTPRequest, ...]] = {
        ("RunsResource", "start"): (
            HTTPRequest(
                "HTTP",
                "POST",
                "/start-benchmark",
                body=start_body,
                mutating=True,
                note="JSON values are literal templates; single-quoted JSON does not expand shell variables.",
            ),
        ),
        ("RunsResource", "fetch"): (
            HTTPRequest("HTTP", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
        ),
        ("RunsResource", "list"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/fetch-benchmarks",
                query=(("order_by", "desc"), ("limit", "50"), ("offset", "0")),
            ),
        ),
        ("RunsResource", "stream"): (
            HTTPRequest("HTTP", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"), ("connect", "true"))),
        ),
        ("RunsResource", "results"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/retrieve-results",
                query=(("benchmark_id", "$RUN_ID"), ("s3", "false"), ("task_ids", "task-id")),
            ),
        ),
        ("RunsResource", "metadata"): (HTTPRequest("HTTP", "GET", "/fetch-benchmark-metadata/$RUN_ID"),),
        ("RunsResource", "results_exist"): (
            HTTPRequest("HTTP", "GET", "/check-results-exist", query=(("benchmark_id", "$RUN_ID"),)),
        ),
        ("RunsResource", "analyze"): (
            HTTPRequest(
                "HTTP",
                "POST",
                "/analyze-benchmark/$RUN_ID",
                body='{"no_cache":false,"lambda_function":null}',
                mutating=True,
            ),
        ),
        ("RunsResource", "stream_outputs"): (
            HTTPRequest("HTTP", "GET", "/fetch-run-outputs/$RUN_ID", query=(("task_ids", "task-id"),)),
        ),
        ("RunsResource", "stop"): (
            HTTPRequest(
                "HTTP no task selection", "POST", "/stop-benchmark/$RUN_ID", query=(("force", "false"),), mutating=True
            ),
            HTTPRequest(
                "HTTP selected tasks",
                "POST",
                "/stop-benchmark/$RUN_ID",
                query=(("force", "false"),),
                body='{"task_ids":["task-id"]}',
                mutating=True,
            ),
        ),
        ("RunsResource", "resume"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/retry-or-resume-benchmark/$RUN_ID",
                query=(("retry", "false"), ("retry_mode", "auto")),
                body='{"task_ids":[],"service_headers":{},"secrets":{}}',
                mutating=True,
            ),
        ),
        ("RunsResource", "retry"): (
            HTTPRequest("HTTP prerequisite", "GET", "/fetch-benchmark", query=(("benchmark_id", "$RUN_ID"),)),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/retry-or-resume-benchmark/$RUN_ID",
                query=(("retry", "true"), ("retry_mode", "auto")),
                body='{"task_ids":[],"service_headers":{},"secrets":{}}',
                mutating=True,
            ),
        ),
        ("BenchmarksResource", "fetch"): (HTTPRequest("HTTP", "GET", "/benchmarks/$RUN_ID"),),
        ("BenchmarksResource", "statuses"): (
            HTTPRequest("HTTP", "GET", "/benchmarks/status", query=(("ids", "$RUN_ID"),)),
        ),
        ("BenchmarksResource", "tasks"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/benchmarks/$RUN_ID/tasks",
                query=(("status", "ERROR,FINISHED"), ("limit", "25"), ("offset", "0")),
            ),
        ),
        ("BenchmarksResource", "task"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/benchmarks/$RUN_ID/tasks/task%20one",
                note="Raw cURL callers must URL-encode the task-id path segment; the SDK does this automatically.",
            ),
        ),
        ("BenchmarksResource", "artifacts"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/benchmarks/$RUN_ID/tasks/task%20one/artifacts",
                note="Raw cURL callers must URL-encode the task-id path segment; the SDK does this automatically.",
            ),
        ),
        ("AgentsResource", "list"): (HTTPRequest("HTTP", "GET", "/agents"),),
        ("AgentsResource", "download_url"): (
            HTTPRequest(
                "HTTP",
                "GET",
                "/agents/agent%20one/download-url",
                note="Raw cURL callers must URL-encode the agent-name path segment; the SDK does this automatically.",
            ),
        ),
        ("BenchmarkServicesResource", "catalog"): (HTTPRequest("HTTP", "GET", "/benchmark-services"),),
        ("BenchmarkServicesResource", "list"): (
            HTTPRequest("HTTP catalog prerequisite", "GET", "/benchmark-services"),
            HTTPRequest(
                "HTTP primary",
                "POST",
                "/benchmark-services",
                body=service_body,
                note="The SDK omits the POST when the catalog is empty.",
            ),
        ),
        ("BenchmarkServicesResource", "task_ids"): (
            HTTPRequest(
                "HTTP",
                "POST",
                "/fetch-benchmark-tasks",
                body='{"benchmark_name":"benchmark-name","dataset":"default","custom_benchmark_service":null,"service_headers":{}}',
            ),
        ),
    }
    return requests[(resource, method)]


def _render_http_metadata(requests: Sequence[HTTPRequest]) -> tuple[list[tuple[str, str, str]], list[str]]:
    blocks = [_render_http_request(request) for request in requests]
    notes = [
        f"**{request.label}:** "
        + request.note.replace(
            "single-quoted JSON does not expand shell variables",
            "a quoted JSON heredoc does not expand shell variables",
        )
        for request in requests
        if request.note
    ]
    return blocks, notes


def _render_panel(blocks: Sequence[tuple[str, str, str]]) -> list[str]:
    lines = ["<Panel>"]
    if len(blocks) > 1:
        lines.extend(("<CodeGroup>", ""))
    for language, title, content in blocks:
        lines.extend((f"```{language} {title}", content, "```", ""))
    if len(blocks) > 1:
        lines.extend(("</CodeGroup>",))
    lines.extend(("</Panel>", ""))
    return lines


def _escape_html(value: str) -> str:
    return html.escape(value, quote=False).replace("\n", "<br />")


def _render_parameter_row(
    name: str,
    type_name: str,
    *,
    required: bool,
    default: str | None,
    constraints: Sequence[str] = (),
    description: str = "",
    type_markup: bool = False,
    alias: str | None = None,
) -> list[str]:
    rendered_type = type_name if type_markup else f"<code>{_escape_html(type_name)}</code>"
    metadata = ["required" if required else "optional", rendered_type]
    if alias is not None:
        metadata.append(f"alias: <code>{_escape_html(alias)}</code>")
    if default is not None:
        metadata.append(f"default: <code>{_escape_html(default)}</code>")
    if constraints:
        metadata.append("constraints: " + _escape_html("; ".join(constraints)))

    lines = [
        '<div className="border-b border-gray-200 py-3 dark:border-gray-800">',
        '  <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">'
        f'<span className="break-all font-mono text-sm">{_escape_html(name)}</span>'
        f'<span className="min-w-0 break-words text-sm text-gray-500 dark:text-gray-400">'
        f"{' · '.join(metadata)}</span></div>",
    ]
    if description:
        lines.append(f'  <p className="mb-0 mt-1">{_escape_html(description)}</p>')
    lines.extend(("</div>", ""))
    return lines


def _render_cli_parameter_table(parameters: Sequence[CLIParameterReference], kind: str) -> list[str]:
    selected = [parameter for parameter in parameters if parameter.kind == kind]
    if not selected:
        return []
    title = "Arguments" if kind == "argument" else "Options"
    lines = [f"## {title}", ""]
    for parameter in selected:
        lines.extend(
            _render_parameter_row(
                ", ".join(parameter.declarations),
                parameter.type_name,
                required=parameter.required,
                default=parameter.default,
                constraints=parameter.constraints,
                description=parameter.help,
            )
        )
    return lines


def _format_cli_example(command: CLICommandReference, example: str) -> str:
    """Put each concrete argument or option group on its own shell line."""
    comments = [line for line in example.splitlines() if line.startswith("#")]
    command_line = next((line for line in example.splitlines() if line and not line.startswith("#")), "")
    tokens = command_line.split()
    prefix_length = 1 + len(command.path)
    if len(tokens) <= prefix_length:
        return example

    option_by_declaration = {
        declaration: parameter
        for parameter in command.parameters
        if parameter.kind == "option"
        for declaration in parameter.declarations
    }
    groups: list[list[str]] = []
    index = prefix_length
    while index < len(tokens):
        token = tokens[index]
        parameter = option_by_declaration.get(token)
        value_count = max(parameter.nargs, 1) if parameter is not None and parameter.type_name != "boolean" else 0
        group = tokens[index : index + 1 + value_count]
        groups.append(group)
        index += len(group)

    if len(groups) <= 1:
        return example
    lines = [*comments, " ".join(tokens[:prefix_length]) + " \\"]
    for position, group in enumerate(groups):
        continuation = " \\" if position < len(groups) - 1 else ""
        lines.append("  " + " ".join(group) + continuation)
    return "\n".join(lines)


def _render_cli_page(command: CLICommandReference) -> str:
    command_name = "valkyrie " + " ".join(command.path)
    description = command.summary or f"Reference for {command_name}."
    lines = _frontmatter(command_name, description)
    lines.extend((description, ""))
    panel_blocks = [("bash", "Syntax", _command_usage(command))]
    if command.example is not None:
        example = command.example
        if command.path == ("run", "stop"):
            example = "valkyrie run stop $RUN_ID"
        elif command.path == ("config", "auth", "set"):
            example = "valkyrie config auth set benchmark-name $BENCHMARK_CREDENTIAL"
        if command.path in _CLI_MUTATING_PATHS:
            example = "# Example only — review before running\n" + example
        panel_blocks.append(("bash", "Example", _format_cli_example(command, example)))
    http_blocks, http_notes = _render_http_metadata(_cli_http_requests(command.path))
    panel_blocks.extend(http_blocks)
    lines.extend(_render_panel(panel_blocks))
    for note in http_notes:
        lines.extend((note, ""))
    if command.path == ("run", "retry"):
        lines.extend(
            (
                "`retry` is a separate command alias for the retry mode of `run resume`; it retains the shared options.",
                "",
            )
        )
    lines.extend(_render_cli_parameter_table(command.parameters, "argument"))
    lines.extend(_render_cli_parameter_table(command.parameters, "option"))
    lines.extend((f"For task guidance, see [{command.path[0].title()} guides]({_GUIDE_LINKS[command.path[0]]}).", ""))
    return "\n".join(lines).rstrip() + "\n"


def _render_cli_index(commands: Sequence[CLICommandReference]) -> str:
    lines = _frontmatter("CLI reference", "Complete generated reference for every Valkyrie CLI command.")
    lines.extend(
        (
            "This reference is generated from the registered Click command tree. Use the task guides for complete workflows and examples.",
            "",
            "## Command groups",
            "",
            "| Group | Commands | Reference |",
            "| --- | ---: | --- |",
        )
    )
    groups: OrderedDict[str, list[CLICommandReference]] = OrderedDict()
    for command in commands:
        groups.setdefault(command.path[0], []).append(command)
    for group, group_commands in groups.items():
        first_route = _route(_cli_command_path(group_commands[0]))
        lines.append(f"| `{group}` | {len(group_commands)} | [Open](/{first_route}) |")
    lines.extend(("", "## Complete command tree", "", "```text", "valkyrie"))
    for group, group_commands in groups.items():
        lines.append(f"  {group}")
        for command in group_commands:
            lines.append("    " + " ".join(command.path[1:]))
    lines.extend(("```", "", f"Format version: `{_FORMAT_VERSION}`", ""))
    return "\n".join(lines)


def _cli_navigation(commands: Sequence[CLICommandReference]) -> list[object]:
    navigation: list[object] = [_route(_CLI_INDEX_PATH)]
    groups: OrderedDict[str, list[CLICommandReference]] = OrderedDict()
    for command in commands:
        groups.setdefault(command.path[0], []).append(command)
    for group, group_commands in groups.items():
        pages: list[object] = []
        nested: OrderedDict[str, list[str]] = OrderedDict()
        for command in group_commands:
            route = _route(_cli_command_path(command))
            if len(command.path) == 2:
                pages.append(route)
                continue
            subgroup = command.path[1]
            if subgroup not in nested:
                nested[subgroup] = []
                pages.append({"group": subgroup.title(), "pages": nested[subgroup]})
            nested[subgroup].append(route)
        navigation.append({"group": group.title(), "pages": pages})
    return navigation


def _public_type_routes(reference: SDKReference) -> dict[str, str]:
    return {entry.name: f"/{_route(_sdk_type_path(entry))}" for entry in (*reference.models, *reference.enums)}


def _link_public_types(value: str, type_routes: dict[str, str]) -> str:
    """Link exact public type tokens while preserving containers and unions."""
    parts = re.split(r"([A-Za-z_][A-Za-z0-9_]*)", value)
    rendered: list[str] = []
    for part in parts:
        if part in type_routes:
            rendered.append(f'<a href="{type_routes[part]}"><code>{part}</code></a>')
        else:
            rendered.append(_escape_html(part))
    return "".join(rendered)


def _render_sdk_parameter_table(
    parameters: Sequence[SDKParameterReference],
    *,
    heading_level: int = 2,
    type_routes: dict[str, str] | None = None,
) -> list[str]:
    if not parameters:
        return []
    lines = [f"{'#' * heading_level} Parameters", ""]
    for parameter in parameters:
        lines.extend(
            _render_parameter_row(
                parameter.name,
                _link_public_types(parameter.type_name, type_routes or {}),
                required=parameter.required,
                default=parameter.default,
                type_markup=True,
            )
        )
    return lines


def _render_returns(
    method: SDKMethodReference,
    *,
    heading_level: int = 2,
    type_routes: dict[str, str] | None = None,
) -> list[str]:
    lines = [f"{'#' * heading_level} Returns", ""]
    if len(method.return_types) == 1:
        lines.extend((_link_public_types(method.return_types[0], type_routes or {}), ""))
        return lines
    lines.extend(
        ("The selected overload determines the return type.", "", "| Overload | Return type |", "| ---: | --- |")
    )
    for index, return_type in enumerate(method.return_types, start=1):
        lines.append(f"| {index} | {_link_public_types(return_type, type_routes or {})} |")
    return [*lines, ""]


def _render_sdk_method_page(
    reference: SDKReference,
    resource: SDKResourceReference,
    page: str,
    method: SDKMethodReference,
) -> str:
    title = f"{resource.client_attribute}.{method.name}"
    description = method.description or f"Reference for {title}."
    lines = _frontmatter(title, description)
    lines.extend((description, ""))
    signature_blocks = [
        ("python", "Signature" if len(method.signatures) == 1 else f"Overload {index}", signature)
        for index, signature in enumerate(method.signatures, start=1)
    ]
    http_blocks, http_notes = _render_http_metadata(_sdk_http_requests(resource.name, method.name))
    signature_blocks.extend(http_blocks)
    lines.extend(_render_panel(signature_blocks))
    for note in http_notes:
        lines.extend((note, ""))
    type_routes = _public_type_routes(reference)
    lines.extend(_render_sdk_parameter_table(method.parameters, type_routes=type_routes))
    lines.extend(_render_returns(method, type_routes=type_routes))
    guide = "/sdk/runs" if page == "runs" else "/sdk/resources"
    lines.extend((f"For examples, see the [Python SDK guide]({guide}).", ""))
    return "\n".join(lines).rstrip() + "\n"


def _render_sdk_index(reference: SDKReference) -> str:
    lines = _frontmatter("Python SDK reference", "Complete generated reference for the public Valkyrie Python SDK.")
    lines.extend(
        (
            "This reference follows the tested `valkyrie.sdk` public contract. Internal wire models and transport helpers are excluded.",
            "",
            "## Client",
            "",
            "Use [`ValkyrieClient`](/reference/sdk/client) to configure the async client and access resource namespaces.",
            "",
            "## Resource namespaces",
            "",
            "| Attribute | Resource | Reference |",
            "| --- | --- | --- |",
        )
    )
    for resource in reference.resources:
        page = _RESOURCE_PAGES[resource.name]
        first_method = resource.methods[0]
        route = _route(_sdk_method_path(page, first_method))
        lines.append(f"| `{resource.client_attribute}` | `{resource.name}` | [Open](/{route}) |")
    lines.extend(("", "## Public exports", "", "| Name | Kind | Reference |", "| --- | --- | --- |"))
    for export in reference.exports:
        lines.append(f"| `{export.name}` | {export.kind} | [Open]({export.target}) |")
    lines.extend(("", f"Format version: `{_FORMAT_VERSION}`", ""))
    return "\n".join(lines)


def _render_sdk_client(reference: SDKReference) -> str:
    lines = _frontmatter("ValkyrieClient", "Construct and close the async Valkyrie SDK client.")
    lines.extend(
        (
            "`ValkyrieClient` owns the async HTTP connection pool and exposes the public resource namespaces.",
            "",
        )
    )
    blocks = [("python", method.name, method.signatures[0]) for method in reference.client_methods]
    lines.extend(_render_panel(blocks))
    for method in reference.client_methods:
        lines.extend((f"## {method.name}", "", method.description, ""))
        type_routes = _public_type_routes(reference)
        lines.extend(_render_sdk_parameter_table(method.parameters, heading_level=3, type_routes=type_routes))
        lines.extend(_render_returns(method, heading_level=3, type_routes=type_routes))
    lines.extend(
        (
            "## Async context manager",
            "",
            "The client closes its connection pool when an `async with` block exits.",
            "",
            "```python",
            "async with ValkyrieClient(config) as client:",
            '    run = await client.runs.start(agent="sweagent", benchmark="swebench")',
            "```",
            "",
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def _sdk_navigation(reference: SDKReference) -> list[object]:
    navigation: list[object] = [_route(_SDK_INDEX_PATH), _route(_SDK_CLIENT_PATH)]
    for resource in reference.resources:
        page = _RESOURCE_PAGES[resource.name]
        navigation.append(
            {
                "group": resource.name,
                "pages": [_route(_sdk_method_path(page, method)) for method in resource.methods],
            }
        )
    type_entries = _ordered_type_entries(reference)
    type_groups: list[object] = [_route(_SDK_TYPES_INDEX_PATH)]
    for family in ("Agents", "Runs", "Benchmarks", "Services", "Config"):
        pages = [_route(_sdk_type_path(entry)) for entry in type_entries if entry.family == family]
        type_groups.append({"group": family, "pages": pages})
    navigation.append(
        {
            "group": "Types",
            "pages": [
                {"group": "Models", "pages": type_groups},
                _route(_SDK_ERRORS_PATH),
            ],
        }
    )
    return navigation


def _ordered_type_entries(reference: SDKReference) -> tuple[SDKModelReference | SDKEnumReference, ...]:
    by_name = {entry.name: entry for entry in (*reference.models, *reference.enums)}
    return tuple(by_name[export.name] for export in reference.exports if export.name in by_name)


def _render_types_index(reference: SDKReference) -> str:
    lines = _frontmatter("Python SDK types", "Public models and enums exported by the Valkyrie Python SDK.")
    lines.extend(("Only types exported from `valkyrie.sdk` appear here.", ""))
    entries = _ordered_type_entries(reference)
    for family in ("Agents", "Runs", "Benchmarks", "Services", "Config"):
        family_entries = [entry for entry in entries if entry.family == family]
        lines.extend((f"## {family}", ""))
        for entry in family_entries:
            lines.extend((f"- [`{entry.name}`](/{_route(_sdk_type_path(entry))}) — {entry.description}",))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _render_type_page(reference: SDKReference, entry: SDKModelReference | SDKEnumReference) -> str:
    kind = "enum" if isinstance(entry, SDKEnumReference) else "model"
    lines = _frontmatter(entry.name, entry.description or f"Public SDK {kind} {entry.name}.")
    lines.extend((entry.description, ""))
    if isinstance(entry, SDKEnumReference):
        lines.extend(("## Members", ""))
        for name, value in entry.members:
            lines.extend(
                (
                    '<div className="border-b border-gray-200 py-3 dark:border-gray-800">',
                    '  <div className="flex min-w-0 flex-wrap items-baseline gap-x-2 gap-y-1">'
                    f'<span className="break-all font-mono text-sm">{_escape_html(name)}</span>'
                    f'<span className="text-sm text-gray-500 dark:text-gray-400">'
                    f"<code>{_escape_html(value)}</code></span></div>",
                    "</div>",
                    "",
                )
            )
        return "\n".join(lines).rstrip() + "\n"

    type_routes = _public_type_routes(reference)
    lines.extend(("## Fields", ""))
    for field in entry.fields:
        lines.extend(
            _render_parameter_row(
                field.name,
                _link_public_types(field.type_name, type_routes),
                required=field.required,
                default=field.default,
                alias=field.alias,
                constraints=field.constraints,
                description=field.description,
                type_markup=True,
            )
        )
    return "\n".join(lines).rstrip() + "\n"


def _render_errors(reference: SDKReference) -> str:
    lines = _frontmatter("Python SDK errors", "Generated exception hierarchy for the public Valkyrie SDK.")
    lines.extend(
        (
            "Catch `ValkyrieSDKError` to handle every SDK-defined failure, or catch a specific subclass.",
            "",
            "| Exception | Parent | Constructor | Description |",
            "| --- | --- | --- | --- |",
        )
    )
    for error in reference.exceptions:
        lines.append(
            f"| `{error.name}` | `{error.parent}` | {_code(error.signature)} | {_escape_cell(error.description)} |"
        )
    lines.append("")
    for error in reference.exceptions:
        lines.extend((f"## `{error.name}`", "", error.description, "", "```python", error.signature, "```", ""))
    return "\n".join(lines)


def _render_json(value: object) -> str:
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def render_reference() -> OrderedDict[Path, str]:
    """Render the code-derived generated manifest in deterministic order."""
    commands = collect_cli_commands()
    _validate_cli_http_classification(commands)
    sdk_reference = collect_sdk_reference()
    rendered: OrderedDict[Path, str] = OrderedDict()
    rendered[_CLI_INDEX_PATH] = _render_cli_index(commands).rstrip() + "\n"
    rendered[_CLI_NAVIGATION_PATH] = _render_json(_cli_navigation(commands))
    for command in commands:
        rendered[_cli_command_path(command)] = _render_cli_page(command)

    rendered[_SDK_INDEX_PATH] = _render_sdk_index(sdk_reference).rstrip() + "\n"
    rendered[_SDK_CLIENT_PATH] = _render_sdk_client(sdk_reference)
    rendered[_SDK_NAVIGATION_PATH] = _render_json(_sdk_navigation(sdk_reference))
    for resource in sdk_reference.resources:
        page = _RESOURCE_PAGES[resource.name]
        for method in resource.methods:
            rendered[_sdk_method_path(page, method)] = _render_sdk_method_page(sdk_reference, resource, page, method)
    rendered[_SDK_TYPES_INDEX_PATH] = _render_types_index(sdk_reference)
    for entry in _ordered_type_entries(sdk_reference):
        rendered[_sdk_type_path(entry)] = _render_type_page(sdk_reference, entry)
    rendered[_SDK_ERRORS_PATH] = _render_errors(sdk_reference).rstrip() + "\n"
    return rendered


def _obsolete_generated_files(docs_root: Path, expected: set[Path]) -> tuple[Path, ...]:
    reference_root = docs_root / "reference"
    if not reference_root.exists():
        return ()
    obsolete: list[Path] = []
    for path in reference_root.rglob("*.mdx"):
        relative_path = path.relative_to(docs_root)
        if relative_path in expected:
            continue
        if _GENERATED_MARKER in path.read_text(encoding="utf-8"):
            obsolete.append(relative_path)
    return tuple(sorted(obsolete))


def write_reference(docs_root: Path = _DOCS_ROOT) -> tuple[Path, ...]:
    """Write the manifest and remove only obsolete files bearing the generated marker."""
    rendered = render_reference()
    for relative_path in rendered:
        output_path = docs_root / relative_path
        if output_path.suffix == ".mdx" and output_path.exists():
            existing = output_path.read_text(encoding="utf-8")
            if _GENERATED_MARKER not in existing:
                raise FileExistsError(f"Refusing to overwrite unmarked file: {relative_path}")

    obsolete = _obsolete_generated_files(docs_root, set(rendered))
    for relative_path in obsolete:
        (docs_root / relative_path).unlink()

    for relative_path, content in rendered.items():
        output_path = docs_root / relative_path
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8", newline="\n")
    return obsolete


def check_reference(docs_root: Path = _DOCS_ROOT) -> tuple[str, ...]:
    """Return diagnostics for missing, stale, or unexpected generated files."""
    rendered = render_reference()
    diagnostics: list[str] = []
    for relative_path, expected in rendered.items():
        output_path = docs_root / relative_path
        if not output_path.exists():
            diagnostics.append(f"missing: {relative_path}")
            continue
        actual = output_path.read_text(encoding="utf-8")
        if actual == expected:
            continue
        diagnostics.append(f"stale: {relative_path}")
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=str(relative_path),
            tofile=f"generated/{relative_path}",
            lineterm="",
        )
        diagnostics.extend(list(diff)[:_MAX_DIFF_LINES])
    diagnostics.extend(
        f"unexpected generated file: {path}" for path in _obsolete_generated_files(docs_root, set(rendered))
    )
    return tuple(diagnostics)


def main(argv: Sequence[str] | None = None) -> int:
    """Generate reference pages or check that committed output is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing them")
    arguments = parser.parse_args(argv)

    if arguments.check:
        diagnostics = check_reference()
        if diagnostics:
            print("Generated documentation reference is stale:")
            for diagnostic in diagnostics:
                print(diagnostic)
            print("Run `make docs-reference` and commit the generated files.")
            return 1
        print("Generated documentation reference is current.")
        return 0

    obsolete = write_reference()
    print(f"Generated {len(render_reference())} documentation reference files.")
    if obsolete:
        print(f"Removed {len(obsolete)} obsolete generated files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
