FROM python:3.12-slim

# https://docs.astral.sh/uv/guides/integration/docker/#installing-uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONPATH=/app

# Copy over project dependencies from `src/` 
# NOTE: Ideally this is just what we need to start the daytona environment (Not everything)
COPY src/ ./src/

COPY submodules/ ./submodules/

# Copy over project pyproject.toml file and install dependencies
COPY pyproject.toml ./pyproject.toml
COPY README.md ./README.md
RUN uv sync --group dev