"""Shared records and paths for generated reference documentation."""

from __future__ import annotations

from pathlib import Path
from typing import Literal, NamedTuple

ROOT = Path(__file__).resolve().parents[2]
DOCS_ROOT = ROOT / "docs"
GENERATED_MARKER = "{/* Generated by scripts/generate_reference.py; do not edit. */}"

REFERENCE_ROOT = Path("reference")
CLI_ROOT = REFERENCE_ROOT / "cli"
SDK_ROOT = REFERENCE_ROOT / "sdk"
TYPE_ROOT = SDK_ROOT / "models"

CLI_INDEX = CLI_ROOT / "index.mdx"
CLI_NAVIGATION = CLI_ROOT / "navigation.json"
REDIRECTS = REFERENCE_ROOT / "redirects.json"
SDK_INDEX = SDK_ROOT / "index.mdx"
SDK_CLIENT = SDK_ROOT / "client.mdx"
SDK_NAVIGATION = SDK_ROOT / "navigation.json"
TYPE_INDEX = TYPE_ROOT / "index.mdx"
SDK_ERRORS = SDK_ROOT / "errors.mdx"

STATIC_REDIRECTS = [
    {"source": "/introduction", "destination": "/get-started/overview"},
]

GUIDE_LINKS = {
    "run": "/runs/start",
    "agent": "/agents/manage-agents",
    "benchmark": "/benchmarks/custom-services",
    "config": "/get-started/configuration",
}

CLI_CARDS = {
    "run": ("play", "starting, monitoring, managing, and retrieving runs"),
    "agent": ("package", "installing, uploading, listing, downloading, and removing agent bundles"),
    "benchmark": ("flask-conical", "exporting the task IDs in a benchmark dataset"),
    "config": ("sliders-horizontal", "credentials, sandbox providers, and benchmark services"),
}

RESOURCE_CARDS = {
    "RunsResource": ("Runs", "play", "starting, inspecting, streaming, controlling, and retrying runs"),
    "BenchmarksResource": ("Benchmarks", "flask-conical", "retrieving benchmark status, tasks, and artifacts"),
    "AgentsResource": ("Agents", "package", "listing agents and retrieving bundle download URLs"),
    "BenchmarkServicesResource": (
        "Benchmark services",
        "server",
        "discovering service catalogs, deployments, and task IDs",
    ),
}

TYPE_CARDS = {
    "Agents": ("package", "uploaded agent bundles and download URLs"),
    "Runs": ("play", "run requests, responses, and lifecycle enums"),
    "Benchmarks": ("flask-conical", "benchmark, task, artifact, and status responses"),
    "Services": ("server", "benchmark service catalog and health responses"),
    "Config": ("sliders-horizontal", "validated SDK configuration and field aliases"),
}

READ_ONLY_COMMANDS = frozenset(
    {
        ("agent", "list"),
        ("benchmark", "tasks"),
        ("config", "auth", "list"),
        ("config", "provider", "list"),
        ("config", "service", "list"),
        ("run", "errors"),
        ("run", "fetch"),
        ("run", "list"),
        ("run", "output"),
        ("run", "outputs"),
        ("run", "results"),
        ("run", "status"),
    }
)


class CLIParameterReference(NamedTuple):
    name: str
    kind: Literal["argument", "option"]
    declarations: tuple[str, ...]
    type_name: str
    required: bool
    default: str | None
    multiple: bool
    nargs: int
    metavar: str | None
    constraints: tuple[str, ...]
    help: str


class CLICommandReference(NamedTuple):
    path: tuple[str, ...]
    summary: str
    example: str | None
    parameters: tuple[CLIParameterReference, ...]


class SDKParameterReference(NamedTuple):
    name: str
    type_name: str
    required: bool
    default: str | None


class SDKMethodReference(NamedTuple):
    name: str
    description: str
    signatures: tuple[str, ...]
    parameters: tuple[SDKParameterReference, ...]
    return_types: tuple[str, ...]


class SDKResourceReference(NamedTuple):
    name: str
    client_attribute: str
    description: str
    methods: tuple[SDKMethodReference, ...]


class SDKFieldReference(NamedTuple):
    name: str
    type_name: str
    required: bool
    default: str | None
    alias: str | None
    constraints: tuple[str, ...]
    description: str


class SDKModelReference(NamedTuple):
    name: str
    family: str
    slug: str
    description: str
    fields: tuple[SDKFieldReference, ...]


class SDKEnumReference(NamedTuple):
    name: str
    family: str
    slug: str
    description: str
    members: tuple[tuple[str, str], ...]


class SDKExceptionReference(NamedTuple):
    name: str
    parent: str
    description: str
    signature: str


class SDKReference(NamedTuple):
    exports: tuple[str, ...]
    resources: tuple[SDKResourceReference, ...]
    models: tuple[SDKModelReference, ...]
    enums: tuple[SDKEnumReference, ...]
    exceptions: tuple[SDKExceptionReference, ...]
    client_methods: tuple[SDKMethodReference, ...]
