[supervisord]
nodaemon=true
user=root

[program:api]
command=uv run --no-sync python -m tracker.serve
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=uv run --no-sync taskiq worker --no-configure-logging tracker.config:broker tracker.utils
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
