name: basedpyright
on: [pull_request, push]

jobs:
  setup-uv:
    uses: ./.github/workflows/_setup_uv.yaml
    with:
      python-version: "3.12"

  run-basedpyright:
    needs: setup-uv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: make install

      - name: Run basedpyright
        run: make typecheck
