name: validate-lockfile

on:
  pull_request:
    branches: [dev, prod]
  push:
    branches: [dev, prod]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lockfile:
    strategy:
      matrix:
        project_path:
          - "."
          - services/tracker
          - infra
    uses: vals-ai/.github/.github/workflows/validate-lockfile.yaml@main
    with:
      project_path: ${{ matrix.project_path }}
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      SSH_PRIVATE_KEY: ${{ secrets.SUBMODULES_SSH_KEY }}
